'use client';
import {useEffect,useState} from 'react';
import Script from 'next/script';
import {launchIdentity,redirectSession,type IdentityLaunch,type IdentitySdk,type IdentitySummary} from '@/lib/identity-browser';
const storage='bizproof:identity-pilot:v1';
const labels:Record<IdentitySummary['status'],string>={pending:'인증 결과 대기',verified:'서버에서 본인확인 결과 검증 완료',failed:'인증 실패',cancelled:'요청 취소',consumed:'사용된 인증 결과',expired:'요청 만료'};
export default function IdentityPilot({companies}:{companies:{id:string;name:string;documentHash:string}[]}){
 const [company,setCompany]=useState(companies[0]?.id??''),[consent,setConsent]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[session,setSession]=useState<IdentitySummary|null>(null),[message,setMessage]=useState('');
 async function command(body:unknown):Promise<IdentitySummary&{launch?:IdentityLaunch}>{const r=await fetch('/api/identity/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),redirect:'error'});const b=await r.json() as IdentitySummary&{launch?:IdentityLaunch;error?:string};if(!r.ok)throw Error(b.error??'인증 상태를 확인하지 못했습니다.');return b;}
 function remember(value:IdentitySummary){const summary:IdentitySummary={id:value.id,status:value.status,expiresAt:value.expiresAt,documentHash:value.documentHash,mode:value.mode,documentSigned:false};setSession(summary);sessionStorage.setItem(storage,JSON.stringify(summary));}
 async function check(id:string){const result=await command({action:'check',id});remember(result);return result;}
 useEffect(()=>{let active=true;void(async()=>{try{const raw=sessionStorage.getItem(storage),saved=raw?JSON.parse(raw) as IdentitySummary:null;const id=redirectSession(location.href,saved);if(saved&&saved.expiresAt>Date.now()&&active)setSession(saved);if(id){const result=await command({action:'check',id});if(active){remember(result);history.replaceState(null,'','/identity-pilot');}}}catch{if(active)setMessage('인증 복귀 정보를 확인하지 못했습니다. 현재 요청 상태를 다시 확인해 주세요.');}})();return()=>{active=false;};},[]);
 async function run(action:'start'|'check'|'cancel'){if(busy)return;setBusy(true);setMessage('');try{
  if(action==='start'){const selected=companies.find(c=>c.id===company);if(!selected||!consent)throw Error('기업과 본인확인 동의를 확인해 주세요.');const sdk=(window as Window&{PortOne?:IdentitySdk}).PortOne;if(!sdk||!ready)throw Error('인증 창을 준비 중입니다.');const next=await command({action:'start',companyId:selected.id,documentHash:selected.documentHash,consent:true});remember(next);if(!next.launch)throw Error('인증 요청 정보를 받지 못했습니다.');remember(await launchIdentity(sdk,next,next.launch,location.origin,check));}
  else if(session){remember(action==='check'?await check(session.id):await command({action:'cancel',id:session.id}));}
 }catch(e){setMessage(e instanceof Error?e.message:'인증 처리에 실패했습니다.');}finally{setBusy(false);}}
 return <main className="issuance-page"><Script src="https://cdn.portone.io/v2/browser-sdk.js" onReady={()=>setReady(true)} onError={()=>setMessage('인증 창을 불러오지 못했습니다. 연결을 확인한 뒤 새로고침해 주세요.')}/><section className="issuance-intro"><a href="/issuance">자격 발급으로</a><h1>본인확인 공급자 연결 시험</h1><p>이 화면은 승인된 파일럿 담당자의 공급자 연결 시험입니다. 시험 결과가 기업 자격 발급이나 문서 전자서명을 자동 승인하지 않습니다.</p></section><section className="issuance-card"><label>대상 기업 <select value={company} onChange={e=>{setCompany(e.target.value);setConsent(false);}} disabled={busy||session?.status==='pending'}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>확인할 내용: 선택한 기업의 인증 공급자 연결 인수시험에 참여합니다.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy}/> 본인확인 공급자의 안내를 확인하고 인증을 진행합니다.</label><p><button onClick={()=>void run('start')} disabled={!ready||busy||!consent||!company||session?.status==='pending'}>본인확인 시작</button></p>{session&&<div role="status"><h2>{labels[session.status]}</h2><p>{session.mode==='live'?'운영 채널 검증':session.mode==='provider-test'?'공급자 테스트 채널 검증':'공급자 결과 조회 전'}</p><p>문서 전자서명과 기업 담당자 권한은 별도 확인이 필요합니다.</p><button disabled={busy} onClick={()=>void run('check')}>현재 요청 상태 확인</button>{session.status==='pending'&&<button disabled={busy} onClick={()=>void run('cancel')}>현재 요청 취소</button>}</div>}{message&&<p role="alert">{message}</p>}</section></main>;
}
