import {sdkManifestSchema,sdkPreparationSchema,sdkContractSchema} from '@/lib/midnight-sdk-schema';
import {getChatGPTUser,getActiveRole} from '@/app/chatgpt-auth';
import {z} from 'zod';
export const dynamic='force-dynamic';
const hex=z.string().regex(/^[a-f\d]{64}$/i);
async function authorized(req:Request){if(!await getChatGPTUser())return Response.json({error:'로그인이 필요합니다.'},{status:401});const url=new URL(req.url);if(!['localhost','127.0.0.1'].includes(url.hostname))return Response.json({error:'SDK 브리지는 로컬 개발 환경에서만 사용할 수 있습니다.'},{status:503});if(req.headers.get('origin')&&req.headers.get('origin')!==url.origin)return Response.json({error:'허용되지 않는 출처입니다.'},{status:403});}
async function bridge(path:string,method='GET'){const r=await fetch('http://127.0.0.1:4011'+path,{method,redirect:'manual',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('SDK 브리지·인덱서 또는 컴파일 산출물을 확인하세요.');return r.json();}
function failure(e:unknown){return Response.json({error:e instanceof z.ZodError||e instanceof SyntaxError?'SDK 요청 형식을 확인하세요.':'SDK 브리지에 연결하지 못했거나 검증이 실패했습니다. 최신 contracts/bridge.mjs와 인덱서 상태를 확인하세요.'},{status:e instanceof z.ZodError||e instanceof SyntaxError?400:503});}
export async function GET(req:Request){const denied=await authorized(req);if(denied)return denied;try{const url=new URL(req.url);const id=url.searchParams.get('address');const path=id?'/sdk/contract?address='+hex.parse(id)+(url.searchParams.has('request')?'&request='+hex.parse(url.searchParams.get('request')):''):'/sdk/manifest';const data=(id?sdkContractSchema:sdkManifestSchema).parse(await bridge(path));return Response.json(data,{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(req:Request){const denied=await authorized(req);if(denied)return denied;const role=(await getActiveRole())??'';if(role!=='admin')return Response.json({error:'관리자 역할에서 SDK 준비 검사를 실행하세요.'},{status:403});try{const text=await req.text();if(text.length>1000)return Response.json({error:'요청이 너무 큽니다.'},{status:413});z.object({action:z.literal('prepare')}).strict().parse(JSON.parse(text));return Response.json(sdkPreparationSchema.parse(await bridge('/sdk/prepare','POST')),{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
