"use client";
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
type Row=Record<string,string|number|null>;
const row=z.record(z.union([z.string(),z.number(),z.null()]));
const detailSchema=z.object({identity:z.string(),summary:row,months:z.array(z.object({label:z.string(),value:z.number()})),rows:z.array(row),page:z.number()});
type Detail=z.infer<typeof detailSchema>;
const when=(value:Row[string])=>value?new Date(String(value)).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
const source=(value:Row[string])=>value==='login'?'로그인 확인':value==='self-reported'?'직접 입력 · 미인증':'익명 브라우저';
export default function CustomerDetail({identity,onClose}:{identity:string|null;onClose:()=>void}){
 const [page,setPage]=useState(0),[data,setData]=useState<Detail|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!identity)return;const abort=new AbortController();let active=true;queueMicrotask(()=>{if(active){setData(null);setError('');}});void fetch('/api/admin/analytics/customer?'+new URLSearchParams({identity,page:String(page)}),{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw Error(r.status===403?'관리자 로그인이 필요합니다.':'이력을 불러오지 못했습니다.');return r.json();}).then(v=>{if(active)setData(detailSchema.parse(v));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;abort.abort();};},[identity,page]);
 return <Sheet open={!!identity} onOpenChange={open=>{if(!open)onClose();}}><SheetContent className="analytics-detail" showCloseButton={false}><SheetHeader><SheetTitle>고객 방문 이력</SheetTitle><SheetDescription>전체 보관 기간 기준 · 동일 계정 또는 브라우저 쿠키의 기록</SheetDescription></SheetHeader><SheetClose aria-label="고객 이력 닫기" className="analytics-detail-close">닫기 ✕</SheetClose>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">방문 이력 조회 중…</p>}{data&&<><div className="analytics-person"><h2>{data.summary.display_name||'익명 방문자'}</h2><p>{source(data.summary.name_source)}{data.summary.company?' · '+data.summary.company:''}</p><code>{identity}</code></div><div className="analytics-person-stats"><span><b>{data.summary.visits}</b>누적 방문</span><span><b>{data.summary.ip_count}</b>관찰된 IP</span><span><b>{data.summary.page_count}</b>방문 페이지</span></div><p className="analytics-person-dates">첫 방문 {when(data.summary.first_seen)}<br/>최근 방문 {when(data.summary.last_seen)}</p><h3>월별 이용 기록</h3><div className="analytics-months">{data.months.map(m=><span key={m.label}>{m.label} <b>{m.value}회</b></span>)}</div><h3>실제 방문 타임라인</h3><ol className="analytics-timeline">{data.rows.map(r=><li key={String(r.id)}><time>{when(r.occurred_at)}</time><strong>{r.path}</strong><p>{r.ip||'IP 미확인'} · {[r.country,r.region,r.city].filter(Boolean).join(' / ')||'지역 미확인'}</p><p>{r.browser} · {r.os} · {r.device}</p><details><summary>브라우저 원문·지역 출처</summary><p>{r.user_agent}</p><p>{r.geo_source}</p></details></li>)}</ol>{!data.rows.length&&<p>보관된 방문 기록이 없습니다.</p>}<div className="analytics-detail-paging"><button disabled={!page} onClick={()=>setPage(v=>v-1)}>이전 50개</button><span>{page+1}페이지</span><button disabled={(page+1)*50>=Number(data.summary.visits)} onClick={()=>setPage(v=>v+1)}>다음 50개</button></div><p>같은 IP가 같은 사람을 의미하지 않습니다. <a href="https://db-ip.com" target="_blank" rel="noreferrer">IP Geolocation by DB-IP</a></p></>}</SheetContent></Sheet>;
}
