"use client";
import Link from 'next/link';
import {z} from 'zod';
import {useEffect,useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import CustomerDetail from './customer-detail';
import {kstParts} from '@/lib/visitor-analytics';
type Row=Record<string,string|number|null>;
const series=z.array(z.object({label:z.string(),value:z.number()}));
const reportSchema=z.object({month:z.string(),summary:z.object({visits:z.number(),visitors:z.number(),customers:z.number(),countries:z.number()}),daily:series,countries:series,browsers:series,months:series,total:z.number(),rows:z.array(z.record(z.union([z.string(),z.number(),z.null()]))),refreshedAt:z.string(),devices:series,regions:series,pages:series,identities:series,returning:series,lifetime:z.object({visits:z.number(),visitors:z.number(),first_seen:z.string().nullable(),last_seen:z.string().nullable()}),geo:z.object({available:z.boolean(),buildDate:z.string().nullable(),status:z.string()})});
type Report=z.infer<typeof reportSchema>;
export default function AnalyticsDashboard({administrator,localPreview,canChangePassword}:{administrator:string;localPreview:boolean;canChangePassword:boolean}){
 const [customer,setCustomer]=useState<string|null>(null);
 const [month,setMonth]=useState(()=>kstParts().month),[kind,setKind]=useState<'visits'|'customers'>('visits'),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 useEffect(()=>{const controller=new AbortController();let active=true;queueMicrotask(()=>{if(active){setBusy(true);setError('');}});void fetch('/api/admin/analytics?'+new URLSearchParams({month,kind,search:query,page:String(page)}),{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error(r.status===403?'관리자 세션을 확인하고 다시 로그인하세요.':'분석 자료를 불러오지 못했습니다.');return r.json();}).then(v=>{if(active)setReport(reportSchema.parse(v));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;controller.abort();};},[month,kind,query,page,refresh]);
 useEffect(()=>{let current=kstParts().month;const timer=setInterval(()=>{const next=kstParts().month;if(current!==next){const previous=current;setMonth(m=>m===previous?next:m);setPage(0);current=next;}if(!document.hidden)setRefresh(v=>v+1);},60000);return()=>clearInterval(timer);},[]);
 const changeMonth=(value:string)=>{setMonth(value);setPage(0);};
 const cell=(value:Row[string])=>value===null||value===undefined||value===''?'미확인':String(value);
 const time=(value:Row[string])=>value?new Date(String(value)).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
 return <main className="analytics-shell"><aside className="analytics-nav"><Link href="/" className="analytics-brand">BizProof<span>운영 관리</span></Link><b>방문자 분석</b><a href="#customer-records">방문·고객 기록</a><a href="#collection-status">보관·수집 상태</a><Link href="/">기업 자격 서비스</Link><Link href="/privacy/analytics">수집 안내</Link>{canChangePassword&&<Link href="/admin/security">비밀번호 변경</Link>}<div className="analytics-account">{administrator}<small>{localPreview?'로컬 개발 미리보기':'지정 서비스 관리자'}</small><form action="/api/admin/logout" method="post"><button>로그아웃</button></form></div></aside>
 <div className="analytics-main"><header><div><span className="admin-eyebrow">VISITOR INTELLIGENCE</span><h1>방문과 고객을 한눈에</h1><p>한국 시간 기준 월별 분석 · 원본 기록 누적 보관</p></div><div className="analytics-controls"><label>조회 월<input type="month" aria-label="조회 월" value={month} onChange={e=>changeMonth(e.target.value)}/></label><button onClick={()=>setRefresh(v=>v+1)} disabled={busy}>새로고침</button></div></header>
 {localPreview&&<p className="analytics-banner">로컬 개발 전용 미리보기입니다. 실제 IP·국가·지역과 고객 이름이 없는 값은 미확인으로 표시합니다.</p>}
 {error&&<p role="alert" className="analytics-banner">{error} <Link href="/admin/login">관리자 로그인</Link></p>}{busy&&<p role="status">방문 기록을 불러오는 중…</p>}
 {report&&<><section id="collection-status" className="analytics-status"><div><b>누적 기록 영구 보관</b><span>전체 {report.lifetime.visits.toLocaleString()}회 · 자동 삭제 없음 · 월별 분류</span></div><div><b>{report.geo.available?'국가·지역 조회 활성':'국가·지역 미연결'}</b><span>{report.geo.buildDate?'DB-IP '+report.geo.buildDate.slice(0,7)+' 기준 · 서버 내부 조회':'확인되지 않은 지역은 미확인으로 표시'}{report.geo.status==='update-failed'?' · 갱신 실패, 이전 DB 사용':''}</span></div></section><section className="analytics-kpis">{[['방문 횟수',report.summary.visits],['방문 브라우저',report.summary.visitors],['로그인 고객',report.summary.customers],['확인된 국가',report.summary.countries]].map(([label,value])=><article key={label}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong><small>{month} 기준</small></article>)}</section>
 <section className="analytics-chart-grid"><article className="analytics-card"><h2>일별 방문 추이</h2><p>중복 방문을 포함한 페이지 조회 수</p>{report.daily.length?<div style={{height:260,width:'100%'}}><ResponsiveContainer><BarChart data={report.daily}><CartesianGrid vertical={false} stroke="#e7edf5"/><XAxis dataKey="label" tickFormatter={s=>s.slice(8)}/><YAxis allowDecimals={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="value" name="방문 횟수" fill="#5265dc" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div>:<p className="analytics-empty">이 달의 방문 기록이 없습니다.</p>}</article><article className="analytics-card"><h2>국가별 방문</h2><p>IP 기반 대략적인 국가 · 미확인 포함</p>{report.countries.map(c=><div className="analytics-meter" key={c.label}><span>{c.label}</span><progress max={Math.max(report.summary.visits,1)} value={c.value}/><b>{c.value}</b></div>)}</article></section>
 <section className="analytics-chart-grid"><article className="analytics-card"><h2>브라우저 구성</h2>{report.browsers.map(c=><div className="analytics-meter" key={c.label}><span>{c.label}</span><progress max={Math.max(report.summary.visits,1)} value={c.value}/><b>{c.value}</b></div>)}</article><article className="analytics-card"><h2>월별 누적 기록</h2><p>최근 24개 기록 월 · 그 이전도 조회 월로 검색</p><div className="analytics-months">{report.months.map(m=><button key={m.label} onClick={()=>changeMonth(m.label)}>{m.label}<b>{m.value.toLocaleString()}회</b></button>)}</div></article></section>
 <section className="analytics-chart-grid"><Meters title="방문 페이지 순위" items={report.pages} total={report.summary.visits}/><Meters title="대략적인 지역 분포" items={report.regions} total={report.summary.visits}/></section>
 <section className="analytics-chart-grid analytics-triple"><Meters title="기기 구성" items={report.devices} total={report.summary.visits}/><Meters title="방문 고객 구분" items={report.identities} total={report.identities.reduce((n,v)=>n+v.value,0)}/><Meters title="신규·재방문 브라우저" items={report.returning} total={report.summary.visitors} note="재방문: 조회 월 이전에도 기록이 있는 브라우저"/></section>
 <section id="customer-records" className="analytics-card"><div className="analytics-table-head"><div><h2>{kind==='visits'?'상세 방문 기록':'고객·익명 방문자'}</h2><p>로그인 확인·직접 입력·익명을 구분합니다. 이름을 누르면 전체 기간 방문 이력이 열립니다.</p></div><div className="analytics-tabs"><button aria-pressed={kind==='visits'} onClick={()=>{setKind('visits');setPage(0);}}>방문 기록</button><button aria-pressed={kind==='customers'} onClick={()=>{setKind('customers');setPage(0);}}>고객 정보</button></div></div>
 <form className="analytics-search" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(0);}}><input aria-label="방문 기록 검색" placeholder="이름, 회사, IP 또는 방문 페이지 검색" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/><button>검색</button></form>
 <div className="analytics-table-scroll"><table><thead><tr>{(kind==='visits'?['방문 시각','이름 / 계정','IP','국가 · 지역','브라우저 / 기기','방문 페이지']:['이름','계정 식별자','방문 수','관찰된 IP 수','첫 방문 (조회 월)','최근 방문 (조회 월)']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.rows.map((r,i)=><tr key={String(r.id??r.identity??i)}>{kind==='visits'?<><td>{time(r.occurred_at)}</td><td><button className="analytics-person-link" onClick={()=>setCustomer(String(r.identity))}>{r.display_name||'익명 방문자'}</button><small>{identityLabel(r.name_source)}</small>{r.company&&<small>{r.company}</small>}</td><td>{cell(r.ip)}</td><td>{[r.country,r.region,r.city].filter(Boolean).join(' · ')||'미확인'}<small>{cell(r.geo_source)}</small></td><td>{cell(r.browser)} · {cell(r.os)}<small>{cell(r.device)}</small><details><summary>브라우저 원문</summary>{cell(r.user_agent)}</details></td><td>{cell(r.path)}</td></>:<><td><button className="analytics-person-link" onClick={()=>setCustomer(String(r.identity))}>{r.display_name||'익명 방문자'}</button><small>{identityLabel(r.name_source)}</small>{r.company&&<small>{r.company}</small>}</td><td>{cell(r.user_id??r.identity)}</td><td>{cell(r.visits)}</td><td>{cell(r.ip_count)}</td><td>{time(r.first_seen)}</td><td>{time(r.last_seen)}</td></>}</tr>)}</tbody></table></div>{!report.rows.length&&<p className="analytics-empty">조건에 맞는 기록이 없습니다.</p>}
 <div className="analytics-pagination"><span>{report.total.toLocaleString()}개 · {page+1}페이지 · 검색은 목록에 적용</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전</button><button disabled={(page+1)*50>=report.total} onClick={()=>setPage(p=>p+1)}>다음</button></div></section>
 <footer>최근 조회 {time(report.refreshedAt)} · 1분마다 화면 갱신 · 자동 삭제 없음 · 관리자 조회 감사 기록 보관<br/>통계는 조회 월 전체 기준이며 검색은 아래 목록에 적용됩니다. 브라우저 수는 실제 사람 수와 다릅니다.<br/><a href="https://db-ip.com" target="_blank" rel="noreferrer">IP Geolocation by DB-IP</a> · 무료 지역 DB 매월 갱신 · VPN·통신사에 따라 지역이 다를 수 있습니다.</footer></>}
 </div><CustomerDetail key={customer??'none'} identity={customer} onClose={()=>setCustomer(null)}/></main>;
}

function identityLabel(value:Row[string]){return value==='login'?'로그인 확인':value==='self-reported'?'직접 입력 · 미인증':'익명 브라우저';}
function Meters({title,items,total,note}:{title:string;items:{label:string;value:number}[];total:number;note?:string}){const names:Record<string,string>={desktop:'데스크톱',mobile:'모바일',tablet:'태블릿',bot:'봇','self-reported':'직접 입력 · 미인증',login:'로그인 확인',anonymous:'익명 브라우저','/welcome':'입구 페이지','/guide':'이용자 가이드','/process':'처리 과정 관제','/':'홈','/?view=apply':'신청하기','/?view=progress':'진행 현황'};return <article className="analytics-card"><h2>{title}</h2>{note&&<p>{note}</p>}{items.map(v=><div className="analytics-meter" key={v.label}><span title={v.label}>{names[v.label]??v.label}</span><progress aria-label={names[v.label]??v.label} max={Math.max(total,1)} value={v.value}/><b>{v.value}</b></div>)}{!items.length&&<p className="analytics-empty">이 달의 기록이 없습니다.</p>}</article>;}
