const fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),assert=require('node:assert/strict'),Module=require('node:module');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
fs.mkdirSync('outputs',{recursive:true});process.env.BIZPROOF_DATA_DIR=fs.mkdtempSync(path.resolve('outputs/process-test-'));
let user=null,persona='company';
const original=Module._load;Module._load=function(id,...rest){if(id==='cloudflare:workers')return require('../lib/node-bindings.ts');if(id==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>user};if(id==='next/headers')return {cookies:async()=>({get:()=>({value:persona})})};if(id.startsWith('@/'))id=path.resolve(id.slice(2))+'.ts';return original.call(this,id,...rest);};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const {env}=require('../lib/node-bindings.ts'),store=require('../lib/store.ts'),{preparedDemoState}=require('../lib/prepared-demo.ts'),{prepareApplication}=require('../lib/application-flow.ts');
 const {observedApplications}=require('../lib/application-process.ts'),{listProcessRuns}=require('../lib/process-store.ts'),{readProcessStream}=require('../lib/process-stream.ts'),{safeProcessData}=require('../lib/process-types.ts');
 async function fixture(change=()=>{}){const s=await preparedDemoState();change(s);const ctx={owner:'demo-'+crypto.randomUUID(),actor:'operator-a',role:'company',authMode:'demo'};await env.DB.prepare('INSERT INTO workspaces(owner,payload,version) VALUES (?,?,0)').bind(ctx.owner,JSON.stringify(s)).run();const input={companyId:s.preparedDemo.companyId,consent:true,items:await Promise.all(s.preparedDemo.policyIds.map(async policyId=>{const p=await prepareApplication(s,ctx,{companyId:s.preparedDemo.companyId,policyId});return {policyId,key:crypto.randomUUID(),credentialId:p.selected.id,previewHash:p.previewHash};}))};return {s,ctx,input};}
 async function consume(f){let run;const result=await readProcessStream(await observedApplications(f.s,f.ctx,f.input,0),r=>run=r);return {run,result};}
 const f=await fixture();const realSave=store.saveState;let release,entered;const gate=new Promise(r=>release=r),reached=new Promise(r=>entered=r);
 store.saveState=async(...args)=>{entered();await gate;return realSave(...args);};
 let live;const consuming=readProcessStream(await observedApplications(f.s,f.ctx,f.input,0),r=>live=r);
 await reached;assert.equal(live.status,'running');assert.equal(live.committed,false);assert.ok(live.events.some(e=>e.stage==='commit'&&e.state==='running'));assert.equal((await store.readState(f.ctx.owner)).state.presentations.length,0);
 release();const result=await consuming;store.saveState=realSave;
 assert.ok(result.outcomes.every(o=>o.ok));assert.equal(live.status,'succeeded');assert.equal(live.committed,true);assert.ok(live.events.some(e=>e.stage==='commit'&&e.state==='success'));
 assert.ok(live.events.some(e=>e.stage==='credential'&&e.data.checks?.some(c=>c.label.includes('서명')&&c.pass)));
 assert.equal(new Set(live.events.filter(e=>e.data.nonce).map(e=>e.data.nonce)).size,2);
 assert.equal(new Set(live.events.filter(e=>e.stage==='signature'&&e.state==='success').map(e=>e.data.credentialId)).size,1);
 assert.ok(live.events.every((e,i)=>e.seq===i+1&&e.elapsedMs>=0&&(!i||e.elapsedMs>=live.events[i-1].elapsedMs)));
 const history=(await listProcessRuns(f.ctx))[0];assert.equal(history.id,live.id);assert.equal(history.committed,true);assert.equal((await store.readState(f.ctx.owner)).state.presentations.length,2);
 const text=JSON.stringify(live);assert.ok(!text.includes(f.s.issuers[0].privateKey.d));assert.ok(!text.includes(f.s.credentials[0].signature));assert.ok(!text.includes('"claims"'));assert.deepEqual(safeProcessData({nonce:'safe',privateKey:'secret',token:'secret',claims:{revenue:1}}),{nonce:'safe'});
 const replay=await readProcessStream(await observedApplications(f.s,f.ctx,f.input,1),()=>{});assert.ok(replay.outcomes.every(o=>o.ok&&o.receipt.replayed));
 assert.equal((await listProcessRuns(f.ctx))[0].events.filter(e=>e.stage==='signature').length,0);
 const partial=await fixture();partial.s.policies.find(p=>p.id===partial.input.items[1].policyId).status='archived';const pr=await consume(partial);assert.equal(pr.run.status,'partial');assert.equal(pr.run.committed,true);assert.equal((await store.readState(partial.ctx.owner)).state.presentations.length,1);assert.ok(pr.run.events.some(e=>e.state==='failed'));
 const manual=await fixture(s=>s.policyAutomation.forEach(p=>p.enabled=false));const mr=await consume(manual);assert.ok(mr.run.events.filter(e=>e.stage==='verification').every(e=>e.state==='waiting'));assert.ok(mr.result.outcomes.every(o=>o.ok&&!o.receipt.verifiedAt));
 const conflict=await fixture();await env.DB.prepare('UPDATE workspaces SET version=1 WHERE owner=?').bind(conflict.ctx.owner).run();let conflicted;await assert.rejects(readProcessStream(await observedApplications(conflict.s,conflict.ctx,conflict.input,0),r=>conflicted=r),/동시에/);assert.equal(conflicted.committed,false);assert.equal(conflicted.status,'failed');assert.equal((await store.readState(conflict.ctx.owner)).state.presentations.length,0);assert.ok(!conflicted.events.some(e=>e.stage==='commit'&&e.state==='success'));
 const revoked=await fixture();revoked.s.credentials[0].status='revoked';const rr=await consume(revoked);assert.equal(rr.run.status,'failed');assert.equal(rr.run.committed,false);assert.equal((await store.readState(revoked.ctx.owner)).state.presentations.length,0);
 const logsUnavailable=await fixture();const processStore=require('../lib/process-store.ts'),realLogSave=processStore.saveProcessRun;processStore.saveProcessRun=async()=>{throw Error('Unavailable')};const lr=await consume(logsUnavailable);processStore.saveProcessRun=realLogSave;assert.equal(lr.run.committed,true);assert.equal(lr.run.historySaved,false);assert.equal((await store.readState(logsUnavailable.ctx.owner)).state.presentations.length,2);
 const disconnected=await fixture();const response=await observedApplications(disconnected.s,disconnected.ctx,disconnected.input,0);const reader=response.body.getReader();await reader.read();await reader.cancel();let done;for(let i=0;i<100;i++){done=(await listProcessRuns(disconnected.ctx))[0];if(done.status!=='running')break;await delay(10);}assert.equal(done.status,'succeeded');assert.equal((await store.readState(disconnected.ctx.owner)).state.presentations.length,2);
 const api=require('../app/api/process-runs/route.ts');const get=id=>api.GET(new Request('https://app.test/api/process-runs'+(id?'?id='+id:'')));
 assert.equal((await get()).status,401);user={userId:f.ctx.actor,storageOwner:f.ctx.owner,authMode:'demo',allowedRoles:['company','admin','buyer']};assert.equal((await (await get(live.id)).json()).runs[0].id,live.id);
 user={...user,storageOwner:partial.ctx.owner};assert.deepEqual((await (await get(live.id)).json()).runs,[]);user={...user,storageOwner:f.ctx.owner,userId:'operator-b'};assert.deepEqual((await (await get(live.id)).json()).runs,[]);persona='admin';assert.equal((await (await get(live.id)).json()).runs.length,1);persona='buyer';assert.equal((await get()).status,403);
 await assert.rejects(listProcessRuns({...f.ctx,authMode:'keycloak'}));
 await assert.rejects(readProcessStream(new Response('{"type":"run","run":'+JSON.stringify(live)+'}\n',{headers:{'Content-Type':'application/x-ndjson'}}),()=>{}),/연결이 끊어/);
 console.log('PASS process monitor: real streamed stages before commit, durable SQLite, signatures and two nonces, redaction, replay, partial/manual/revoked, CAS rollback, disconnect continuation, workspace/actor/role ACL, missing completion');
})().catch(e=>{console.error(e);process.exit(1)});
