const fs=require('fs'),path=require('path'),ts=require('typescript'),assert=require('node:assert/strict'),Module=require('module');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
(async()=>{const {seedState}=require('../lib/seed.ts'),{sign}=require('../lib/signatures.ts'),{credentialPayload}=require('../lib/domain.ts');let state=await seedState(),version=0,role='company',actor='alice',mode='demo',write=true,offline=false;const env={};const original=Module._load,nativeFetch=global.fetch;
Module._load=function(id,...rest){if(id==='cloudflare:workers')return {env};if(id==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>({userId:actor,storageOwner:'room',allowedRoles:[role],displayName:actor,authMode:mode})};if(id==='next/headers')return {cookies:async()=>({get:()=>({value:role})})};if(id==='@/lib/store')return {readState:async()=>({state:structuredClone(state),version}),saveState:async(_owner,s)=>{state=s;version++},ConflictError:class extends Error{}};if(id.startsWith('@/'))id=path.resolve(id.slice(2))+'.ts';return original.call(this,id,...rest);};
try{const api=require('../app/api/platform/route.ts');async function post(action,data={},status=200){const r=await api.POST(new Request('http://localhost/api/platform',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({action,...data})}));const v=await r.json();assert.equal(r.status,status,JSON.stringify(v));return v;}
const choice={companyId:'hanbit',policyId:'vendor-standard'};
await post('configure-automatic-verification',{policyId:choice.policyId,enabled:true},403);role='grant';await post('configure-automatic-verification',{policyId:choice.policyId,enabled:true},403);role='buyer';await post('configure-automatic-verification',{policyId:choice.policyId,enabled:true});role='company';
let preview=await post('prepare-application',choice);assert.equal(preview.ready,true);assert.equal(preview.selected.id,'credential-hanbit');const input={...choice,previewHash:preview.previewHash,key:crypto.randomUUID(),consent:true};const before=state.requests.length;
await post('submit-application',{...input,consent:false},400);assert.equal(state.requests.length,before);
const submitted=await post('submit-application',input);assert.equal(submitted.status,'verified');const count=state.presentations.length;const repeat=await post('submit-application',input);assert.equal(repeat.requestId,submitted.requestId);assert.equal(repeat.replayed,true);assert.equal(state.presentations.length,count);await post('submit-application',{...input,key:crypto.randomUUID()},409);
assert.ok(state.audit.some(a=>a.actor==='system:policy-verifier'&&a.target===submitted.requestId));assert.ok(state.audit.some(a=>a.action==='application-submit'));
// Recipient opt-in changes invalidate consent snapshots; no automatic acceptance by default.
const grant={companyId:'hanbit',policyId:'grant-startup'};preview=await post('prepare-application',grant);role='grant';await post('configure-automatic-verification',{policyId:grant.policyId,enabled:true});role='company';await post('submit-application',{...grant,key:crypto.randomUUID(),consent:true,previewHash:preview.previewHash},409);role='grant';await post('configure-automatic-verification',{policyId:grant.policyId,enabled:false});role='company';preview=await post('prepare-application',grant);const manual=await post('submit-application',{...grant,key:crypto.randomUUID(),consent:true,previewHash:preview.previewHash});assert.equal(manual.status,'submitted');
// Changed/revoked credential between preview and submit fails closed, without creating requests.
state.requests=[];state.presentations=[];state.applicationSubmissions=[];preview=await post('prepare-application',choice);state.credentials.find(c=>c.id==='credential-hanbit').status='revoked';await post('submit-application',{...choice,key:crypto.randomUUID(),consent:true,previewHash:preview.previewHash},422);assert.equal(state.requests.length,0);
state=await seedState();const c=state.credentials.find(c=>c.id==='credential-hanbit');const other=structuredClone(c);other.id='other-credential';other.claims.revenue+=100;other.signature=await sign(state.issuers.find(i=>i.id===c.issuerId).privateKey,credentialPayload(other));state.credentials.push(other);preview=await post('prepare-application',choice);assert.equal(preview.needsChoice,true);assert.equal(preview.ready,false);preview=await post('prepare-application',{...choice,credentialId:c.id});assert.equal(preview.ready,true);state.walletEntries=[{credentialId:c.id,archived:true}];await post('prepare-application',{...choice,credentialId:c.id},422);
// Operational mode: ACL outage, write denial, unreviewed credentials, actor-bound authority.
// A rolling age boundary crossing after consent must require a new preview.
const RealDate=Date;let clock=Date.UTC(2026,8,25);
try{global.Date=class extends RealDate{constructor(...args){if(args.length)super(...args);else super(clock);}static now(){return clock;}};
state=await seedState();state.policies.find(p=>p.id===choice.policyId).maxAgeMonths=24;
preview=await post('prepare-application',choice);assert.equal(preview.selected.eligible,true);const requestCount=state.requests.length;clock++;
await post('submit-application',{...choice,key:crypto.randomUUID(),consent:true,previewHash:preview.previewHash},409);assert.equal(state.requests.length,requestCount);
}finally{global.Date=RealDate;}
state=await seedState();mode='keycloak';Object.assign(env,{BIZPROOF_ACCESS_CONTROL:'openfga',OPENFGA_URL:'http://127.0.0.1:18380',OPENFGA_STORE_ID:'01ARZ3NDEKTSV4RRFFQ69G5FAV',OPENFGA_MODEL_ID:'01ARZ3NDEKTSV4RRFFQ69G5FAW'});const {fgaCompany}=require('../lib/openfga.ts');global.fetch=async(_url,init)=>{if(offline)throw Error('offline');const t=JSON.parse(init.body).tuple_key;return Response.json({allowed:t.object===fgaCompany('room','hanbit')&&(t.relation!=='can_write_business'||write)});};
await post('prepare-application',{...choice,companyId:'nova'},403);offline=true;await post('prepare-application',choice,503);offline=false;preview=await post('prepare-application',choice);assert.equal(preview.ready,false);
const c2=state.credentials.find(c=>c.id==='credential-hanbit'),hash='a'.repeat(64);state.evidence.push({id:'e',companyId:'hanbit',sha256:hash,key:'e',name:'review.txt',size:5,mime:'text/plain',createdAt:new Date().toISOString()});c2.source={kind:'document-review',reference:'reviewed',period:'2026',method:'fixture reviewed',reviewer:'reviewer',reviewedAt:new Date().toISOString(),documents:[{id:'e',name:'review.txt',sha256:hash}],notice:'fixture'};c2.signature=await sign(state.issuers[0].privateKey,credentialPayload(c2));preview=await post('prepare-application',choice);assert.equal(preview.ready,false);role='issuer';await post('issue-authority',{credentialId:c2.id,holderUserId:'alice',holder:'Alice',title:'Officer',scope:'buyer',days:1});role='company';preview=await post('prepare-application',choice);assert.equal(preview.ready,true);assert.ok(preview.selected.authorityId);actor='bob';assert.equal((await post('prepare-application',choice)).ready,false);actor='alice';write=false;await post('submit-application',{...choice,key:crypto.randomUUID(),previewHash:preview.previewHash,consent:true},403);write=true;
const review=await post('request-issuance-review',{...choice,evidenceIds:['e']});assert.equal(review.status,'pending');const same=await post('request-issuance-review',{...choice,evidenceIds:['e']});assert.equal(same.id,review.id);await post('request-issuance-review',{...choice,evidenceIds:['missing']},404);
console.log('PASS applications: automatic matching, conflicting credentials, explicit consent, stale preview, recipient opt-in, manual fallback, idempotency, duplicate prevention, revocation, ACL, actor authority, review queue');
}finally{Module._load=original;global.fetch=nativeFetch}})().catch(e=>{console.error(e);process.exit(1)});
