const fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),assert=require('node:assert/strict'),Module=require('node:module');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const original=Module._load;Module._load=function(id,...rest){if(id==='cloudflare:workers')return {env:{}};return original.call(this,id,...rest);};
(async()=>{const {preparedDemoState}=require('../lib/prepared-demo.ts'),{prepareApplication}=require('../lib/application-flow.ts'),{submitApplications}=require('../lib/application-batch.ts'),{inspectCredential}=require('../lib/credential-family.ts');
let s=await preparedDemoState();const ctx={owner:'demo-fixture',actor:'demo-person',role:'company',authMode:'demo'};assert.equal(s.companies.length,1);assert.equal(s.credentials.length,1);assert.equal(s.presentations.length,0);assert.ok((await inspectCredential(s,s.credentials[0])).valid);
async function input(){return {companyId:s.preparedDemo.companyId,consent:true,items:await Promise.all(s.preparedDemo.policyIds.map(async policyId=>{const p=await prepareApplication(s,ctx,{companyId:s.preparedDemo.companyId,policyId});assert.equal(p.autoVerify,true);return {policyId,key:crypto.randomUUID(),credentialId:p.selected.id,previewHash:p.previewHash};}))};}
const request=await input(),before=JSON.stringify(s);await assert.rejects(submitApplications(s,ctx,{...request,consent:false}));assert.equal(JSON.stringify(s),before);await assert.rejects(submitApplications(s,ctx,{...request,items:[request.items[0],request.items[0]]}));
let result=await submitApplications(s,ctx,request);assert.ok(result.outcomes.every(x=>x.ok&&x.receipt.status==='verified'));assert.equal(s.presentations.length,2);assert.equal(new Set(s.presentations.map(p=>p.credentialId)).size,1);assert.equal(new Set(s.presentations.map(p=>p.nonce)).size,2);assert.equal(new Set(s.presentations.map(p=>p.audience)).size,2);
result=await submitApplications(s,ctx,request);assert.ok(result.outcomes.every(x=>x.ok&&x.receipt.replayed));assert.equal(s.presentations.length,2);
s=await preparedDemoState();const partial=await input();s.policies.find(p=>p.id===partial.items[1].policyId).status='archived';result=await submitApplications(s,ctx,partial);assert.equal(result.outcomes[0].ok,true);assert.equal(result.outcomes[1].ok,false);assert.equal(s.presentations.length,1);s.policies.find(p=>p.id===partial.items[1].policyId).status='active';result=await submitApplications(s,ctx,partial);assert.equal(result.outcomes[0].receipt.replayed,true);assert.equal(result.outcomes[1].ok,true);assert.equal(s.presentations.length,2);
s=await preparedDemoState();const stale=await input();s.policyAutomation[1].enabled=false;result=await submitApplications(s,ctx,stale);assert.equal(result.outcomes[0].ok,true);assert.equal(result.outcomes[1].ok,false);assert.equal(result.outcomes[1].status,409);assert.equal(s.presentations.length,1);
s=await preparedDemoState();const revoked=await input();s.credentials[0].status='revoked';result=await submitApplications(s,ctx,revoked);assert.ok(result.outcomes.every(x=>!x.ok));assert.equal(s.presentations.length,0);
s=await preparedDemoState();const forbidden=await input();result=await submitApplications(s,{...ctx,role:'buyer'},forbidden);assert.ok(result.outcomes.every(x=>!x.ok&&x.status===403));assert.equal(s.presentations.length,0);
console.log('PASS batch: signed prepared fixture, explicit consent, distinct recipients/nonces, one credential, replay, isolated partial failure, stale consent, revocation and role denial');
})().catch(e=>{console.error(e);process.exit(1)}).finally(()=>{Module._load=original});
