const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const ctx=await browser.newContext({viewport:{width:1440,height:1100}}),page=await ctx.newPage(),base='http://localhost:5173',errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/signin-with-chatgpt?return_to=/',{waitUntil:'networkidle'});
 async function post(action,data={}){const r=await ctx.request.post(base+'/api/platform',{data:{action,...data}}),v=await r.json();assert.equal(r.status(),200,JSON.stringify(v));return v;}
 await post('switch-role',{role:'admin'});await post('create-request',{companyId:'hanbit',policyId:'vendor-standard'});await post('create-request',{companyId:'hanbit',policyId:'grant-startup'});
 await page.goto(base+'/?view=settings',{waitUntil:'networkidle'});await page.getByLabel('Midnight 연결 자격',{exact:true}).selectOption('credential-hanbit');await page.getByLabel('연결 컨트랙트 주소',{exact:true}).fill('a'.repeat(64));await page.getByLabel('보유 지갑 커밋먼트',{exact:true}).fill('b'.repeat(64));
 const panel=page.locator('section').filter({has:page.getByRole('heading',{name:'웹 자격 → Midnight 연결',exact:true})});await panel.getByRole('checkbox',{name:/구매 등록/}).last().check();await panel.getByRole('checkbox',{name:/지원사업/}).last().check();const button=page.getByRole('button',{name:'서명된 Midnight 연결 파일 다운로드',exact:true});assert.equal(await button.isDisabled(),true);await panel.getByRole('checkbox').last().check();
 const [download]=await Promise.all([page.waitForEvent('download'),button.click()]);const file=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(file.body.source.credentialId,'credential-hanbit');assert.equal(file.body.requests.length,2);assert.equal(file.body.contractAddress,'a'.repeat(64));assert.ok(file.signature);assert.equal(await button.isDisabled(),true);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 // UI-only operational persona fixture: no server identity or permissions are forged.
 await page.route('**/api/platform',async route=>{if(route.request().method()!=='GET')return route.continue();const response=await route.fetch(),body=await response.json();return route.fulfill({json:{...body,authMode:'keycloak',actor:'fixture-alice'}});});await page.reload({waitUntil:'networkidle'});await page.getByText('운영 보호 적용: 기업별 권한 · 검토 근거 · 본인 담당자 권한 필수',{exact:true}).waitFor();
 console.log('PASS business UI: actual signed web-source download, consent reset, mobile layout, operational-mode notice');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
