const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),ts=require('typescript'),assert=require('node:assert/strict'),Module=require('node:module');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
fs.mkdirSync('outputs',{recursive:true});process.env.BIZPROOF_DATA_DIR=fs.mkdtempSync(path.resolve('outputs/bizproof-pool-'));
const original=Module._load;Module._load=function(id,...rest){if(id==='cloudflare:workers')return require('../lib/node-bindings.ts');return original.call(this,id,...rest);};
(async()=>{const {env}=require('../lib/node-bindings.ts'),{readState}=require('../lib/store.ts'),pool=require('../lib/demo-pool.ts');
let status=await pool.prepareDemoPool(3);assert.equal(status.available,3);const initial=(await env.DB.prepare('SELECT owner,prepared FROM demo_ready_spaces').all()).results;for(const row of initial){const {state}=await readState(row.owner);assert.equal(state.companies.length,1);assert.equal(state.credentials.length,1);assert.equal(state.preparedDemo.policyIds.length,2);assert.equal(state.presentations.length,0);assert.ok(state.preparedDemo.preparedAt);}
const ids=await Promise.all([pool.claimPreparedDemo('192.0.2.1'),pool.claimPreparedDemo('192.0.2.2')]);assert.equal(new Set(ids).size,2);assert.ok(ids.every(Boolean));assert.ok(ids.every(id=>initial.some(r=>r.owner===id)));
const first=await readState(ids[0]),second=await readState(ids[1]);first.state.credentials[0].status='revoked';await require('../lib/store.ts').saveState(ids[0],first.state,first.version);assert.equal((await readState(ids[1])).state.credentials[0].status,'active');
await Promise.all([pool.claimPreparedDemo('192.0.2.3'),pool.claimPreparedDemo('192.0.2.4'),pool.claimPreparedDemo('192.0.2.5'),pool.claimPreparedDemo('192.0.2.6')]);assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM demo_sessions').first()).n,5);assert.equal(await pool.claimPreparedDemo('192.0.2.7'),null);
const before=await readState(ids[1]);await pool.ensurePreparedWorkspace(ids[1]);await pool.ensurePreparedWorkspace(ids[1]);assert.equal((await readState(ids[1])).version,before.version);
const old='demo-'+crypto.randomUUID();await readState(old);const oldBefore=await readState(old);await pool.ensurePreparedWorkspace(old);const upgraded=await readState(old);assert.ok(upgraded.state.preparedDemo);assert.equal(upgraded.state.companies.length,oldBefore.state.companies.length+1);await pool.ensurePreparedWorkspace(old);assert.equal((await readState(old)).state.companies.length,upgraded.state.companies.length);
const {DatabaseSync}=require('node:sqlite'),reopened=new DatabaseSync(path.join(process.env.BIZPROOF_DATA_DIR,'bizproof.sqlite'));assert.ok(reopened.prepare('SELECT payload FROM workspaces WHERE owner=?').get(ids[1]).payload.includes('preparedDemo'));reopened.close();
console.log('PASS demo pool: pre-saved SQLite credentials, concurrent isolated claims, 5-session cap, persistence and idempotent non-destructive upgrade');
})().catch(e=>{console.error(e);process.exit(1)}).finally(()=>{Module._load=original});
