const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const ctx=await browser.newContext({viewport:{width:1440,height:1040}});const page=await ctx.newPage();await page.goto('http://localhost:5173/signin-with-chatgpt?return_to=/',{waitUntil:'networkidle'});
const base='http://localhost:5173';async function post(action,payload={},status=200){const r=await ctx.request.post(base+'/api/platform',{data:{action,...payload}});const d=await r.json();assert.equal(r.status(),status,JSON.stringify(d));return d;}
await post('switch-role',{role:'admin'});const state=await(await ctx.request.get(base+'/api/platform')).json();const companyId=state.companies[0].id;
const upload=await ctx.request.post(base+'/api/evidence',{multipart:{companyId,file:{name:'demo-evidence.txt',mimeType:'text/plain',buffer:Buffer.from('Fictional supplier evidence')}}});assert.equal(upload.status(),200,await upload.text());let next=await(await ctx.request.get(base+'/api/platform')).json();const evidence=next.evidence.at(-1);const file=await ctx.request.get(base+'/api/evidence?id='+evidence.id);assert.equal(await file.text(),'Fictional supplier evidence');
await post('create-schema',{name:'기업 테스트 스키마',description:'검증 테스트',previousId:state.schemas[0].id});next=await(await ctx.request.get(base+'/api/platform')).json();assert.equal(next.schemas.at(-1).version,2);
await post('create-connection',{companyId,organization:'테스트 기관 '+Date.now(),kind:'buyer'});next=await(await ctx.request.get(base+'/api/platform')).json();const connection=next.connections.at(-1);await post('connection-status',{id:connection.id,status:'accepted'});await post('connection-status',{id:connection.id,status:'declined'},409);
await post('switch-role',{role:'buyer'});assert.equal((await ctx.request.get(base+'/api/evidence?id='+evidence.id)).status(),403);await post('switch-role',{role:'admin'});
await page.goto(base+'/?view=settings',{waitUntil:'networkidle'});await page.getByRole('button',{name:'회로 검증 실행',exact:true}).click();await page.getByText('차단 확인',{exact:true}).first().waitFor({timeout:45000});assert.equal(await page.getByText('차단 확인',{exact:true}).count(),4);await page.screenshot({path:'outputs/bizproof-circuit-lab.png',fullPage:true});
await page.goto(base+'/',{waitUntil:'networkidle'});await page.screenshot({path:'outputs/bizproof-overview.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'outputs/bizproof-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
console.log('PASS: evidence persistence/download/access, schema version, connection transitions, compiled-circuit UI, mobile');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
