const fs=require('node:fs'),ts=require('typescript'),assert=require('node:assert/strict'),Module=require('node:module');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
(async()=>{
 const {baoConfig,baoClient}=require('../lib/openbao.ts');
 const cfg=baoConfig({address:'http://localhost:8200',token:'test-token'});let version=1,offline=false,unsafe=false;const keys=new Map(),calls=[];
 keys.set(1,await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']));
 // Protocol double uses real AES-GCM and AAD to test context and tamper handling.
 async function mock(url,init){calls.push({url,method:init.method});assert.equal(init.headers['X-Vault-Token'],'test-token');assert.equal(init.redirect,'error');if(offline)return Response.json({errors:['secret internal server detail']},{status:503});
 const op=new URL(url).pathname.split('/')[3],body=init.body?JSON.parse(init.body):{};
 if(op==='keys')return Response.json({data:{type:'aes256-gcm96',derived:true,exportable:unsafe,allow_plaintext_backup:false,latest_version:version}});
 const additionalData=Buffer.from(body.context,'base64');
 async function encrypt(bytes){const iv=crypto.getRandomValues(new Uint8Array(12)),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData},keys.get(version),bytes);return 'vault:v'+version+':'+Buffer.concat([Buffer.from(iv),Buffer.from(encrypted)]).toString('base64');}
 async function decrypt(){const [,v,data]=body.ciphertext.split(':'),bytes=Buffer.from(data,'base64');return crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.subarray(0,12),additionalData},keys.get(Number(v.slice(1))),bytes.subarray(12));}
 try{if(op==='encrypt')return Response.json({data:{ciphertext:await encrypt(Buffer.from(body.plaintext,'base64'))}});if(op==='decrypt')return Response.json({data:{plaintext:Buffer.from(await decrypt()).toString('base64')}});if(op==='rewrap')return Response.json({data:{ciphertext:await encrypt(await decrypt())}});}catch{return Response.json({errors:['decryption failed']},{status:400});}throw Error('Unexpected route '+url);}
 const client=baoClient(cfg,mock),plain=JSON.stringify({privateKey:{d:'private-material'},name:'한글 기업'}),encrypted=await client.encrypt('alice',plain);
 assert.ok(!JSON.stringify(encrypted).includes('private-material'));assert.equal(await client.decrypt('alice',encrypted),plain);await assert.rejects(client.decrypt('bob',encrypted));await assert.rejects(client.decrypt('alice',{...encrypted,key:'other-key'}));
 const tampered={...encrypted,ciphertext:encrypted.ciphertext.slice(0,-8)+'AAAAAAA='};await assert.rejects(client.decrypt('alice',tampered));
 version=2;keys.set(2,await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']));const count=calls.length,rewrapped=await client.rewrap('alice',encrypted);assert.ok(rewrapped.ciphertext.startsWith('vault:v2:'));assert.ok(calls.slice(count).every(x=>!x.url.includes('/decrypt/')));assert.equal(await client.decrypt('alice',rewrapped),plain);assert.equal(await client.decrypt('alice',encrypted),plain);
 unsafe=true;await assert.rejects(client.encrypt('alice',plain));unsafe=false;offline=true;await assert.rejects(client.encrypt('alice',plain),e=>!e.message.includes('secret internal'));offline=false;
 for(const address of ['http://remote.invalid','https://user:pass@example.com','https://example.com/other'])assert.throws(()=>baoConfig({address,token:'x'}));assert.throws(()=>baoConfig({address:cfg.address,token:'x',mount:'../sys'}));
 await assert.rejects(baoClient(cfg,async()=>Response.json({data:{ciphertext:'invalid'}})).encrypt('alice',plain));
 await assert.rejects(baoClient(cfg,async()=>new Response('x'.repeat(1_500_001))).metadata());
 const env={BIZPROOF_STORAGE_PROTECTION:'openbao',OPENBAO_ADDR:cfg.address,OPENBAO_TOKEN:cfg.token};const rows=new Map();
 env.DB={prepare(sql){let values;return {bind(...v){values=v;return this;},async first(){const row=rows.get(values[0]);return row?{...row}:null;},async run(){if(sql.startsWith('INSERT')){if(!rows.has(values[0]))rows.set(values[0],{payload:values[1],version:0});return {meta:{changes:1}};}const [payload,owner,v]=values,row=rows.get(owner);if(!row||row.version!==v)return {meta:{changes:0}};rows.set(owner,{payload,version:v+1});return {meta:{changes:1}};}};}};
 const load=Module._load;Module._load=function(id,...rest){if(id==='cloudflare:workers')return {env};return load.call(this,id,...rest);};const oldFetch=global.fetch;global.fetch=mock;
 try{const store=require('../lib/store.ts'),protection=require('../lib/storage-protection.ts');const first=await store.readState('owner');assert.ok(protection.storageEnvelope(rows.get('owner').payload));assert.ok(first.state.issuers[0].privateKey.d);await store.saveState('owner',first.state,first.version);await assert.rejects(store.saveState('owner',first.state,first.version),store.ConflictError);
 const before=rows.get('owner').payload;offline=true;await assert.rejects(store.saveState('owner',first.state,1));assert.equal(rows.get('owner').payload,before);await assert.rejects(store.readState('owner'));offline=false;
 rows.set('legacy',{payload:JSON.stringify(first.state),version:0});const legacy=await store.readState('legacy');await store.saveState('legacy',legacy.state,0);assert.ok(protection.storageEnvelope(rows.get('legacy').payload));
 const evidenceProtection=require('../lib/evidence-protection.ts');const fileBytes=new Uint8Array(300000).fill(81).buffer,fileHash=await evidenceProtection.evidenceHash(fileBytes);const protectedFile=await evidenceProtection.protectEvidence('owner','file-a',fileBytes);assert.equal(JSON.parse(protectedFile.body).chunks.length,2);const fileObject={customMetadata:{protection:'openbao-v1'},arrayBuffer:async()=>new TextEncoder().encode(protectedFile.body).buffer};assert.equal(await evidenceProtection.evidenceHash(await evidenceProtection.readEvidence('owner','file-a',fileObject,fileHash)),fileHash);await assert.rejects(evidenceProtection.readEvidence('other-owner','file-a',fileObject,fileHash));await assert.rejects(evidenceProtection.readEvidence('owner','other-file',fileObject,fileHash));offline=true;await assert.rejects(evidenceProtection.protectEvidence('owner','file-a',fileBytes));offline=false;
 env.BIZPROOF_STORAGE_PROTECTION='demo';await assert.rejects(evidenceProtection.readEvidence('owner','file-a',fileObject,fileHash));assert.equal((await evidenceProtection.protectEvidence('owner','plain-file',fileBytes)).encrypted,false);await assert.rejects(store.readState('owner'));await store.saveState('demo',first.state,0).catch(()=>{});env.BIZPROOF_STORAGE_PROTECTION='typo';await assert.rejects(protection.encodeStorage('alice',plain));
 }finally{Module._load=load;global.fetch=oldFetch;}
 console.log('PASS OpenBao: encryption, context isolation, tampering, rotation/rewrap, key policy, bounded responses, D1 migration/CAS, fail-closed outage and disabled-mode protection.');
})().catch(e=>{console.error(e);process.exitCode=1;});
