const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.SMOKE_BASE||'http://127.0.0.1:3120',out=path.resolve(process.env.SMOKE_OUTPUT||'outputs/proof-jobs-ui');fs.mkdirSync(out,{recursive:true});
const localPreview=base.startsWith('http://127.0.0.1:')&&process.env.BIZPROOF_ANALYTICS_LOCAL_PREVIEW==='true';
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chromium',args:[]}),ctx=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await ctx.addCookies([{name:'bp-analytics-optout',value:'1',url:base}]);await ctx.addInitScript(()=>localStorage.setItem('bp-analytics-notice','1'));await page.goto(base+'/issuance');await page.getByRole('button',{name:'내 체험 공간 시작하기'}).click();await page.getByRole('button',{name:'동의하고 발급 신청',exact:true}).waitFor();
const post=async(route,body)=>{const r=await ctx.request.post(base+route,{headers:{Origin:base},data:body});const b=await r.json();assert.ok(r.ok(),JSON.stringify(b));return b;};
const catalog=await (await ctx.request.get(base+'/api/issuance')).json();let request=await post('/api/issuance',{action:'apply',key:crypto.randomUUID(),documentHash:catalog.catalog.documentHash,consent:true});await post('/api/issuance',{action:'decide',id:request.id,key:crypto.randomUUID(),revision:request.revision,decision:'approve',reason:''});const receipt=await post('/api/issuance',{action:'receive',id:request.id,key:crypto.randomUUID()});const items=[];
for(const policyId of ['issuer-demo-buyer','issuer-demo-grant']){const p=await post('/api/platform',{action:'prepare-application',companyId:receipt.companyId,credentialId:receipt.credentialId,policyId});items.push({policyId,credentialId:receipt.credentialId,previewHash:p.previewHash,key:crypto.randomUUID()});}await post('/api/platform',{action:'submit-applications',companyId:receipt.companyId,items,consent:true});
await page.goto(base+'/?view=apply&company=issuer-demo-company&flow=issued');const panel=page.locator('#issued-chain-process');await panel.waitFor();await panel.getByRole('list',{name:'신청부터 체인 검증까지'}).waitFor();const button=panel.getByRole('button',{name:'Midnight 시연 실행 요청',exact:true});await button.waitFor();assert.equal(await button.isDisabled(),true);await panel.getByRole('checkbox').check();await button.click();await panel.getByRole('heading',{name:'진행자 승인 대기',exact:true}).waitFor();let data=await (await ctx.request.get(base+'/api/proof-jobs')).json(),job=data.jobs[0];assert.equal(job.credentialId,receipt.credentialId);assert.equal(job.requests.length,2);
assert.equal((await ctx.request.post(base+'/api/admin/proof-jobs',{headers:{Origin:base},data:{action:'approve',id:job.id,revision:job.revision}})).status(),403,'ordinary visitor cannot approve');
assert.equal((await ctx.request.post(base+'/api/proof-worker',{data:{action:'claim',id:job.id}})).status(),401);
assert.equal((await ctx.request.post(base+'/api/identity/sessions',{headers:{Origin:base},data:{action:'start',companyId:receipt.companyId,documentHash:'a'.repeat(64),consent:true}})).status(),403,'public identity cannot become real');
await page.screenshot({path:path.join(out,'request-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'request-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1100});
if(process.env.ADMIN_SESSION_FILE){const token=fs.readFileSync(process.env.ADMIN_SESSION_FILE,'utf8').trim();await ctx.addCookies([{name:'bizproof-admin',value:token,url:base}]);}
else if(localPreview)await ctx.addCookies([{name:'bizproof-persona',value:'admin',url:base}]);
if(process.env.ADMIN_ACCESS_FILE){await page.goto(base+'/admin/login');const password=fs.readFileSync(process.env.ADMIN_ACCESS_FILE,'utf8').split(/\r?\n/).find(s=>s.startsWith('Password: ')).slice(10);await page.getByLabel('관리자 아이디').fill('admin');await page.getByLabel('관리자 비밀번호').fill(password);const [login]=await Promise.all([page.waitForResponse(r=>r.url()===base+'/api/demo-admin'&&r.request().method()==='POST'),page.getByRole('button',{name:'관리자 로그인',exact:true}).click()]);assert.equal(login.status(),303,'provided administrator credentials must be accepted; never reset or bypass login in this test');await page.waitForURL(base+'/admin');}
if(process.env.ADMIN_SESSION_FILE||process.env.ADMIN_ACCESS_FILE||localPreview){await page.goto(base+'/admin/proof-jobs');const ownJob=page.locator('article.proof-job').filter({hasText:job.id});await ownJob.getByRole('button',{name:'이 두 신청의 체인 실행 승인',exact:true}).click();await ownJob.getByRole('heading',{name:'실행기 대기',exact:true}).waitFor();await page.screenshot({path:path.join(out,'approved.png'),fullPage:true});}
fs.writeFileSync(path.join(out,'job.json'),JSON.stringify({id:job.id,credentialId:receipt.credentialId,requests:job.requests,sourceDigest:job.sourceDigest,origin:base},null,2));
if(process.env.KEEP_PROOF_JOB==='true')await ctx.storageState({path:path.join(out,'private-browser-state.json')});
else {await post('/api/proof-jobs',{action:'cancel',id:job.id});await page.goto(base+'/chain-jobs');await page.getByRole('heading',{name:'요청 취소',exact:true}).waitFor();}
assert.deepEqual(errors,[]);console.log('PASS proof jobs UI: real separate issuance and two applications, explicit consent, visitor/admin/worker separation, public identity guard, desktop/mobile, cancel; administrator approval '+(localPreview||process.env.ADMIN_SESSION_FILE||process.env.ADMIN_ACCESS_FILE?'checked':'not configured')+'. Job '+job.id);
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{if(process.env.KEEP_PROOF_JOB!=='true')await ctx.request.get(base+'/signout-with-chatgpt').catch(()=>{});await browser.close();}})().catch(e=>{console.error(String(e.message??e).split('Call log:')[0]);process.exit(1);});
