const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const base=process.env.SMOKE_BASE||'http://localhost:3102';const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chromium',args:[]});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let posts=0;page.on('request',r=>{if(r.url().endsWith('/api/platform')&&r.postData()?.includes('submit-applications'))posts++;});
try{fs.mkdirSync('outputs',{recursive:true});const entryResponse=await page.goto(base+'/',{waitUntil:'networkidle'});const enteredAt=Date.parse(entryResponse.headers()['date'])+999;const notice=page.getByLabel('방문 분석 안내',{exact:true});if(await notice.isVisible())await notice.getByRole('button',{name:'확인',exact:true}).click();await page.getByRole('button',{name:'내 체험 공간 시작하기'}).click();await page.waitForURL('**/?view=apply');await page.getByRole('button',{name:'모두 선택',exact:true}).waitFor();
async function state(){return page.evaluate(async()=>{const r=await fetch('/api/platform');if(!r.ok)throw Error('State unavailable');return r.json()});}
const before=await state();assert.equal(before.role,'company');assert.equal(before.companies.length,1);assert.equal(before.credentials.length,1);assert.ok(Date.parse(before.preparedDemo.preparedAt)<enteredAt,'Data must be persisted before entering the demo');assert.equal(before.presentations.length,0);assert.equal(await page.getByRole('combobox',{name:'업무 역할'}).count(),0);assert.equal(await page.locator('input[type="text"],input[type="email"],input[type="file"]').count(),0);assert.equal(await page.getByRole('button',{name:'새 시연 준비',exact:true}).count(),0);const ids={company:before.companies[0].id,credential:before.credentials[0].id};
await page.getByRole('button',{name:'모두 선택',exact:true}).click();const submit=page.getByRole('button',{name:'선택한 2곳에 제출',exact:true});await submit.waitFor();assert.equal(await submit.isDisabled(),true);await page.screenshot({path:'outputs/simple-apply-desktop.png',fullPage:true});await page.getByRole('checkbox').check();await submit.click();await page.getByRole('dialog').getByText('처리·저장 완료',{exact:true}).waitFor();await page.getByRole('button',{name:'관제 창 닫기'}).click();await page.getByRole('region',{name:'신청 결과'}).getByRole('heading',{name:'신청 결과',exact:true}).waitFor();let after=await state();assert.equal(after.presentations.length,2);assert.ok(after.presentations.every(p=>p.verifiedAt&&p.eligible));assert.equal(new Set(after.presentations.map(p=>p.credentialId)).size,1);assert.equal(after.presentations[0].credentialId,ids.credential);assert.equal(new Set(after.presentations.map(p=>p.nonce)).size,2);assert.equal(posts,1);
await page.reload({waitUntil:'networkidle'});after=await state();assert.equal(after.companies[0].id,ids.company);assert.equal(after.presentations.length,2);assert.equal(after.credentials[0].id,ids.credential);await page.screenshot({path:'outputs/simple-results-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'outputs/simple-results-mobile.png',fullPage:true});
const guards=await page.evaluate(async()=>({pool:(await fetch('/api/admin/demo-data')).status,admin:(await fetch('/api/admin/analytics')).status}));assert.deepEqual(guards,{pool:403,admin:403});assert.deepEqual(errors,[]);await page.goto(base+'/signout-with-chatgpt');console.log(JSON.stringify({pass:true,checks:['data stored before entry','company role','zero mandatory text fields','two recipients in one submit','same credential distinct nonces','automatic verification','reload persistence','mobile','admin isolation'],company:ids.company,credential:ids.credential}));
}finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exit(1)});
