import {requireBusinessAccess,operational} from '@/lib/business-access';
import {requireReviewedCredential} from '@/lib/business-assurance';
import {FgaError} from '@/lib/openfga';
import {familyMatches} from '@/lib/credential-family';
import {getChatGPTUser,getActiveRole} from '@/app/chatgpt-auth';
import {z} from 'zod';
import {readState,saveState,ConflictError} from '@/lib/store';
import {credentialPayload,statusOf,evaluate,claimsInput,type Role} from '@/lib/domain';
import {digest,verify} from '@/lib/signatures';
import {foundingCutoff} from '@/lib/compact-policy';
export const dynamic='force-dynamic';
export async function GET(req:Request){
 if(!await getChatGPTUser())return Response.json({error:'로그인이 필요합니다.'},{status:401});
 if(!['localhost','127.0.0.1'].includes(new URL(req.url).hostname))return Response.json({error:'로컬 서비스 진단은 로컬 개발 환경에서만 가능합니다.'},{status:503});
 const probes=[{id:'bridge',name:'Compact 실행 브리지',url:'http://127.0.0.1:4011/health'}, {id:'proof',name:'Proof server · 목표 8.1.0',url:'http://127.0.0.1:6300/version'}, {id:'node',name:'Midnight node · 목표 1.0.0',url:'http://127.0.0.1:9944/health'}, {id:'indexer',name:'Indexer · 목표 4.3.3',url:'http://127.0.0.1:8088/api/v4/graphql'}];
 const checks=await Promise.all(probes.map(async probe=>{try{const response=await fetch(probe.url,{signal:AbortSignal.timeout(2500),redirect:'manual',...(probe.id==='indexer'?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:'{ __typename }'})}:{})});let reachable=response.ok;if(probe.id==='indexer'&&reachable){const body=await response.json() as {data?:{__typename?:unknown};errors?:unknown};reachable=typeof body.data?.__typename==='string'&&!body.errors;}else if(probe.id==='bridge'&&reachable){const body=await response.json() as {mode?:unknown;proofGenerated?:unknown};reachable=body.mode==='compact-local'&&body.proofGenerated===false;}else{await response.body?.cancel();}return {id:probe.id,name:probe.name,reachable,detail:reachable?'로컬 API 응답 확인. 버전 호환성·체인 동기화·거래 검증은 별도입니다.':'예상 서비스 응답을 확인하지 못했습니다.'};}catch{return {id:probe.id,name:probe.name,reachable:false,detail:'서비스 미실행 또는 연결 실패'};}}));
 return Response.json({checkedAt:new Date().toISOString(),checks,proofGenerated:false,contractDeployed:false},{headers:{'Cache-Control':'no-store'}});
}
const resultInput=z.object({mode:z.literal('compact-local'),networkConnected:z.literal(false),proofGenerated:z.literal(false),requestId:z.string(),credentialId:z.string(),policyHash:z.string(),eligible:z.boolean(),replayBlocked:z.literal(true),compiler:z.literal('0.31.1'),runtime:z.string(),at:z.string(),notice:z.string()});
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'로그인이 필요합니다.'},{status:401});const url=new URL(req.url);if(!['localhost','127.0.0.1'].includes(url.hostname))return Response.json({error:'로컬 회로 실행은 로컬 개발 환경에서만 사용할 수 있습니다.'},{status:503});const origin=req.headers.get('origin');if(origin&&origin!==url.origin)return Response.json({error:'허용되지 않는 출처입니다.'},{status:403});try{const text=await req.text();if(text.length>2000)return Response.json({error:'요청이 너무 큽니다.'},{status:413});const body=z.record(z.unknown()).parse(text?JSON.parse(text):{});if(!Object.keys(body).length){const r=await fetch('http://127.0.0.1:4011/demo',{method:'POST',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('bridge');return Response.json(await r.json(),{headers:{'Cache-Control':'no-store'}});}
const ids=z.object({requestId:z.string(),credentialId:z.string()}).strict().parse(body);const role=((await getActiveRole())??'') as Role;if(!['admin','issuer','company'].includes(role))return Response.json({error:'기업 또는 발급기관 역할에서 실행하세요.'},{status:403});const {state:s,version}=await readState(user.storageOwner);const request=s.requests.find(r=>r.id===ids.requestId),c=s.credentials.find(c=>c.id===ids.credentialId);if(!request||!c)return Response.json({error:'요청 또는 자격을 찾을 수 없습니다.'},{status:404});await requireBusinessAccess({actor:user.userId,owner:user.storageOwner,authMode:user.authMode,role},c.companyId);if(operational(user))requireReviewedCredential(s,c);const issuer=s.issuers.find(i=>i.id===c.issuerId);const now=new Date();if(request.companyId!==c.companyId||request.status!=='pending'||Date.parse(request.expiresAt)<=now.getTime()||statusOf(c)!=='active'||issuer?.status!=='active'||!request.policy.issuerIds.includes(c.issuerId))return Response.json({error:'대기 중인 요청과 같은 기업의 유효한 자격·신뢰 발급기관이 필요합니다.'},{status:422});const key=c.keyId===issuer.keyId?issuer.publicKey:issuer.previousKeys.find(k=>k.keyId===c.keyId)?.publicKey;if(!key||!await verify(key,credentialPayload(c),c.signature)||await digest(request.policy)!==request.policyHash)return Response.json({error:'원본 자격 서명 또는 정책 스냅샷 검증 실패'},{status:422});if(!await familyMatches(s,c))return Response.json({error:"스키마 버전 연결 검증 실패"},{status:422});claimsInput.parse(c.claims);const policy=request.policy;let minFoundedDay:number;try{minFoundedDay=foundingCutoff(policy,now);}catch(e){return Response.json({error:e instanceof Error?e.message:'업력 조건 변환 실패'},{status:422});}
const input={requestId:request.id,credentialId:c.id,audience:policy.audience,nonce:request.nonce,policyHash:request.policyHash,deadline:Math.floor(Date.parse(request.expiresAt)/1000),claims:{revenue:c.claims.revenue,foundedDay:Math.floor(Date.parse(c.claims.foundedOn)/864e5),region:policy.region&&c.claims.region!==policy.region?2:1,certified:c.claims.certified,expiresAt:Math.floor(Date.parse(c.expiresAt)/1000)},policy:{minRevenue:policy.minRevenue??0,maxRevenue:policy.maxRevenue??1e12,minFoundedDay,region:policy.region?1:0,requireCertification:policy.requireCertification}};
const r=await fetch('http://127.0.0.1:4011/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(30000)});if(r.status===422)return Response.json({error:'Compact 회로가 입력 또는 서명 검증을 거절했습니다.'},{status:422});if(!r.ok)throw Error('bridge');const report=resultInput.parse(await r.json());if(report.requestId!==request.id||report.credentialId!==c.id||report.policyHash!==request.policyHash||report.eligible!==evaluate(c.claims,policy,now).eligible)return Response.json({error:'회로와 업무 정책의 결과가 일치하지 않아 결과를 저장하지 않았습니다.'},{status:422});
// Store a bounded result record only: never raw claims, witness secrets or signatures.
const record={id:'compact-'+crypto.randomUUID(),...report,sourceSignatureVerified:true,policyParity:true};(s.compactRuns??=[]).push(record);s.compactRuns=s.compactRuns.slice(-100);s.audit.push({id:'audit-'+crypto.randomUUID(),at:new Date().toISOString(),actor:user.userId,role,action:'compact-request-evaluated',target:request.id,detail:'저장된 자격·정책의 로컬 회로 실행 · '+(report.eligible?'조건 충족':'미충족')});await saveState(user.storageOwner,s,version);return Response.json(record,{headers:{'Cache-Control':'no-store'}});
}catch(e){if(e instanceof FgaError)return Response.json({error:e.message},{status:e.status});if(e instanceof ConflictError)return Response.json({error:'검증 중 업무 데이터가 변경되었습니다. 다시 실행하세요.'},{status:409});if(e instanceof z.ZodError||e instanceof SyntaxError)return Response.json({error:'회로 요청 또는 응답 형식이 올바르지 않습니다.'},{status:400});return Response.json({error:'Compact 실행 서비스에 연결하지 못했습니다. contracts 폴더에서 node bridge.mjs를 실행하세요.'},{status:503});}}

