import {scanEvidence} from '@/lib/malware-runtime';
import {ScanError} from '@/lib/malware-scan';
import {requireEvidenceAccess} from '@/lib/openfga-runtime';
import {FgaError} from '@/lib/openfga';
import {protectEvidence,readEvidence} from '@/lib/evidence-protection';
import { env } from 'cloudflare:workers';
import {getChatGPTUser,getActiveRole} from '@/app/chatgpt-auth';
import { readState,saveState } from '@/lib/store';
export const dynamic='force-dynamic';
async function authorize(){const user=await getChatGPTUser();if(!user)return null;const role=(await getActiveRole())??'';if(!['admin','issuer','company'].includes(role))return null;return {user,role:role as 'admin'|'issuer'|'company'};}
export async function POST(req:Request){const auth=await authorize();if(!auth)return Response.json({error:'기업 또는 발급기관 역할로 로그인하세요.'},{status:403});const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return Response.json({error:'허용되지 않는 출처입니다.'},{status:403});if(Number(req.headers.get('content-length')??0)>2200000)return Response.json({error:'파일은 2MB 이하여야 합니다.'},{status:413});let storedKey:string|undefined;try{if(!env.BUCKET)return Response.json({error:'문서 저장소를 연결하지 못했습니다.'},{status:503});const fd=await req.formData();const file=fd.get('file');const companyId=String(fd.get('companyId')??'');if(!(file instanceof File)||file.size>2*1024*1024||file.size===0)return Response.json({error:'비어 있지 않은 2MB 이하 파일을 선택하세요.'},{status:400});const bytes=await file.arrayBuffer();const prefix=new TextDecoder().decode(bytes.slice(0,5));const pdf=prefix==='%PDF-';if(!pdf&&!file.name.toLowerCase().endsWith('.txt'))return Response.json({error:'PDF 또는 TXT 파일만 지원합니다.'},{status:400});const {state,version}=await readState(auth.user.storageOwner);if(!state.companies.some(c=>c.id===companyId))return Response.json({error:'기업을 찾을 수 없습니다.'},{status:404});await requireEvidenceAccess(auth.user,companyId,'write');const id=crypto.randomUUID();const key=`evidence/${auth.user.storageOwner}/${id}`;const scan=await scanEvidence(bytes);const protectedFile=await protectEvidence(auth.user.storageOwner,key,bytes);await env.BUCKET.put(key,protectedFile.body,{httpMetadata:{contentType:protectedFile.encrypted?'application/json':pdf?'application/pdf':'text/plain'},customMetadata:protectedFile.encrypted?{protection:'openbao-v1'}:{}});storedKey=key;const sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');const f={scan,sha256,id,companyId,key,name:file.name.replace(/[\r\n"\\/]/g,'_').slice(0,150),mime:pdf?'application/pdf':'text/plain',size:file.size,createdAt:new Date().toISOString()};state.evidence.push(f);state.audit.push({id:crypto.randomUUID(),at:f.createdAt,actor:auth.user.userId,role:auth.role,action:'evidence.upload',target:id,detail:'비공개 증빙 문서 첨부 · '+(scan.status==='clean'?'ClamAV 검사 통과':'보안 검사 미실행')});await saveState(auth.user.storageOwner,state,version);return Response.json({id});}catch(e){if(storedKey)await env.BUCKET?.delete(storedKey);if(e instanceof FgaError||e instanceof ScanError)return Response.json({error:e.message},{status:e.status});console.error(e);return Response.json({error:'문서 저장에 실패했습니다. 다시 시도하세요.'},{status:500});}}
export async function GET(req:Request){const auth=await authorize();if(!auth)return Response.json({error:'이 문서에 접근할 수 없습니다.'},{status:403});try{const {state}=await readState(auth.user.storageOwner);const id=new URL(req.url).searchParams.get('id');const item=state.evidence.find(f=>f.id===id);if(!item)return Response.json({error:'문서를 찾을 수 없습니다.'},{status:404});await requireEvidenceAccess(auth.user,item.companyId,'read');const obj=await env.BUCKET?.get(item.key);if(!obj)return Response.json({error:'파일을 불러올 수 없습니다.'},{status:404});const bytes=await readEvidence(auth.user.storageOwner,item.key,obj,item.sha256);await scanEvidence(bytes);return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(item.name)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}catch(e){if(e instanceof FgaError||e instanceof ScanError)return Response.json({error:e.message},{status:e.status});return Response.json({error:'문서 저장소를 불러올 수 없습니다.'},{status:503});}}

