"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {type ViewState,statusOf} from '@/lib/domain';
import CompactRequest from './compact-request';

type Props={data:ViewState;busy:boolean;act:(action:string,payload:Record<string,unknown>)=>Promise<unknown>;refresh:()=>Promise<void>;openCredential:(id:string)=>void};
const names={buyer:'구매사 등록',grant:'지원사업 신청',negative:'미충족 비교'} as const;
const statuses:Record<string,string>={pending:'제출 전',submitted:'기관 확인 전',verified:'충족 확인',rejected:'미충족 확인',cancelled:'요청 취소'};
export default function DemoJourney({data,busy,act,refresh,openCredential}:Props){
 const journey=data.demoJourneys?.at(-1),c=data.credentials.find(c=>c.id===journey?.credentialId);
 const [consents,setConsents]=useState<Record<string,boolean>>({}),[confirmRevoke,setConfirmRevoke]=useState(false);
 const run=(action:string,payload:Record<string,unknown>)=>void act(action,payload).catch(()=>{});
 if(data.role!=='admin')return <section className="panel"><h2>관리자 역할에서 전체 시연을 진행하세요.</h2><p>이 화면은 개인 샌드박스의 발급·제출·기관 확인을 한곳에서 체험합니다. 각 기관 역할의 검증 결과는 검증 요청 화면에서 확인할 수 있습니다.</p></section>;
 return <div className="journey-workspace"><section className="panel journey-intro"><div><span className="eyebrow">ONE CREDENTIAL · TWO OPPORTUNITIES</span><h2>한 번 발급하고 두 곳에 재사용</h2><p>구매사와 지원기관은 각자의 조건 충족 결과를 받습니다. 실제 등록·신청 접수는 수행하지 않습니다.</p></div><Button disabled={busy} onClick={()=>{setConfirmRevoke(false);setConsents({});run('create-demo-journey',{});}}>새 시연 준비</Button></section>
 {!journey||!c?<section className="panel"><h2>가상 기업 자격 1건으로 시작합니다.</h2><p>새 시연을 준비하면 전용 기업·발급기관·정책을 생성합니다. 기존 업무 기록은 유지됩니다.</p></section>:<>
 <section className="panel"><div className="section-heading"><div><h2>1. 모든 요청에 같은 기업 자격 사용</h2><p>가상 매출 3억 원 · 서울 · 생성 시점 약 24개월 업력</p></div><span className={'status '+(statusOf(c)==='active'?'good':'bad')}>{statusOf(c)==='active'?'재사용 가능':'사용 불가'}</span></div><p className="journey-id" data-testid="journey-credential">{c.id}</p><Button variant="outline" onClick={()=>openCredential(c.id)}>자격·발급 근거 확인</Button><p className="small-text muted">합성 데이터 · Ed25519 서명 기반 업무 데모. 서버는 원본 속성을 처리합니다.</p></section>
 <div className="journey-results">{(Object.keys(names) as (keyof typeof names)[]).map(key=>{const r=data.requests.find(r=>r.id===journey.requestIds[key]);if(!r)return null;const p=data.presentations.find(p=>p.requestId===r.id);return <section className="panel" key={r.id} data-testid={'journey-'+key}><span className="eyebrow">{key==='negative'?'FAILURE SCENARIO':'REUSE SCENARIO'}</span><h2>{names[key]}</h2><p>{key==='buyer'?'매출 2억 원 이상':key==='grant'?'매출 5억 원 이하 · 36개월 이내 · 서울':'매출 5억 원 이상'}</p><span className={'status '+(r.status==='verified'?'good':r.status==='rejected'?'bad':'warn')}>{statuses[r.status]}</span><dl className="detail-list"><dt>재사용 자격</dt><dd className="journey-id">{c.id}</dd><dt>개별 요청</dt><dd className="journey-id">{r.id}</dd></dl>{p&&<div aria-live="polite">{p.checks.map(check=><div className="check-row" key={check.label}><span>{check.label}</span><strong>{check.pass?'충족':'미충족'}</strong></div>)}<p className="small-text">{p.verifiedAt?'서명·요청 연결·유효성 확인 완료':'서명된 결과 생성 · 기관 확인 필요'}</p></div>}
 {r.status==='pending'&&statusOf(c)==='active'&&<><label className="consent"><input type="checkbox" checked={!!consents[r.id]} onChange={e=>setConsents({...consents,[r.id]:e.target.checked})}/><span>{r.policy.audience}에 기업 식별 정보와 조건별 충족 결과를 공유하는 데 동의합니다.</span></label><Button disabled={busy||!consents[r.id]} onClick={()=>run('present',{requestId:r.id,credentialId:c.id,consent:consents[r.id]})}>같은 자격으로 제출</Button></>}
 {r.status==='submitted'&&<Button disabled={busy||statusOf(c)!=='active'} onClick={()=>run('verify-presentation',{id:p?.id})}>기관에서 결과 확인</Button>}
 </section>;})}</div>
 <section className="panel"><h2>2. 기관이 받는 정보</h2><div className="engine-grid"><div><b>공유됨</b><p>기업·자격 식별값, 수신 기관, 정책·요청 식별값, 조건별 충족 여부, 유효기간, 서명</p></div><div><b>공유하지 않음</b><p>정확한 매출·설립일·소재지 원본 속성, 증빙 파일, 발급 근거 기록, 발급 비밀키</p></div></div><p>기관은 정책 자체를 알고 있으므로 조건 충족 결과로 일부 속성 범위를 추론할 수 있습니다.</p></section>
 <section className="panel"><h2>선택: Midnight 로컬 회로 대조</h2><p>아직 제출하지 않은 별도 요청으로 회로 판정을 대조합니다. 임시 실험용 서명을 사용하는 로컬 실행이며 실제 proof·체인 거래를 생성하지 않습니다. 자격 취소 전에 실행하세요.</p><CompactRequest key={journey.id} requestId={journey.requestIds.revoked} credentialId={c.id} disabled={statusOf(c)!=='active'} history={data.compactRuns??[]} refresh={refresh}/></section>
 <section className="panel"><h2>3. 자격 취소 후 재사용 차단</h2><p>위 세 결과를 확인한 다음 시연용 자격을 취소합니다. 이미 확인된 결과는 당시 기록으로 남으며, 이후 제출에는 사용할 수 없습니다.</p>{c.status!=='revoked'?<><label className="consent"><input type="checkbox" checked={confirmRevoke} onChange={e=>setConfirmRevoke(e.target.checked)}/><span>이 시연 자격을 취소하고 재사용 차단을 확인합니다.</span></label><Button variant="destructive" disabled={busy||!confirmRevoke||!Object.keys(names).every(key=>['verified','rejected'].includes(data.requests.find(r=>r.id===journey.requestIds[key as keyof typeof names])?.status??''))} onClick={()=>run('revoke-credential',{id:c.id,reason:'재사용 시연: 취소 후 제출 차단 확인'})}>시연 자격 취소</Button></>:<><Button disabled={busy} onClick={()=>run('check-demo-revocation',{id:journey.id})}>현재 자격 상태 검사</Button>{journey.revocationCheck&&<p role="status">{journey.revocationCheck.blocked?'취소된 자격: 제출 전 유효성 검사에서 차단됨':'차단되지 않음 — 점검 필요'} · {new Date(journey.revocationCheck.at).toLocaleString('ko-KR')}</p>}</>}</section>
 </> }</div>;
}
