"use client";
import {useEffect,useState} from 'react';
import {ExternalLink,ArrowDown,Search} from 'lucide-react';
import {z} from 'zod';
const directorySchema=z.object({source:z.literal('https://www.gleif.org/en/organizational-identity/get-an-lei-vlei/get-a-vlei'),reviewedOn:z.string(),live:z.literal(false),total:z.number(),notice:z.string(),items:z.array(z.object({name:z.string(),lei:z.string().regex(/^[A-Z0-9]{20}$/),website:z.string().url().refine(s=>s.startsWith('https://')),qualifiedOn:z.string()}))});
export default function GetVlei({jump,go}:{jump:(id:string)=>void;go:(id:string)=>void}){
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('newest'),[attempt,setAttempt]=useState(0),[directory,setDirectory]=useState<z.infer<typeof directorySchema>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 useEffect(()=>{const controller=new AbortController();fetch('/api/qvi?q='+encodeURIComponent(search)+'&sort='+sort,{signal:controller.signal,cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(z.object({error:z.string()}).parse(body).error);return directorySchema.parse(body);}).then(setDirectory).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'목록을 불러오지 못했습니다.');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[search,sort,attempt]);
 function reload(){setBusy(true);setError('');setDirectory(null);setAttempt(x=>x+1);}
 return <><p className="gleif-kicker">GET AN LEI / vLEI</p><h2>Get a vLEI</h2><p>LEI를 준비한 기업은 공인 vLEI 발급기관을 선택해 신청할 수 있습니다. 각 기관의 웹사이트에서 신청 절차와 발급·유지·취소 비용을 확인하세요.</p><div className="qvi-actions"><button onClick={()=>jump('identity-lei')}>1. 기업 LEI 조회</button><a href="#qvi-list" onClick={e=>{e.preventDefault();document.getElementById('qvi-list')?.scrollIntoView({block:'start'});}}>2. 발급기관 찾기 <ArrowDown size={14}/></a></div><div className="qvi-steps"><h3>Step One · 법인 vLEI 자격</h3><ol><li>기업<small>LEI · 신청 담당자 준비</small></li><li>공인 발급기관<small>기업 및 신청 권한 확인</small></li><li>법인 자격<small>Legal Entity vLEI</small></li></ol><h3>Step Two · 공식 조직 역할 자격</h3><ol><li>법인과 담당자<small>담당자 신원 · 공식 역할 제시</small></li><li>공인 발급기관<small>신원 및 역할 확인</small></li><li>공식 역할 자격<small>OOR vLEI</small></li></ol><p>신청 절차를 설명한 도식입니다. BizProof가 공인 자격을 발급하거나 신청을 대신 제출하지 않습니다.</p></div><div id="qvi-list"><h3>List of vLEI Issuers</h3><form className="qvi-search" onSubmit={e=>{e.preventDefault();setSearch(query);reload();}}><label>발급기관 검색<input value={query} maxLength={100} placeholder="기관명 또는 LEI" onChange={e=>setQuery(e.target.value)}/></label><label>정렬<select aria-label="발급기관 정렬" value={sort} onChange={e=>{setSort(e.target.value);reload();}}><option value="newest">자격 획득일 최신순</option><option value="name">기관명순</option></select></label><button type="submit"><Search size={14}/>검색</button></form>{busy?<p role="status">발급기관 목록을 불러오는 중입니다.</p>:error?<div role="alert"><p>{error}</p><button onClick={reload}>다시 시도</button></div>:directory&&<><p className="qvi-meta">{directory.items.length} / {directory.total}개 · 공식 페이지 확인일 {directory.reviewedOn}</p><p className="gleif-boundary">{directory.notice}</p>{directory.items.map(i=><article className="qvi-card" key={i.lei}><h4>{i.name}</h4><dl><dt>Website</dt><dd><a href={i.website} target="_blank" rel="noreferrer">{i.website}<ExternalLink size={12}/></a></dd><dt>LEI</dt><dd><a href={'https://search.gleif.org/#/record/'+i.lei} target="_blank" rel="noreferrer">{i.lei}<ExternalLink size={12}/></a></dd><dt>Qualification Date</dt><dd>{i.qualifiedOn}</dd></dl><a className="qvi-apply" href={i.website} target="_blank" rel="noreferrer">기관 사이트에서 신청 안내 확인 <ExternalLink size={14}/></a></article>)}{!directory.items.length&&<p role="status">검색 결과가 없습니다. 기관명 또는 LEI를 변경하세요.</p>}<a className="gleif-resource" href={directory.source} target="_blank" rel="noreferrer">GLEIF 공식 목록에서 최신 상태 확인<ExternalLink size={16}/></a></>}</div><div className="qvi-demo"><h4>BizProof 데모 발급</h4><p>프로젝트 내부 기업 자격 발급은 별도의 업무입니다.</p><button onClick={()=>go('studio')}>데모 발급 작업실 열기</button></div></>;
}
