'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,FileCheck2,RefreshCw,ShieldCheck,Building2,Activity,LockKeyhole} from 'lucide-react';
import BizProofLogo from './bizproof-logo';
import EntryForm from './welcome-start';
import Link from 'next/link';
import ProofJobsPanel from './proof-jobs-panel';
import './issuance.css';

type Issuance={id:string;companyId:string;status:string;revision:number;createdAt:string;reason:string;credentialId?:string;events:{seq:number;type:string;at:string;detail:string}[]};
type Receipt={credentialId:string;requestId:string;digest:string;receivedAt:string;status:string;statusCheckedAt?:string};
type Data={autoRun?:boolean;catalog:{documentHash:string;catalog:{name:string;claims:{revenue:number;foundedOn:string;region:string}}};requests:Issuance[];receipts:Receipt[]};
const labels:Record<string,string>={submitted:'기관 검토 대기',needs_changes:'보완 필요',issued:'기관 발급 완료',rejected:'반려',cancelled:'철회',active:'사용 가능',revoked:'발급 취소',unknown:'기관 상태 미확인',expired:'유효기간 만료',review_approved:'검토 승인'};
export default function IssuanceExperience({operator=false}:{operator?:boolean}){
 const [data,setData]=useState<Data>(),[error,setError]=useState(''),[unauthorized,setUnauthorized]=useState(false),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[reason,setReason]=useState(''),[notice,setNotice]=useState('');
 const [selected,setSelected]=useState('');const attempts=useRef<Record<string,string>>({});
 const load=useCallback(async()=>{try{const response=await fetch('/api/issuance',{cache:'no-store'});const body=await response.json().catch(()=>{throw Error('발급 서비스 응답을 확인하지 못했습니다. 잠시 후 다시 조회하세요.');}) as Data & {error?:string};setUnauthorized(response.status===401);if(!response.ok)throw Error(body.error);setData(body);setError('');}catch(e){setData(previous=>previous?{...previous,receipts:previous.receipts.map(r=>({...r,status:'unknown'}))}:previous);setError(e instanceof Error?e.message:'현재 상태를 불러오지 못했습니다.');}},[]);
 useEffect(()=>{const initial=setTimeout(()=>void load(),0),timer=setInterval(()=>void load(),8000);return()=>{clearTimeout(initial);clearInterval(timer);};},[load]);
 const request=selected==='new'?undefined:(data?.requests.find(r=>r.id===selected)??data?.requests[0]);
 const receipt=data?.receipts.find(r=>r.requestId===request?.id);
 async function command(action:string,body:Record<string,unknown>={}){
  if(busy)return;setBusy(true);setError('');setNotice('');
  const fingerprint=JSON.stringify({action,...body}),key=attempts.current[fingerprint]??crypto.randomUUID();attempts.current[fingerprint]=key;
  try{const response=await fetch('/api/issuance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,key,...body})});const result=await response.json().catch(()=>{throw Error('처리 응답을 확인하지 못했습니다. 현재 상태를 먼저 조회하세요.');}) as {id?:string;error?:string};if(!response.ok)throw Error(result.error);delete attempts.current[fingerprint];if(result.id)setSelected(result.id);setConsent(false);setReason('');setNotice(action==='receive'?'기관 서명과 현재 상태를 검증한 자격을 지갑에 저장했습니다.':'발급 서버에 처리 결과를 저장했습니다.');await load();}
  catch(e){setError(e instanceof Error?e.message:'요청을 완료하지 못했습니다.');}finally{setBusy(false);}
 }
 const stage=receipt?4:request?.status==='issued'?2:request?1:0;
 return <main className="issuance-page">
  <header className="issuance-header"><a href="/welcome" aria-label="BizProof 홈"><BizProofLogo/></a><nav aria-label="발급 체험 메뉴"><Link href="/?view=apply">빠른 체험</Link><a href="/guide#guide-independent-issuer">이용자 가이드</a></nav></header>
  <section className="issuance-intro"><span className="issuance-kicker">{operator?'ISSUER REVIEW DESK':'A CREDENTIAL, ISSUED FOR YOU'}</span><h1>{operator?'발급기관 검토 체험':'자격을 발급받는 순간부터.'}</h1><p>{operator?'내 체험 공간의 신청만 검토합니다. 결정은 별도 발급 서버의 원장에 기록됩니다.':'동의하고 신청하면, 기관이 발급한 자격을 받아 두 곳에 활용할 수 있습니다.'}</p><div className="issuance-badges"><span><Building2 size={14}/> 별도 HTTP 발급 서버</span><span><LockKeyhole size={14}/> 기관 전용 Ed25519 키</span><span>합성 기업·인증 시뮬레이션</span></div></section>
  <div className="issuance-notice"><ShieldCheck/><p>휴대폰 본인확인이나 공동인증서 서명은 연결 전입니다. 가상 담당자의 동의를 체험하며, 실제 기업·대표권을 인증하지 않습니다. 발급 서버의 통신·전자서명·저장은 실제로 실행됩니다.</p></div>
  {unauthorized?<section className="issuance-card"><h2>내 체험 공간을 열어 주세요</h2><p>다른 방문자의 신청과 분리된 공간을 준비합니다. 실제 개인정보는 입력하지 마세요.</p><EntryForm demo returnTo={operator?'/issuer-demo':'/issuance'}/></section>:<>
   {error&&<div role="alert" className="issuance-error">{error}<button onClick={()=>void load()} disabled={busy}><RefreshCw size={14}/> 상태 다시 확인</button></div>}
   {notice&&<p role="status" className="issuance-success"><Check size={17}/>{notice}</p>}
   {data&&<><ol className="issuance-steps" aria-label="발급 진행">{['동의·신청','기관 검토','서명 발급','지갑 수신'].map((text,index)=><li key={text} className={stage>index?'done':stage===index?'current':''} aria-current={stage===index?'step':undefined}><span>{stage>index?<Check size={17}/>:index+1}</span>{text}</li>)}</ol>
    <div className="issuance-columns"><section className="issuance-card">
     <div className="issuance-section-title"><h2>{operator?'접수한 발급 신청':'기업 기본 · 재무 자격'}</h2><span className="issuance-chip">{request?labels[request.status]:'신규 신청'}</span></div>
     <h3>{data.catalog.catalog.name}</h3><dl className="issuance-facts"><div><dt>연 매출 (합성)</dt><dd>{data.catalog.catalog.claims.revenue.toLocaleString()}원</dd></div><div><dt>설립일 (합성)</dt><dd>{data.catalog.catalog.claims.foundedOn}</dd></div><div><dt>소재지 (합성)</dt><dd>{data.catalog.catalog.claims.region}</dd></div><div><dt>발급 후 사용처</dt><dd>구매사 등록 · 지원사업 신청</dd></div></dl>
     {data.requests.length>1&&<label className="issuance-field">신청 기록 선택<select value={request?.id??''} onChange={e=>setSelected(e.target.value)}>{selected==='new'&&<option value="">새 발급 신청</option>}{data.requests.map(r=><option value={r.id} key={r.id}>{new Date(r.createdAt).toLocaleString('ko-KR')} · {labels[r.status]}</option>)}</select></label>}
     {!operator&&(!request||['rejected','cancelled'].includes(request.status))&&<><details><summary>승인할 문서와 공유 범위</summary><p>문서 버전 1 · 기업 기본 자격의 발급 신청. 위 합성 기업 자료와 가상 담당자의 동의 기록을 발급기관에 전달합니다. 지갑 수신 후 구매사·지원사업 제출에는 별도 공유 동의가 필요합니다.</p><code>문서 해시 {data.catalog.documentHash}</code></details><label className="issuance-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy}/>실제 본인확인이 아닌 동의 체험임을 이해하고, 위 자료로 자격 발급을 신청합니다. {data.autoRun&&'고정 합성 자료의 모의 검토·서명 발급·지갑 수신은 자동으로 진행합니다.'}</label><button className="issuance-primary" disabled={!consent||busy} onClick={()=>void command('apply',{consent:true,documentHash:data.catalog.documentHash,automatic:!!data.autoRun})}>{busy?'발급 서버에서 처리하는 중…':data.autoRun?'동의하고 자동 발급·수신':'동의하고 발급 신청'}<ArrowRight size={16}/></button></>}
     {request&&<><p className="issuance-muted">신청 버전 {request.revision} · {new Date(request.createdAt).toLocaleString('ko-KR')}</p>{request.reason&&<p className="issuance-reason">기관 처리 사유: {request.reason}</p>}
      {operator&&request.status==='submitted'&&<><label className="issuance-field">검토 의견 <small>보완·반려 시 필수. 실제 개인정보를 입력하지 마세요.</small><textarea maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="issuance-actions"><button className="issuance-primary" disabled={busy} onClick={()=>void command('decide',{id:request.id,revision:request.revision,decision:'approve',reason})}>검토 승인·서명 발급</button><button disabled={busy||reason.trim().length<2} onClick={()=>void command('decide',{id:request.id,revision:request.revision,decision:'needs_changes',reason})}>보완 요청</button><button disabled={busy||reason.trim().length<2} onClick={()=>void command('decide',{id:request.id,revision:request.revision,decision:'reject',reason})}>반려</button></div></>}
      {!operator&&request.status==='submitted'&&<div className="issuance-waiting"><p>발급기관 검토를 기다리고 있습니다. 시연에서는 아래 화면에서 직접 기관 검토를 체험할 수 있습니다.</p><a className="issuance-link" href="/issuer-demo">내 신청의 기관 검토 체험 <ArrowRight size={16}/></a></div>}
      {!operator&&request.status==='needs_changes'&&<><label className="issuance-field">보완 내용 <small>합성 자료에 대한 확인 내용을 적어 주세요.</small><textarea maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="issuance-primary" disabled={busy||reason.trim().length<2} onClick={()=>void command('resubmit',{id:request.id,revision:request.revision,reason})}>보완 내용 보내기</button></>}
      {!operator&&['submitted','needs_changes'].includes(request.status)&&<details><summary>신청을 철회하려면</summary><button disabled={busy} onClick={()=>void command('cancel',{id:request.id,revision:request.revision})}>이 발급 신청 철회</button></details>}
      {request.status==='issued'&&!operator&&<div className="issuance-wallet"><FileCheck2 size={28}/><h3>{receipt?'내 기업 자격에 저장됨':'발급기관이 자격에 서명했습니다'}</h3>{receipt?<><p>현재 기관 상태: <strong>{labels[receipt.status]}</strong></p><p className="issuance-muted">{receipt.statusCheckedAt?new Date(receipt.statusCheckedAt).toLocaleTimeString('ko-KR')+' 서버 조회':'기관 상태를 확인할 수 없어 새 신청을 제한합니다.'}</p><code>원본 SHA-256 {receipt.digest}</code>{['revoked','expired'].includes(receipt.status)&&<button disabled={busy} onClick={()=>{setSelected('new');setConsent(false);}}>새 발급 신청 준비</button>}{receipt.status==='active'&&<div className="issuance-actions"><Link className="issuance-link" href="/?view=apply&company=issuer-demo-company&flow=issued">이 자격으로 두 곳에 신청 <ArrowRight size={16}/></Link><a href={'/api/platform?export=credential&id='+receipt.credentialId}>서명 원본 보기</a></div>}</>:<button className="issuance-primary" disabled={busy} onClick={()=>void command('receive',{id:request.id})}>서명 확인 후 지갑에 받기</button>}</div>}
      {operator&&request.status==='issued'&&<><p>자격 {request.credentialId}의 원본 서명이 발급 서버에 저장되어 있습니다.</p><a className="issuance-link" href="/issuance">신청자 화면에서 자격 받기 <ArrowRight size={16}/></a><details><summary>발급 취소 체험</summary><p>취소하면 이 자격으로 새 신청을 제출할 수 없습니다. 과거의 처리 기록과 블록체인 거래를 삭제하는 동작은 아닙니다.</p><label className="issuance-field">취소 사유<textarea maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<2} onClick={()=>void command('revoke',{id:request.credentialId,reason})}>발급기관 원장에서 취소</button></details></>}
     </>}
     {operator&&!request&&<p>아직 접수된 신청이 없습니다. <a href="/issuance">기업 자격 발급 신청하기 →</a></p>}
    </section><aside className="issuance-card issuance-monitor"><h2><Activity size={20}/> 실제 처리 기록</h2><p className="issuance-muted">발급 서버에 저장된 사건입니다. 새로고침해도 유지되며 자동으로 조회합니다.</p>{request?.events.length?<ol>{request.events.map(e=><li key={e.seq}><span className="issuance-event-dot"/><div><b>{labels[e.type]??e.type}</b><time dateTime={e.at}>{new Date(e.at).toLocaleTimeString('ko-KR')} · #{e.seq}</time><p>{e.detail}</p></div></li>)}</ol>:<p className="issuance-empty">발급 신청 후 접수·검토·서명 기록이 표시됩니다.</p>}{receipt&&<div className="issuance-received"><Check size={16}/><span>웹 지갑 수신·검증 기록<br/><time>{new Date(receipt.receivedAt).toLocaleString('ko-KR')}</time></span></div>}<div className="issuance-boundary"><b>실행 범위</b><p>인증: 시뮬레이션<br/>발급: 독립 프로세스·기관 서명<br/>재사용: 플랫폼 처리 결과 서명<br/>블록체인: 아래 작업 기록에서 별도 확인</p></div><button onClick={()=>void load()} disabled={busy}><RefreshCw size={14}/> 지금 상태 확인</button></aside></div></>}
   {receipt&&!operator&&<ProofJobsPanel credentialId={receipt.credentialId}/>}
   {!data&&!error&&<p role="status">발급 서버의 현재 상태를 확인하고 있습니다…</p>}
  </>}
  <footer className="issuance-footer">BizProof · 합성 데이터로 체험하는 기업 자격 발급과 재사용<a href={operator?'/issuance':'/issuer-demo'}>{operator?'신청자 화면':'내 신청의 기관 검토 체험'}</a></footer>
 </main>;
}
