"use client";
import {useEffect,useRef,useState} from 'react';
import type {LeiRecord} from '@/lib/lei-directory';
import {z} from 'zod';
import {Search,ExternalLink} from 'lucide-react';
const resultSchema=z.object({lei:z.string(),legalName:z.string(),jurisdiction:z.string(),entityStatus:z.string(),registrationStatus:z.string(),address:z.string(),lastUpdated:z.string(),nextRenewal:z.string().nullable(),source:z.string().regex(/^https:\/\/api\.gleif\.org\/api\/v1\/lei-records\/[A-Z0-9]{20}$/),checkedAt:z.string(),officialVleiVerified:z.literal(false),notice:z.string()});
export default function LeiLookup(){
 const [lei,setLei]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<LeiRecord|null>(null);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 return <div className="gleif-lookup"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setResult(null);controller.current?.abort();const request=new AbortController();controller.current=request;try{const r=await fetch('/api/lei?lei='+encodeURIComponent(lei),{signal:request.signal,cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(z.object({error:z.string()}).parse(body).error);setResult(resultSchema.parse(body));}catch(e){if(!request.signal.aborted)setError(e instanceof Error?e.message:'조회 실패');}finally{if(!request.signal.aborted)setBusy(false);}}}><label htmlFor="lei-directory-input">기업 LEI</label><div><input id="lei-directory-input" value={lei} disabled={busy} maxLength={20} required pattern="[A-Za-z0-9]{18}[0-9]{2}" placeholder="20자리 LEI 입력" onChange={e=>{setLei(e.target.value.toUpperCase());setResult(null);setError('');}}/><button disabled={busy} type="submit"><Search size={16}/>{busy?'조회 중…':'LEI 조회'}</button></div><small>조회할 LEI를 GLEIF 공개 API로 전송합니다.</small></form>{error&&<p role="alert">{error}</p>}{result&&<div className="gleif-lei-result" aria-live="polite"><span className="gleif-kicker">GLOBAL LEI INDEX · 조회 결과</span><h4>{result.legalName}</h4><dl>{[['LEI',result.lei],['관할',result.jurisdiction],['법인 상태',result.entityStatus],['LEI 등록 상태',result.registrationStatus],['법적 주소',result.address],['원본 갱신일',result.lastUpdated],['다음 갱신 예정',result.nextRenewal??'미제공']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>{result.notice}</p><small>조회 시각 {new Date(result.checkedAt).toLocaleString('ko-KR')}</small><a href={result.source} target="_blank" rel="noreferrer">GLEIF 원본 레코드 <ExternalLink size={13}/></a></div>}</div>;
}
