"use client";
import {useState} from 'react';
import MidnightChainWatch from './midnight-chain-watch';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {sdkManifestSchema,sdkPreparationSchema,sdkContractSchema} from '@/lib/midnight-sdk-schema';
export default function MidnightSdkPanel({administrator}:{administrator:boolean}){
 const [manifest,setManifest]=useState<z.infer<typeof sdkManifestSchema>|null>(null),[prepared,setPrepared]=useState<z.infer<typeof sdkPreparationSchema>|null>(null),[contract,setContract]=useState<z.infer<typeof sdkContractSchema>|null>(null),[address,setAddress]=useState(''),[request,setRequest]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function fetchData(path='',method='GET'){const r=await fetch('/api/midnight-sdk'+path,{method,cache:'no-store',...(method==='POST'?{headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare'})}:{})});const value=await r.json();if(!r.ok)throw Error(z.object({error:z.string()}).parse(value).error);return value;}
 async function run(operation:'manifest'|'prepare'|'inspect'){setBusy(true);setError('');if(operation==='manifest')setManifest(null);if(operation==='prepare')setPrepared(null);if(operation==='inspect')setContract(null);try{if(operation==='manifest')setManifest(sdkManifestSchema.parse(await fetchData()));if(operation==='prepare')setPrepared(sdkPreparationSchema.parse(await fetchData('','POST')));if(operation==='inspect')setContract(sdkContractSchema.parse(await fetchData('?address='+encodeURIComponent(address.trim())+(request.trim()?'&request='+encodeURIComponent(request.trim()):''))));}catch(e){setError(e instanceof Error?e.message:'SDK 검사 실패');}finally{setBusy(false);}}
 function downloadReport(){if(!contract)return;const blob=new Blob([JSON.stringify(contract,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='bizproof-chain-inspection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel bottom-panel"><div className="section-heading"><div><h2>Midnight.js 실행 및 체인 조회</h2><p>공식 SDK 4.1.1 · Compact 0.31.1 · 기존 기업 조건 회로 9개</p></div><span className="status warn">배포·실제 증명 별도</span></div><div className="button-row"><Button variant="outline" disabled={busy} onClick={()=>void run('manifest')}>컴파일 산출물 검사</Button><Button disabled={busy||!administrator} onClick={()=>void run('prepare')}>SDK 배포 거래 준비 검사</Button></div>{error&&<p role="alert" className="notice">{error}</p>}{manifest&&<div><p>SDK 산출물 {manifest.circuits.length}개 확인 · 브리지 네트워크 {manifest.network}</p><details><summary>회로별 검증 키와 파일 크기</summary>{manifest.circuits.map(c=><div key={c.circuit} className="compact-request"><b>{c.circuit}</b><p>Prover {c.proverBytes.toLocaleString()} B · Verifier {c.verifierBytes.toLocaleString()} B · IR {c.irBytes.toLocaleString()} B</p><p className="journey-id">SHA-256 {c.verifierSha256}</p></div>)}</details></div>}{prepared&&<div className="compact-request" role="status"><b>실제 SDK의 생성자 실행·미증명 거래 구성 확인</b><p>{prepared.notice}</p><small>{new Date(prepared.at).toLocaleString('ko-KR')} · proof 없음 · 지갑 거래 전송 없음 · 배포 안 됨</small></div>}
 <form onSubmit={e=>{e.preventDefault();void run('inspect');}}><fieldset disabled={busy} className="reviewed-form"><label>배포된 컨트랙트 주소<input aria-label="Midnight 컨트랙트 주소" value={address} onChange={e=>{setAddress(e.target.value);setContract(null);}} required pattern="[A-Fa-f0-9]{64}" maxLength={64} placeholder="64자리 16진수 주소"/></label><label>체인의 요청 식별값 (선택)<input aria-label="Midnight 체인 요청 식별값" value={request} onChange={e=>{setRequest(e.target.value);setContract(null);}} pattern="[A-Fa-f0-9]{64}" maxLength={64} placeholder="업무 requestId와 다른 체인 식별값"/></label><Button type="submit" variant="outline" disabled={busy}>체인 공개 상태 조회</Button></fieldset></form><p className="context-note">브리지가 설정한 한 네트워크에서 조회합니다. 입력 주소의 검증 키가 현재 BizProof 회로와 일치해야 결과를 표시합니다. SDK 내부 비공개 상태와 미증명 거래는 화면에 보내지 않습니다.</p>
 <MidnightChainWatch key={address.trim()+":"+request.trim()} address={address.trim()} request={request.trim()} onReport={setContract}/>{contract&&<div className="compact-request" role="status"><p className="journey-id">{contract.network} · {contract.contractAddress}</p>{contract.found?<><b>BizProof 검증 키 일치 · 인덱서 상태 조회 완료</b><dl className="detail-list"><dt>발급자 수</dt><dd>{contract.issuerCount}</dd><dt>취소 자격 수</dt><dd>{contract.revokedCount}</dd><dt>요청 / 결과 수</dt><dd>{contract.requestCount} / {contract.resultCount}</dd><dt>컨트랙트 기준 시각</dt><dd>{contract.trustedTime} (Unix seconds)</dd></dl>{contract.request&&<p>{!contract.request.exists?'요청 없음':contract.request.cancelled?'취소된 요청':!contract.request.submitted?(contract.request.expired?'컨트랙트 기준 시각상 만료된 요청':'제출 대기 중인 요청'):contract.request.eligible?'체인 기록: 조건 충족':'체인 기록: 조건 미충족'}</p>}<p>{contract.notice}</p></>:<b>해당 네트워크에 배포된 컨트랙트가 없습니다.</b>}<small>{new Date(contract.checkedAt).toLocaleString('ko-KR')}</small><div className="button-row"><Button variant="outline" onClick={downloadReport}>체인 조회 보고서 다운로드</Button></div></div>}</section>;
}
