'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Building2,CheckCircle2,ChevronDown,FileCheck2,FileText,FolderOpen,Landmark,Layers3,LoaderCircle,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {ViewState} from '@/lib/domain';
import type {Check,Precheck,ConsentChallenge,ProgramProfile,ProgramApplication} from '@/lib/program-types';
import './program-applications.css';
import './program-visuals.css';
import ProgramProofPanel from './program-proof-panel';
import ProgramSubmissionPanel from './program-submission-panel';
import {CheckDistribution,outcomeLabels,PreparationSteps,ProgramOverview} from './program-visuals';
const scenarioLabels:Record<string,string>={normal:'기본 기업 · 수치 충족', 'investment-path':'매출 대신 투자로 충족','missing-history':'수혜 이력 미확인','wrong-year':'회계연도 불일치','expired-tax':'납세 자격 만료','oversized-ir':'IR 11쪽 · 제한 초과',negative:'업력·재무·인원 미충족'};
type Application=Pick<ProgramApplication,'id'|'companyId'|'createdAt'|'revision'|'status'|'precheck'|'history'|'mode'> &{name:string;profileId:string};
type Catalog={profiles:(ProgramProfile&{windowStatus:string})[];companies:{id:string;name:string;synthetic:boolean}[];scenarios:string[];applications:Application[];autoRun?:boolean;canPrepareDemo:boolean;canUpload:boolean;notice:string};
async function call<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const value=await r.json() as T & {error?:string};if(!r.ok)throw Error(value.error??'요청을 처리하지 못했습니다.');return value;}
function CheckRow({check}:{check:Check}){return <li className={'program-check outcome-'+check.outcome}><div><span className="program-outcome">{outcomeLabels[check.outcome]}</span><strong>{check.label}</strong>{check.bonus&&<small>가점</small>}</div><p>{check.reason}</p>{check.children&&<details><summary>조건별 확인 내용</summary><ul>{check.children.map(c=><CheckRow key={c.id} check={c}/>)}</ul></details>}</li>;}
export default function ProgramApplications({data,refresh}:{data:ViewState;refresh:()=>Promise<void>}){
 const [catalog,setCatalog]=useState<Catalog>(),[company,setCompany]=useState(''),[profile,setProfile]=useState(''),[scenario,setScenario]=useState('normal'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{precheck:Precheck;consent:ConsentChallenge}>(),[consent,setConsent]=useState(false),[saved,setSaved]=useState(''),[reason,setReason]=useState<Record<string,string>>({}),[reviewEvidence,setReviewEvidence]=useState<Record<string,string>>({});
 const [kind,setKind]=useState<'all'|'grant'|'buyer'>('all'),[expanded,setExpanded]=useState(''),[autoConsent,setAutoConsent]=useState(false);const scrollToRecord=useRef(false);
 useEffect(()=>{if(!scrollToRecord.current||!saved)return;const node=document.getElementById('program-record-'+saved);if(node){scrollToRecord.current=false;node.scrollIntoView({behavior:'instant',block:'start'});}},[saved,catalog]);
 const target=catalog?.profiles.find(p=>p.id===profile),canApply=['company','admin','issuer'].includes(data.role);
 const applications=(catalog?.applications??[]).filter(a=>!canApply||!company||a.companyId===company);
 const companiesName=canApply?catalog?.companies.find(c=>c.id===company)?.name:undefined;
 async function load(){const value=await call<Catalog>('/api/programs');setCatalog(value);return value;}
 useEffect(()=>{let cancelled=false;call<Catalog>('/api/programs').then(v=>{if(!cancelled)setCatalog(v);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[data.role]);
 function reset(){setAutoConsent(false);setResult(undefined);setConsent(false);setSaved('');setError('');}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'처리 중 오류가 발생했습니다.');}finally{setBusy(false);}}
 async function prepare(){await run(async()=>{reset();const v=await call<{companyId:string}>('/api/programs',{scenario});await load();setCompany(v.companyId);await refresh();});}
 async function precheck(){await run(async()=>{reset();setResult(await call(`/api/programs/${profile}/precheck`,{companyId:company}));});}
 async function submit(){if(!result||!consent)return;await run(async()=>{const v=await call<Application>('/api/program-applications',{consent:result.consent,confirmed:true});setSaved(v.id);setExpanded(v.id);setConsent(false);await load();});}
 async function automatic(){if(!catalog?.autoRun||!target||!autoConsent)return;await run(async()=>{const v=await call<{companyId:string;precheck:Precheck;application:Application;chainError?:string}>('/api/program-demo',{profileId:profile,scenario,consent:true,scope:'synthetic-preparation-and-local-devnet-90-minutes'});scrollToRecord.current=true;setCompany(v.companyId);setResult(undefined);setConsent(false);setSaved(v.application.id);setExpanded(v.application.id);await load();await refresh();if(v.chainError)setError(v.chainError);});}
 async function review(a:Application,c:Check,decision:'confirmed'|'needs_changes'){await run(async()=>{await call(`/api/program-applications/${a.id}/review`,{revision:a.revision,ruleId:c.id,decision,reason:reason[a.id+':'+c.id]??'',evidenceIds:[reviewEvidence[a.id+':'+c.id]].filter(Boolean)});await load();});}
 async function upload(file:File,type:string){await run(async()=>{const r=await fetch(`/api/program-documents?profileId=${encodeURIComponent(profile)}&companyId=${encodeURIComponent(company)}&type=${encodeURIComponent(type)}`,{method:'POST',headers:{'Content-Type':'application/pdf'},body:file});const v=await r.json() as {error:string};if(!r.ok)throw Error(v.error);reset();setResult(await call(`/api/programs/${profile}/precheck`,{companyId:company}));});}
 return <section className="program-workspace" aria-label="실제 사례 준비">
  {error&&<div className="program-error" role="alert">{error}</div>}
  {!catalog?<div className="program-loading" role="status"><LoaderCircle className="spin" size={23}/>기관별 준비 공간을 불러오는 중입니다.</div>:<>
   <ProgramOverview grants={catalog.profiles.filter(p=>p.kind==='grant').length} buyers={catalog.profiles.filter(p=>p.kind==='buyer').length} credentialCount={canApply?(result?.precheck??applications.find(a=>a.id===saved)?.precheck)?.credentialDigests.length:undefined} checks={canApply?(result?.precheck??applications.find(a=>a.id===saved)?.precheck)?.checks:undefined} recordCount={applications.length} scope={companiesName?'선택한 기업 기준':'내 체험 공간 전체'}/>
   {canApply&&<PreparationSteps selected={Boolean(company&&target)} checked={Boolean(result||saved)} saved={Boolean(saved)} automatic={catalog.autoRun}/>}
   <div className="program-notice"><ShieldCheck size={18}/><span><strong>현재는 내부 사전검사와 제출 준비 단계입니다.</strong> 공식 접수·협력사 등록·선정 결과가 아닙니다. Midnight 검증은 준비 기록에서 별도로 요청합니다.</span></div>
   {catalog.canPrepareDemo&&canApply&&<section className="simple-card program-fixture"><span className="program-fixture-icon" aria-hidden="true"><Layers3 size={25}/></span><div><h3>미리 준비한 시연 자료</h3><p>서명 자격 <b>5개</b>와 합성 PDF <b>13개</b>를 한 번 저장해 여러 대상에 재사용합니다.</p></div><label>시연 사례<select value={scenario} disabled={busy} onChange={e=>{setScenario(e.target.value);setAutoConsent(false);}}>{catalog.scenarios.map(s=><option value={s} key={s}>{scenarioLabels[s]}</option>)}</select></label><Button disabled={busy} onClick={()=>void prepare()}>{busy?<LoaderCircle className="spin"/>:<FileCheck2 size={16}/>}시연 자료 불러오기</Button></section>}
   {canApply&&<>
    <section className="program-selection" aria-labelledby="program-selection-title">
     <div className="program-section-heading"><div><span className="program-eyebrow">01 · 선택</span><h3 id="program-selection-title">어느 곳에 준비할까요?</h3><p>기관별 조건과 필수 서류를 비교한 뒤 하나를 선택하세요.</p></div><label className="program-company">신청 기업<select value={company} disabled={busy} onChange={e=>{setCompany(e.target.value);reset();}}><option value="">기업을 선택하세요</option>{catalog.companies.map(c=><option value={c.id} key={c.id}>{c.name}{c.synthetic?' (합성)':''}</option>)}</select></label></div>
     <div className="program-catalog-toolbar"><div className="program-filters" role="group" aria-label="대상 유형 필터">{(['all','grant','buyer'] as const).map(k=><button key={k} type="button" aria-pressed={kind===k} onClick={()=>setKind(k)}>{k==='all'?'전체':k==='grant'?'지원기관':'구매사'}<span>{catalog.profiles.filter(p=>k==='all'||p.kind===k).length}곳</span></button>)}</div><span>공개 기준 참고 · 기관별 원문 확인</span></div>
     <div className="program-grid">{catalog.profiles.filter(p=>kind==='all'||p.kind===kind).map(p=>{const Icon=p.kind==='grant'?Landmark:Building2;return <button className={'program-target program-target-'+p.kind} type="button" key={p.id} disabled={busy} aria-pressed={profile===p.id} onClick={()=>{setProfile(p.id);reset();}}>
      <span className="program-target-top"><span className="program-org-icon"><Icon size={22}/></span><span className={'program-window window-'+p.windowStatus}>{p.windowStatus==='closed'?'과거 공고 재현':p.windowStatus==='open'?'공고 기간 내':p.windowStatus==='upcoming'?'접수 시작 전':'구매 준비 참고'}</span></span>
      <span className="program-target-kind">{p.kind==='grant'?'지원기관':'구매사'} · {p.category}</span><h4>{p.name}</h4>
      <span className="program-target-facts"><span><ShieldCheck size={14}/>참고 기준 {p.rules.length}항목</span><span><FileText size={14}/>필수 서류 {p.documents.filter(d=>!d.bonus).length}종</span></span>
      <small>자동 접수 미연결</small><span className="program-target-footer"><b>{profile===p.id?'선택됨':'조건 살펴보기'}</b>{profile===p.id?<CheckCircle2 size={19}/>:<ArrowRight size={19}/>}</span>
     </button>;})}</div>
    </section>
    {catalog.autoRun&&target&&<section className="simple-card program-auto" aria-label="공개 데이터 자동 시연"><div><span className="program-eyebrow"><Layers3 size={16}/> 공개 합성 자료 전용</span><h3>한 번 시작하면, 검증까지 자동으로</h3><p><strong>{target.name}</strong> · {scenarioLabels[scenario]}</p><p>선택한 시연 자료 준비 → 사전검사 → 기록 저장 → 실행 허용 → Local Devnet 거래 → 독립 검증을 이어갑니다. 별도 관리자 승인 없이 진행하며 결과는 아래 기록에서 확인합니다.</p></div><label className="simple-consent"><input type="checkbox" checked={autoConsent} disabled={busy} onChange={e=>setAutoConsent(e.target.checked)}/>이 합성 사례로 준비 기록을 저장하고 실행 서버에서 원본을 처리해 Local Devnet에 조건·가명 식별자·결과를 기록하는 자동 시연에 동의합니다. 실행 동의는 90분간 유효하며 실제 기관에는 제출하지 않습니다.</label><Button disabled={busy||!autoConsent} onClick={()=>void automatic()}>{busy?<LoaderCircle className="spin"/>:<ArrowRight size={16}/>}동의한 자료로 자동 시연 시작</Button><p className="simple-note">원본 수치·PDF는 체인에 게시하지 않습니다. 미충족·자료 누락은 그대로 표시하고, 거래가 불확실하면 멈춰 대조합니다. 재시도는 동일 준비 기록과 실행 작업을 재사용합니다.</p></section>}
    {target&&<section className="simple-card program-detail" aria-label="선택한 대상 안내"><div className="program-detail-copy"><span className="program-eyebrow">선택한 대상</span><h3>{target.name}</h3><a href={target.sourceUrl} target="_blank" rel="noopener noreferrer">공식 원문 확인 <ArrowUpRight size={15}/></a>{target.window&&<p className="program-deadline">공고 접수 기간<br/><strong>{new Date(target.window.opens).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} ~ {new Date(target.window.closes).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</strong> (한국시간)</p>}{target.notes.map(n=><p key={n}>{n}</p>)}<small>원문 확인 {target.sourceCheckedAt.slice(0,10)} · {target.version}</small><p className="simple-note">{target.contact}</p></div><div className="program-document-preview"><span className="program-eyebrow"><FileText size={15}/>준비할 자료</span><ul>{target.documents.map(d=><li key={d.type}><FileText size={15}/><span>{d.label}</span><small>{d.bonus?'선택':d.maxPages?`${d.maxPages}쪽 이내`:'필수'}</small></li>)}</ul><Button disabled={!company||busy} onClick={()=>void precheck()}>{busy?<LoaderCircle className="spin"/>:<ShieldCheck size={16}/>}보유 자료로 사전 확인</Button>{!company&&<p>신청 기업을 먼저 선택하세요.</p>}</div></section>}
    {result&&<section className="simple-card program-result" aria-label="사전 확인 결과" aria-live="polite"><div className="program-section-heading"><div><span className="program-eyebrow">02 · 사전 확인</span><h3>확인된 내용과 보완할 항목</h3></div><span className={'program-result-outcome outcome-'+result.precheck.outcome}>{outcomeLabels[result.precheck.outcome]}</span></div><CheckDistribution checks={result.precheck.checks}/><div className="program-summary"><FileCheck2 size={18}/><span>유효 자격 {result.precheck.credentialDigests.length}개 재사용 · 근거 문서 {result.precheck.documents.length}개</span></div><ul className="program-checks">{result.precheck.checks.map(c=><CheckRow key={c.id} check={c}/>)}</ul>{result.precheck.warnings.length>0&&<details><summary>사용하지 않은 자격 {result.precheck.warnings.length}개</summary>{result.precheck.warnings.map(w=><p key={w}>{w}</p>)}</details>}
     {catalog.canUpload&&target&&<details><summary>부족한 PDF 보완</summary>{target.documents.map(d=><label className="simple-field" key={d.type}>{d.label} · 20MB{d.maxPages?` · ${d.maxPages}쪽`:''}<input type="file" accept="application/pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,d.type);}}/></label>)}</details>}
     <div className="program-sharing"><ShieldCheck size={21}/><div><p><strong>준비 기록에 포함:</strong> 기업 식별자, 대상·규칙 버전, 조건별 결과, 서류 목록·해시</p><p>매출·투자 원본 수치와 PDF 본문은 패키지에 포함하지 않습니다. 서버는 원본을 처리하며 조건 결과로 값의 범위를 추론할 수 있습니다.</p></div></div>
     {saved?<p className="program-success"><CheckCircle2 size={18}/>내부 준비 기록이 저장되었습니다. 아래에서 준비 목록을 내려받으세요.</p>:<><label className="simple-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>{target?.organization} 제출 준비를 위해 위 항목을 저장하는 데 동의합니다. 외부로 전송하지 않습니다.</label><Button disabled={!consent||busy} onClick={()=>void submit()}>제출 준비 기록 저장<ArrowRight size={16}/></Button><p className="simple-note">동의는 5분간 유효합니다. 자료·규칙이 바뀌면 다시 확인합니다. 미확인 항목이 있으면 보완 초안으로 저장됩니다.</p></>}
    </section>}
   </>}
   <section className="program-records" aria-label="기관별 준비 기록"><div className="program-section-heading"><div><span className="program-eyebrow">03 · 준비 기록</span><h3>기관별로 이어서 준비하세요 <span>{applications.length}</span></h3><p>{companiesName?companiesName+' · 선택한 기업의 기록':'내 체험 공간 전체 기록'} · 저장 당시의 검사 결과입니다.</p></div><FolderOpen size={28}/></div>
    {!applications.length&&<div className="program-empty"><span><FolderOpen size={30}/></span><h4>첫 번째 준비 기록을 만들어 보세요</h4><p>대상 선택 → 사전 확인 → 공유 동의 후 저장하면<br/>준비 목록 다운로드와 선택적 Midnight 검증을 이어갈 수 있습니다.</p></div>}
    {applications.map(a=><article className={'simple-card program-record'+(expanded===a.id?' is-open':'')} key={a.id}><button type="button" className="program-record-toggle" aria-expanded={expanded===a.id} aria-controls={'program-record-'+a.id} onClick={()=>setExpanded(expanded===a.id?'':a.id)}><span className="program-record-symbol"><FolderOpen size={21}/></span><span className="program-record-title"><span className="simple-pill">{a.status==='internal_reviewed'?'내부 검토 완료':'보완·검토 초안'} · 공식 미접수</span><strong>{a.name}</strong><small>{a.mode==='synthetic'?'합성 시연 자료':'시험 운영 자료'} · {new Date(a.createdAt).toLocaleString('ko-KR')} · 수정 {a.revision}</small></span><span className="program-record-expand">{expanded===a.id?'접기':'기록 열기'}<ChevronDown size={19}/></span></button><CheckDistribution checks={a.precheck.checks} compact/>
     <div id={'program-record-'+a.id} hidden={expanded!==a.id}>{expanded===a.id&&<div className="program-record-body">
      {canApply&&<a className="program-download" href={`/api/program-applications/${a.id}/package`}><FileCheck2 size={16}/>제출 준비 목록 다운로드 (JSON)</a>}
      <details open={catalog.autoRun&&saved===a.id}><summary>결과·검토 기록</summary><ul className="program-checks">{a.precheck.checks.map(c=><CheckRow check={c} key={c.id}/>)}</ul>{a.history.map((h,i)=><p key={i}>{h.simulation?'모의 검토':'내부 검토'} · {h.decision==='confirmed'?'확인':'보완 요청'} · {h.reason}</p>)}{(data.role==='admin'||data.role===catalog.profiles.find(p=>p.id===a.profileId)?.kind)&&a.precheck.checks.filter(c=>c.outcome==='manual_review').map(c=><div className="program-review" key={c.id}><label>{c.label} · 검토 사유<textarea value={reason[a.id+':'+c.id]??''} maxLength={1000} onChange={e=>setReason({...reason,[a.id+':'+c.id]:e.target.value})}/></label><label>확인한 근거 서류<select value={reviewEvidence[a.id+':'+c.id]??''} onChange={e=>setReviewEvidence({...reviewEvidence,[a.id+':'+c.id]:e.target.value})}><option value="">실제로 검토한 근거를 선택하세요</option>{a.precheck.documents.map(d=><option value={d.id} key={d.id}>{a.precheck.checks.find(check=>check.documentIds.includes(d.id)&&check.id.startsWith('document:'))?.label??'서명 자격의 근거'} · {d.id.slice(0,8)}</option>)}</select></label><p>실제 담당기관 승인이 아닌 모의 검토입니다.</p><Button variant="outline" disabled={busy||!reviewEvidence[a.id+':'+c.id]||(reason[a.id+':'+c.id]?.trim().length??0)<10} onClick={()=>void review(a,c,'confirmed')}>모의 검토 확인</Button><Button variant="outline" disabled={busy||!reviewEvidence[a.id+':'+c.id]||(reason[a.id+':'+c.id]?.trim().length??0)<10} onClick={()=>void review(a,c,'needs_changes')}>보완 요청</Button></div>)}</details>
      <ProgramSubmissionPanel profileId={a.profileId}/>{canApply&&catalog.canPrepareDemo&&<ProgramProofPanel applicationId={a.id}/>}
     </div>}</div>
    </article>)}
   </section>
  </>}
 </section>;
}
