'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,FileCheck2,LoaderCircle,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {ViewState} from '@/lib/domain';
import type {Check,Precheck,ConsentChallenge,ProgramProfile,ProgramApplication,Outcome} from '@/lib/program-types';
import './program-applications.css';
import ProgramProofPanel from './program-proof-panel';
import ProgramSubmissionPanel from './program-submission-panel';
const outcomeLabels:Record<Outcome,string>={pass:'확인 완료',fail:'조건 미충족',unknown:'자료 필요',manual_review:'담당자 확인',not_applicable:'선택 사항'};
const scenarioLabels:Record<string,string>={normal:'기본 기업 · 수치 충족', 'investment-path':'매출 대신 투자로 충족','missing-history':'수혜 이력 미확인','wrong-year':'회계연도 불일치','expired-tax':'납세 자격 만료','oversized-ir':'IR 11쪽 · 제한 초과',negative:'업력·재무·인원 미충족'};
type Application=Pick<ProgramApplication,'id'|'companyId'|'createdAt'|'revision'|'status'|'precheck'|'history'|'mode'> &{name:string;profileId:string};
type Catalog={profiles:(ProgramProfile&{windowStatus:string})[];companies:{id:string;name:string;synthetic:boolean}[];scenarios:string[];applications:Application[];canPrepareDemo:boolean;canUpload:boolean;notice:string};
async function call<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const value=await r.json() as T & {error?:string};if(!r.ok)throw Error(value.error??'요청을 처리하지 못했습니다.');return value;}
function CheckRow({check}:{check:Check}){return <li className={'program-check outcome-'+check.outcome}><div><span className="program-outcome">{outcomeLabels[check.outcome]}</span><strong>{check.label}</strong>{check.bonus&&<small>가점</small>}</div><p>{check.reason}</p>{check.children&&<details><summary>조건별 확인 내용</summary><ul>{check.children.map(c=><CheckRow key={c.id} check={c}/>)}</ul></details>}</li>;}
export default function ProgramApplications({data,refresh}:{data:ViewState;refresh:()=>Promise<void>}){
 const [catalog,setCatalog]=useState<Catalog>(),[company,setCompany]=useState(''),[profile,setProfile]=useState(''),[scenario,setScenario]=useState('normal'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{precheck:Precheck;consent:ConsentChallenge}>(),[consent,setConsent]=useState(false),[saved,setSaved]=useState(''),[reason,setReason]=useState<Record<string,string>>({}),[reviewEvidence,setReviewEvidence]=useState<Record<string,string>>({});
 const target=catalog?.profiles.find(p=>p.id===profile),canApply=['company','admin','issuer'].includes(data.role);
 async function load(){const value=await call<Catalog>('/api/programs');setCatalog(value);return value;}
 useEffect(()=>{let cancelled=false;call<Catalog>('/api/programs').then(v=>{if(!cancelled)setCatalog(v);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[data.role]);
 function reset(){setResult(undefined);setConsent(false);setSaved('');setError('');}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'처리 중 오류가 발생했습니다.');}finally{setBusy(false);}}
 async function prepare(){await run(async()=>{reset();const v=await call<{companyId:string}>('/api/programs',{scenario});await load();setCompany(v.companyId);await refresh();});}
 async function precheck(){await run(async()=>{reset();setResult(await call(`/api/programs/${profile}/precheck`,{companyId:company}));});}
 async function submit(){if(!result||!consent)return;await run(async()=>{const v=await call<Application>('/api/program-applications',{consent:result.consent,confirmed:true});setSaved(v.id);setConsent(false);await load();});}
 async function review(a:Application,c:Check,decision:'confirmed'|'needs_changes'){await run(async()=>{await call(`/api/program-applications/${a.id}/review`,{revision:a.revision,ruleId:c.id,decision,reason:reason[a.id+':'+c.id]??'',evidenceIds:[reviewEvidence[a.id+':'+c.id]].filter(Boolean)});await load();});}
 async function upload(file:File,type:string){await run(async()=>{const r=await fetch(`/api/program-documents?profileId=${encodeURIComponent(profile)}&companyId=${encodeURIComponent(company)}&type=${encodeURIComponent(type)}`,{method:'POST',headers:{'Content-Type':'application/pdf'},body:file});const v=await r.json() as {error:string};if(!r.ok)throw Error(v.error);reset();setResult(await call(`/api/programs/${profile}/precheck`,{companyId:company}));});}
 return <section className="program-workspace" aria-label="실제 사례 준비">
  <header className="program-intro"><span className="simple-pill">실제 공고 3곳 · 구매사 사례 3곳</span><h2>같은 기업 자료로, 다른 조건을 확인하세요</h2><p>대상을 고르면 보유 자료를 다시 사용하고 부족한 항목만 안내합니다. 현재는 내부 사전검사와 제출 준비 단계입니다.</p><div className="program-notice"><ShieldCheck size={20}/><span>공식 접수·협력사 등록·선정 결과가 아닙니다. 사전검사 후 별도로 동의하면 관리자의 승인을 거쳐 새 Midnight 거래와 독립 검증을 진행할 수 있습니다.</span></div></header>
  {error&&<div className="program-error" role="alert">{error}</div>}
  {!catalog?<p role="status">대상 목록을 불러오는 중입니다.</p>:<>
   {catalog.canPrepareDemo&&canApply&&<section className="simple-card program-fixture"><div><h3>미리 준비한 시연 자료</h3><p>가상 기업의 자격 5개와 합성 PDF 13개를 한 번 저장해 여러 대상에 재사용합니다.</p></div><label>시연 사례<select value={scenario} disabled={busy} onChange={e=>setScenario(e.target.value)}>{catalog.scenarios.map(s=><option value={s} key={s}>{scenarioLabels[s]}</option>)}</select></label><Button disabled={busy} onClick={()=>void prepare()}>{busy?<LoaderCircle className="spin"/>:<FileCheck2 size={16}/>}시연 자료 불러오기</Button></section>}
   {canApply&&<><label className="simple-field program-company">신청 기업<select value={company} disabled={busy} onChange={e=>{setCompany(e.target.value);reset();}}><option value="">기업을 선택하세요</option>{catalog.companies.map(c=><option value={c.id} key={c.id}>{c.name}{c.synthetic?' (합성)':''}</option>)}</select></label>
   <div className="simple-heading"><h3>1. 확인할 대상 선택</h3><span>원문 확인: 2026-09-25</span></div><div className="program-grid">{catalog.profiles.map(p=><button className="program-target" type="button" key={p.id} disabled={busy} aria-pressed={profile===p.id} onClick={()=>{setProfile(p.id);reset();}}><span className="simple-pill">{p.windowStatus==='closed'?'과거 공고 재현':p.windowStatus==='open'?'공고 기간 내':p.windowStatus==='upcoming'?'접수 시작 전':'구매 준비 참고'}</span><h4>{p.name}</h4><p>{p.category}</p><small>{p.version} · 공식 경로 안내 · 자동 접수 미연결</small><b>{profile===p.id?'✓ 선택됨':'조건 살펴보기 →'}</b></button>)}</div>
   {target&&<section className="simple-card program-detail"><h3>{target.name}</h3><a href={target.sourceUrl} target="_blank" rel="noopener noreferrer">공식 원문 확인 ↗</a>{target.window&&<p>공고 접수 기간: {new Date(target.window.opens).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} ~ {new Date(target.window.closes).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} (한국시간)</p>}{target.notes.map(n=><p key={n}>{n}</p>)}<p className="simple-note">{target.contact}</p><Button disabled={!company||busy} onClick={()=>void precheck()}>{busy?<LoaderCircle className="spin"/>:<ShieldCheck size={16}/>}보유 자료로 사전 확인</Button></section>}
   {result&&<section className="simple-card" aria-label="사전 확인 결과" aria-live="polite"><h3>2. 확인된 내용과 보완할 항목</h3><div className="program-summary"><strong>{outcomeLabels[result.precheck.outcome]}</strong><span>유효 자격 {result.precheck.credentialDigests.length}개 재사용 · 근거 문서 {result.precheck.documents.length}개</span></div><ul className="program-checks">{result.precheck.checks.map(c=><CheckRow key={c.id} check={c}/>)}</ul>{result.precheck.warnings.length>0&&<details><summary>사용하지 않은 자격 {result.precheck.warnings.length}개</summary>{result.precheck.warnings.map(w=><p key={w}>{w}</p>)}</details>}
    {catalog.canUpload&&target&&<details><summary>부족한 PDF 보완</summary>{target.documents.map(d=><label className="simple-field" key={d.type}>{d.label} · 20MB{d.maxPages?` · ${d.maxPages}쪽`:''}<input type="file" accept="application/pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,d.type);}}/></label>)}</details>}
    <div className="program-sharing"><p><strong>준비 기록에 포함:</strong> 기업 식별자, 대상·규칙 버전, 조건별 결과, 서류 목록·해시</p><p>매출·투자 원본 수치와 PDF 본문은 패키지에 포함하지 않습니다. 서버는 원본을 처리하며 조건 결과로 값의 범위를 추론할 수 있습니다.</p></div>
    {saved?<p className="program-success"><CheckCircle2 size={18}/>내부 준비 기록이 저장되었습니다. 아래에서 준비 목록을 내려받으세요.</p>:<><label className="simple-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>{target?.organization} 제출 준비를 위해 위 항목을 저장하는 데 동의합니다. 외부로 전송하지 않습니다.</label><Button disabled={!consent||busy} onClick={()=>void submit()}>제출 준비 기록 저장<ArrowRight size={16}/></Button><p className="simple-note">동의는 5분간 유효합니다. 자료·규칙이 바뀌면 다시 확인합니다. 미확인 항목이 있으면 보완 초안으로 저장됩니다.</p></>}
   </section>}</>}
   <section aria-label="기관별 준비 기록"><h3>3. 기관별 준비 기록</h3>{!catalog.applications.length&&<p>저장한 준비 기록이 없습니다.</p>}{catalog.applications.map(a=><article className="simple-card program-record" key={a.id}><span className="simple-pill">{a.status==='internal_reviewed'?'내부 검토 완료':'보완·검토 초안'} · 공식 미접수</span><h4>{a.name}</h4><p>가상 자료 · {new Date(a.createdAt).toLocaleString('ko-KR')} · 수정 {a.revision}</p>{canApply&&<a className="program-download" href={`/api/program-applications/${a.id}/package`}>제출 준비 목록 다운로드 (JSON)</a>}<details><summary>결과·검토 기록</summary><ul className="program-checks">{a.precheck.checks.map(c=><CheckRow check={c} key={c.id}/>)}</ul>{a.history.map((h,i)=><p key={i}>{h.simulation?'모의 검토':'내부 검토'} · {h.decision==='confirmed'?'확인':'보완 요청'} · {h.reason}</p>)}{(data.role==='admin'||data.role===catalog.profiles.find(p=>p.id===a.profileId)?.kind)&&a.precheck.checks.filter(c=>c.outcome==='manual_review').map(c=><div className="program-review" key={c.id}><label>{c.label} · 검토 사유<textarea value={reason[a.id+':'+c.id]??''} maxLength={1000} onChange={e=>setReason({...reason,[a.id+':'+c.id]:e.target.value})}/></label><label>확인한 근거 서류<select value={reviewEvidence[a.id+':'+c.id]??''} onChange={e=>setReviewEvidence({...reviewEvidence,[a.id+':'+c.id]:e.target.value})}><option value="">실제로 검토한 근거를 선택하세요</option>{a.precheck.documents.map(d=><option value={d.id} key={d.id}>{a.precheck.checks.find(check=>check.documentIds.includes(d.id)&&check.id.startsWith('document:'))?.label??'서명 자격의 근거'} · {d.id.slice(0,8)}</option>)}</select></label><p>실제 담당기관 승인이 아닌 모의 검토입니다.</p><Button variant="outline" disabled={busy||!reviewEvidence[a.id+':'+c.id]||(reason[a.id+':'+c.id]?.trim().length??0)<10} onClick={()=>void review(a,c,'confirmed')}>모의 검토 확인</Button><Button variant="outline" disabled={busy||!reviewEvidence[a.id+':'+c.id]||(reason[a.id+':'+c.id]?.trim().length??0)<10} onClick={()=>void review(a,c,'needs_changes')}>보완 요청</Button></div>)}</details><ProgramSubmissionPanel profileId={a.profileId}/>{canApply&&catalog.canPrepareDemo&&<ProgramProofPanel applicationId={a.id}/>}</article>)}</section>
  </>}
 </section>;
}
