'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity,ArrowRight,CheckCircle2,RefreshCw,ShieldCheck} from 'lucide-react';
import Link from 'next/link';
import type {publicProofJob} from '@/lib/proof-jobs';
import {matchesApplication,proofJobProgress} from '@/lib/proof-job-progress';
type Job=ReturnType<typeof publicProofJob>;
type Candidate={credentialId:string;requests:{id:string;kind:string;audience:string;policyHash:string}[]};
const labels:Record<string,string>={awaiting_approval:'진행자 승인 대기',queued:'실행기 대기',running:'실제 체인 처리 중',awaiting_verification:'독립 인덱서 대조 중',confirmed:'체인 결과 확인',blocked:'새 사용 차단',needs_attention:'거래 상태 확인 필요',cancelled:'요청 취소'};
const stages:Record<string,string>={wallet:'지갑 동기화',deploy:'전용 계약 배포',source:'기관 원본·현재 상태 확인',attestation:'회로용 자격 연결',proof:'영지식 증명 생성',balance:'거래 준비',submission:'네트워크 전송',create:'원래 신청 연결',submit:'조건 증명 제출',indexer:'독립 인덱서 대조',revoke:'체인 취소 반영',failed:'상태 확인 필요',recovered:'저장된 거래 복구'};
export default function ProofJobsPanel({administrator=false,credentialId,requestIds}:{administrator?:boolean;credentialId?:string;requestIds?:string[]}){
 const [data,setData]=useState<{jobs:Job[];candidates?:Candidate[]}>(),[error,setError]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false);const requestKey=useRef(''),loadSequence=useRef(0);
 const endpoint=administrator?'/api/admin/proof-jobs':'/api/proof-jobs';
 const load=useCallback((signal?:AbortSignal)=>{const sequence=++loadSequence.current;return fetch(endpoint,{cache:'no-store',signal}).then(async r=>{const b=await r.json().catch(()=>{throw Error('서비스 응답을 확인하지 못했습니다. 잠시 후 새로고침해 주세요.');}) as {jobs:Job[];candidates?:Candidate[];error?:string};if(!r.ok)throw Error(b.error??'현재 상태를 확인하지 못했습니다.');return b;}).then(b=>{if(!signal?.aborted&&sequence===loadSequence.current){setData(b);setError('');}}).catch(e=>{if(!signal?.aborted&&sequence===loadSequence.current)setError(e instanceof Error?e.message:'상태 조회 실패');});},[endpoint]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);const timer=setInterval(()=>void load(controller.signal),6000);return()=>{controller.abort();clearInterval(timer);};},[load]);
 async function command(body:Record<string,unknown>){if(busy)return;setBusy(true);try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),b=await r.json().catch(()=>{throw Error('서비스 응답을 확인하지 못했습니다. 잠시 후 새로고침해 주세요.');}) as {jobs:Job[];candidates?:Candidate[];error?:string};if(!r.ok)throw Error(b.error??'처리 실패');setConsent(false);if(body.action==='request')requestKey.current='';await load();}catch(e){setError(e instanceof Error?e.message:'처리 실패');}finally{setBusy(false);}}
 const jobs=data?.jobs.filter(j=>matchesApplication(j,credentialId,requestIds))??[];
 const candidate=data?.candidates?.map(c=>({...c,requests:c.requests.filter(r=>!requestIds||requestIds.includes(r.id))})).find(c=>(!credentialId||c.credentialId===credentialId)&&new Set(c.requests.map(r=>r.kind)).size===2);
 const selectionIdentity=JSON.stringify(candidate?[candidate.credentialId,candidate.requests.map(r=>[r.id,r.policyHash])]:null);
 useEffect(()=>{setConsent(false);requestKey.current='';},[selectionIdentity]);
 return <section className="issuance-card proof-jobs" id="issued-chain-process"><div className="issuance-section-title"><h2><Activity size={20}/> {administrator?'진행자용 Midnight 실행 관리':'이 자격의 Midnight 처리'}</h2><button onClick={()=>void load()} disabled={busy} aria-label="체인 작업 새로고침"><RefreshCw size={15}/></button></div>
  <p>신청 접수와 체인 확정은 각각 표시합니다. 위에서 제출한 같은 자격과 두 신청을 연결하며, 관리자 승인 후 별도 실행 환경이 가동 중일 때 처리합니다.</p>
  <div className="issuance-boundary"><b>확인 범위</b><p>합성 기업·본인확인 시뮬레이션 · 실제 Midnight Local Devnet 거래. 웹 서버와 실행기는 원본을 처리합니다. 회로는 기관의 Ed25519 원본을 직접 검증하지 않고, 검증한 원본에서 실행기가 만든 Schnorr 자격을 검증합니다.</p></div>
  {error&&<p role="alert" className="issuance-error">{error} · 마지막 표시를 현재 완료 상태로 해석하지 마세요.</p>}
  {!administrator&&(!jobs.length||jobs.every(j=>['cancelled','blocked'].includes(j.status)))&&(candidate?<div className="proof-job-request"><label className="issuance-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>이 합성 자격과 두 신청을 별도 실행기에 전달하는 데 동의합니다. 동의는 90분 동안 유효합니다.</label><button className="issuance-primary" disabled={!consent||busy||!!error} onClick={()=>{requestKey.current||=crypto.randomUUID();const selected=['buyer','grant'].map(kind=>candidate.requests.find(r=>r.kind===kind)!.id);void command({action:'request',credentialId:candidate.credentialId,requestIds:selected,key:requestKey.current,consent:true});}}>Midnight 시연 실행 요청 <ArrowRight size={16}/></button></div>:<p className="issuance-muted">같은 자격으로 두 기관 신청을 먼저 완료해 주세요. <Link href="/?view=apply&company=issuer-demo-company&flow=issued">신청 화면으로 이동 →</Link></p>)}
  {!jobs.length&&<><p className="issuance-empty">{data?'아직 체인 실행을 요청하지 않았습니다. 신청 완료가 체인 확정을 뜻하지 않습니다.':'체인 작업 상태를 조회하고 있습니다.'}</p>{requestIds&&<ol className="proof-steps" aria-label="신청부터 체인 검증까지">{proofJobProgress().map(s=><li key={s.label} className={s.state}>{s.label}</li>)}</ol>}</>}
  {jobs.map(j=><article key={j.id} className="proof-job"><div className="issuance-section-title"><h3>{labels[j.status]}</h3><span className="issuance-chip">Local Devnet</span></div><code>작업 {j.id}<br/>자격 {j.credentialId}<br/>원본 {j.sourceDigest}</code>
   <ul className="proof-request-list">{j.requests.map(r=><li key={r.id}><b>{r.audience}</b><code>{r.id}</code></li>)}</ul>
   {j.reason&&<p className="issuance-reason">{j.reason}</p>}{j.currentStatus==='unknown'&&<p role="status">기관 현재 상태 미확인 · 과거 거래 기록과 새 사용 가능 여부는 다릅니다.</p>}
   <ol className="proof-steps" aria-label="신청부터 체인 검증까지">{proofJobProgress(j).map(s=><li key={s.label} className={s.state} aria-current={s.state==='current'?'step':undefined}>{s.label}</li>)}</ol>
   {j.status==='queued'&&<p className="issuance-muted">승인 완료 · 실행 환경이 준비되면 순서대로 처리합니다. 대기는 증명 생성이나 거래 확정을 의미하지 않습니다.</p>}
   {j.status==='awaiting_verification'&&<p className="issuance-muted">거래 영수증을 받았습니다. 별도 검증기가 원래 신청·계약과 대조한 뒤에만 검증 완료가 됩니다.</p>}
   <h4>최근 처리 기록 · 최신순</h4><div className="issuance-monitor"><ol>{j.events.slice(-10).reverse().map(e=><li key={e.seq}><span className="issuance-event-dot"/><div><b>{stages[e.stage]} · {e.status==='complete'?'단계 완료':e.status==='sent'?'전송됨':e.status==='blocked'?'차단':e.status==='uncertain'?'미확정':'진행 중'}</b><time dateTime={e.at}>{new Date(e.at).toLocaleTimeString('ko-KR')} · #{e.seq}</time>{e.txId&&<code>{e.txId}</code>}</div></li>)}</ol></div>
   {j.contractAddress&&<details><summary>계약과 확정 영수증 {j.receipts.length}개</summary><code>계약 {j.contractAddress}</code>{j.receipts.map(r=><p key={r.txId}><b>{r.operation} · 블록 {r.blockHeight}</b><code>{r.txId}</code></p>)}</details>}
   {j.verification&&<div className="issuance-received"><CheckCircle2 size={20}/><div><b>{j.status==='confirmed'?'별도 인덱서 검증 기록':'보존된 검증 기록 · 현재 사용 가능 여부와 구분'}</b><p>{new Date(j.verification.checkedAt).toLocaleString('ko-KR')} · {j.verification.receiptsVerified}개 거래 대조</p>{j.verification.results.map(r=><p key={r.id}>{j.requests.find(x=>x.id===r.id)?.audience} · {r.eligible?'조건 충족':'조건 미충족'}</p>)}</div></div>}
   {j.revocation!=='none'&&<p className="issuance-reason"><ShieldCheck size={17}/> {j.revocation==='confirmed'?'발급기관 취소 + 체인 취소 확인':'발급기관 취소 완료 · 체인 취소 반영 대기'}. 과거 거래는 보존됩니다.</p>}
   <div className="issuance-actions">{administrator&&j.status==='needs_attention'&&<button disabled={busy||!!error} onClick={()=>void command({action:'resume',id:j.id,revision:j.revision})}>기존 거래 대조 후 이어서 처리</button>}{administrator&&j.status==='awaiting_approval'&&<button className="issuance-primary" disabled={busy||!!error} onClick={()=>void command({action:'approve',id:j.id,revision:j.revision})}>이 두 신청의 체인 실행 승인</button>}{['awaiting_approval','queued'].includes(j.status)&&<button disabled={busy} onClick={()=>void command({action:'cancel',id:j.id,...(administrator?{revision:j.revision}:{})})}>실행 요청 취소</button>}</div>
  </article>)}
 </section>;
}
