"use client";
import {useState,useEffect,type FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {type ViewState,type IssuanceRequest} from '@/lib/domain';
export default function ReviewedIssuance({data,busy,act,openCredential,reviewRequest}:{reviewRequest?:IssuanceRequest;data:ViewState;busy:boolean;act:(a:string,p:Record<string,unknown>)=>Promise<unknown>;openCredential:(id:string)=>void}){
 const [companyId,setCompanyId]=useState(reviewRequest?.companyId??data.companies[0]?.id??''),[evidenceIds,setEvidenceIds]=useState<string[]>(reviewRequest?.evidenceIds??[]),[error,setError]=useState('');
 useEffect(()=>{if(reviewRequest)document.getElementById('reviewed-issuance-form')?.scrollIntoView({block:'start'});},[reviewRequest]);
 const previous=data.credentials.filter(c=>c.companyId===companyId&&c.claims).sort((a,b)=>b.issuedAt.localeCompare(a.issuedAt))[0]?.claims;
 if(!['admin','issuer'].includes(data.role))return null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{const result=await act('issue-reviewed-credential',{...(reviewRequest?{reviewRequestId:reviewRequest.id,reviewRevision:reviewRequest.revision??0}:{}),companyId,issuerId:f.get('issuerId'),schemaId:data.schemas[0]?.id,days:90,claims:{revenue:Number(f.get('revenue')),foundedOn:f.get('foundedOn'),region:f.get('region'),certified:f.get('certified')==='on'},source:{reference:f.get('reference'),period:f.get('period'),method:f.get('method'),evidenceIds,confirmed:f.get('confirmed')==='on'}}) as {id:string};openCredential(result.id);}catch(e){setError(e instanceof Error?e.message:'발급 실패');}}
 return <details id="reviewed-issuance-form" open={reviewRequest?true:undefined} className="panel bottom-panel"><summary><b>문서 검토 근거를 연결하여 발급</b></summary><p>기업 상세에서 가상 증빙 파일을 먼저 첨부하세요. 담당자가 확인한 속성, 출처, 기간, 검토 방법과 파일 해시를 함께 서명합니다.</p>{reviewRequest&&<p className="simple-note">기업·증빙·참조번호를 자동 연결했습니다. 기존 속성이 표시되면 원본과 다시 대조하세요. 검토 판단과 기간·방법은 직접 확인합니다.</p>}<form key={companyId} onSubmit={submit}><fieldset disabled={busy||!!reviewRequest&&reviewRequest.status!=='pending'} className="reviewed-form"><label>기업<select disabled={!!reviewRequest} value={companyId} onChange={e=>{setCompanyId(e.target.value);setEvidenceIds([]);}}>{data.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>발급기관<select name="issuerId" defaultValue={reviewRequest?.issuerId} required>{data.issuers.filter(i=>i.status==='active').map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>검토한 연 매출 (원)<input name="revenue" defaultValue={previous?.revenue} type="number" min="0" max="1000000000000" required/></label><label>검토한 설립일<input name="foundedOn" defaultValue={previous?.foundedOn} type="date" required/></label><label>검토한 소재지<input name="region" defaultValue={previous?.region??data.companies.find(c=>c.id===companyId)?.region} required maxLength={160}/></label><label>출처·참조번호<input name="reference" defaultValue={reviewRequest?.id} required minLength={3} maxLength={200}/></label><label>대상 기간<input name="period" placeholder="예: 2025 회계연도" required minLength={3} maxLength={100}/></label><label>확인 방법<textarea name="method" required minLength={5} maxLength={500}/></label><label className="consent"><input name="certified" type="checkbox"/>인증 보유 확인</label><div><b>검토한 증빙</b>{data.evidence.filter(f=>f.companyId===companyId).map(f=><label className="consent" key={f.id}><input type="checkbox" checked={evidenceIds.includes(f.id)} onChange={e=>setEvidenceIds(e.target.checked?[...evidenceIds,f.id]:evidenceIds.filter(id=>id!==f.id))}/><a href={'/api/evidence?id='+encodeURIComponent(f.id)} target="_blank" rel="noreferrer">{f.name}</a></label>)}{!data.evidence.some(f=>f.companyId===companyId)&&<p>첨부된 증빙이 없습니다. 기업 디렉터리에서 먼저 업로드하세요.</p>}</div><label className="consent"><input name="confirmed" type="checkbox" required/>위 파일을 검토했고 입력한 속성과 검토 방법을 확인했습니다. 현재는 가상 데이터로 진행합니다.</label><Button type="submit" disabled={busy||!evidenceIds.length}>검토 기록과 함께 서명 발급</Button></fieldset>{error&&<p role="alert">{error}</p>}</form></details>;
}
