'use client';
import {useState,useRef,useContext,useLayoutEffect,createContext,type RefObject} from 'react';
import {useJsonForms,JsonForms,ResolvedJsonFormsDispatch,withJsonFormsControlProps,withJsonFormsLayoutProps} from '@jsonforms/react';
import {rankWith,isControl,uiTypeIs,type ControlProps,type LayoutProps,type Layout} from '@jsonforms/core';
import {formAjv,formDefinition,initialFormData,submittedValues,type FormSpec} from '@/lib/form-schema';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
function Control({id,label,data,handleChange,path,visible,enabled,errors,schema,uischema,required}:ControlProps){if(!visible)return null;const options=uischema.options??{},choices=options.choices as {value:string;label:string}[]|undefined;const described=id+'-help',invalid=!!errors;const change=(v:string)=>handleChange(path,v===''?undefined:options.inputType==='number'?Number(v):v);return <div className={options.inputType==='textarea'?'field wide':'field'}><label htmlFor={id}>{label}{required?' *':''}</label>{choices?<Select value={data??''} disabled={!enabled} onValueChange={change}><SelectTrigger id={id} aria-invalid={invalid} aria-describedby={described}><SelectValue placeholder="선택하세요"/></SelectTrigger><SelectContent>{choices.map(c=><SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select>:options.inputType==='textarea'?<textarea id={id} disabled={!enabled} value={data??''} onChange={e=>change(e.target.value)} aria-invalid={invalid} aria-describedby={described}/>:<Input id={id} type={options.inputType} disabled={!enabled} value={data??''} min={schema.minimum} max={schema.maximum} step={options.inputType==='number'?1:undefined} onChange={e=>change(e.target.value)} aria-invalid={invalid} aria-describedby={described}/>}<small id={described}>{options.help}{invalid&&<span role="alert"> {label}: {errors}</span>}</small></div>;}
const Snapshot=createContext<RefObject<Record<string,unknown>>|null>(null);
function Grid(props:LayoutProps){const ref=useContext(Snapshot),state=useJsonForms();useLayoutEffect(()=>{if(ref)ref.current=state.core?.data??{};},[ref,state.core?.data]);if(!props.visible)return null;return <div className="form-grid">{(props.uischema as Layout).elements.map((element,index)=><ResolvedJsonFormsDispatch key={index} schema={props.schema} uischema={element} path={props.path} enabled={props.enabled} renderers={props.renderers} cells={props.cells}/>)}</div>;}
const renderers=[{tester:rankWith(2,isControl),renderer:withJsonFormsControlProps(Control)},{tester:rankWith(2,uiTypeIs('VerticalLayout')),renderer:withJsonFormsLayoutProps(Grid)}];
const i18n={locale:'ko',translateError:(error:{keyword:string;params:Record<string,unknown>})=>({required:'필수 항목을 입력하세요.',type:'올바른 형식으로 입력하세요.',minLength:'필수 항목을 입력하세요.',pattern:'공백만 입력할 수 없습니다.',enum:'목록에서 선택하세요.',format:error.params.format==='past-date'?'유효한 과거 날짜를 입력하세요.':error.params.format==='date'?'유효한 달력 날짜를 입력하세요.':'이메일 형식을 확인하세요.',minimum:`${error.params.limit} 이상이어야 합니다.`,maximum:`${error.params.limit} 이하여야 합니다. (매출 범위도 확인하세요.)`}[error.keyword]??'입력값을 확인하세요.')};
function Editor({spec,close,busy}:{spec:FormSpec;close:()=>void;busy:boolean}){const [definition]=useState(()=>formDefinition(spec.fields)),[validate]=useState(()=>formAjv.compile(definition.schema));const [data,setData]=useState<Record<string,unknown>>(()=>initialFormData(spec.fields)),[attempted,setAttempted]=useState(false),[failure,setFailure]=useState(''),[sending,setSending]=useState(false);const [formInput,setFormInput]=useState<Record<string,unknown>>(()=>initialFormData(spec.fields)),snapshot=useRef<Record<string,unknown>>(formInput);const locked=busy||sending;
 // Only feed data back at submission. Debounced change events can otherwise overwrite rapid edits.
 // Refresh it with the live snapshot before changing validationMode, which reinitializes JSON Forms.
 return <form noValidate onSubmit={async e=>{e.preventDefault();if(locked)return;const current=snapshot.current;setFormInput(current);setData(current);setAttempted(true);if(!validate(current))return;setSending(true);setFailure('');try{await spec.onSubmit(submittedValues(spec.fields,current));close();}catch(e){setFailure(e instanceof Error?e.message:'저장하지 못했습니다. 입력을 확인하고 다시 시도하세요.');}finally{setSending(false);}}}><Snapshot.Provider value={snapshot}><JsonForms {...definition} data={formInput} renderers={renderers} ajv={formAjv} i18n={i18n} readonly={locked} validationMode={attempted?'ValidateAndShow':'ValidateAndHide'} onChange={({data:next})=>setData(next)}/></Snapshot.Provider>{attempted&&!validate(data)&&<p role="alert">입력 오류를 수정한 후 다시 저장하세요.</p>}{failure&&<p role="alert">{failure}</p>}<div className="dialog-actions"><Button type="button" variant="outline" disabled={locked} onClick={close}>취소</Button><Button type="submit" disabled={locked}>{locked?'저장 중…':spec.submitLabel??'저장하기'}</Button></div></form>;
}
export function FormDialog({spec,close,busy}:{spec:FormSpec|null;close:()=>void;busy:boolean}){return <Dialog open={!!spec} onOpenChange={v=>{if(!v&&!busy)close();}}><DialogContent className="bp-dialog"><DialogHeader><DialogTitle>{spec?.title}</DialogTitle><DialogDescription>{spec?.description}</DialogDescription></DialogHeader>{spec&&<Editor key={spec.title} spec={spec} close={close} busy={busy}/>}</DialogContent></Dialog>;}

