'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
type Status={mode:'demo'|'openbao';available:boolean;stored:string;encrypted:boolean;keyVersion:number|null;latestVersion:number|null;needsMigration:boolean};
export function StorageSecurityPanel(){const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/security'),body=await r.json() as Status&{error?:string};if(!r.ok)throw Error(body.error);setStatus(body);setError('');}catch(e){setError(e instanceof Error?e.message:'상태 조회 실패');}},[]);
 useEffect(()=>{const controller=new AbortController();fetch('/api/security',{signal:controller.signal}).then(async r=>{const body=await r.json() as Status&{error?:string};if(!r.ok)throw Error(body.error);setStatus(body);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'상태 조회 실패');});return()=>controller.abort();},[]);
 async function run(action:'protect'|'rewrap'){setBusy(true);try{const r=await fetch('/api/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}),body=await r.json() as {error?:string};if(!r.ok)throw Error(body.error);await load();}catch(e){setError(e instanceof Error?e.message:'작업 실패');}finally{setBusy(false);}}
 return <section className="panel"><h2>저장 데이터 보호 · OpenBao</h2><p>발급 개인키·기업 속성·내부 기록을 포함한 워크스페이스 JSON을 암호화해 저장합니다.</p>{status&&<><p><b>{status.encrypted?'현재 데이터: Transit 암호문':'현재 데이터: 애플리케이션 암호화 미적용'}</b> · {status.mode==='demo'?'데모 저장 모드':status.available?'OpenBao 키 설정 확인됨':'OpenBao 연결 또는 키 설정 확인 필요'}</p>{status.keyVersion&&<p>저장 키 버전 {status.keyVersion} · 서버 최신 버전 {status.latestVersion??'확인 불가'}</p>}<div className="button-row"><Button variant="outline" disabled={busy} onClick={()=>void load()}>상태 새로고침</Button><Button disabled={busy||!status.available||status.encrypted} onClick={()=>void run('protect')}>기존 데이터 암호화</Button><Button variant="outline" disabled={busy||!status.available||!status.encrypted||status.keyVersion===status.latestVersion} onClick={()=>void run('rewrap')}>최신 키로 암호문 갱신</Button></div></>}{error&&<p role="alert">{error}</p>}<p>서버 메모리에서는 업무 처리를 위해 복호화합니다. 첨부파일(R2), 기존 백업·이력, Midnight 로컬 키 저장소는 이 보호 범위에 포함되지 않습니다. 키 교체는 OpenBao 운영자가 수행합니다.</p></section>;
}
