'use client';
import {useEffect,useState} from 'react';
import {Activity,ArrowDown,CheckCircle2,Download,FileKey2,LockKeyhole,Play,Pause,RefreshCw,ShieldCheck} from 'lucide-react';
import {midnightEvidenceSchema,type MidnightEvidence} from '@/lib/midnight-evidence';
import {sdkContractSchema} from '@/lib/midnight-sdk-schema';
const asset='/evidence/midnight-web-devnet.json';
const stages:Record<string,string>={proof:'증명 생성',balance:'거래 수수료 준비',submission:'노드로 제출',transaction:'거래 확정 확인','source-signature':'웹 원본 서명 확인','web-results':'동일 웹 요청 결과 대조',revocation:'취소 후 재사용 차단','wallet-sync':'지갑 동기화','dust-ready':'수수료 자원 확인'};
const statuses:Record<string,string>={running:'실행 시작',complete:'완료',pending:'확인 중',sent:'전송됨',finalized:'확정',unconfirmed:'성공 미확정',blocked:'차단 확인',verified:'검사 통과',failed:'실패'};
export default function VerificationEvidence(){
 const [report,setReport]=useState<MidnightEvidence>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[live,setLive]=useState(''),[checking,setChecking]=useState(false);
 useEffect(()=>{const abort=new AbortController();fetch(asset,{signal:abort.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('검증 기록을 아직 불러올 수 없습니다.');return midnightEvidenceSchema.parse(await r.json());}).then(r=>{setReport(r);setError('');}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'검증 기록 형식을 확인하세요.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[retry]);
 const events=report?.events.filter(e=>!['wallet-sync','dust-ready'].includes(e.stage))??[];
 useEffect(()=>{if(!playing||!events.length)return;const timer=setInterval(()=>{if(document.hidden)return;setStep(s=>{if(s>=events.length-1){setPlaying(false);return s;}return s+1;});},1200);return()=>clearInterval(timer);},[playing,events.length]);
 async function recheck(){if(!report)return;setChecking(true);setLive('로컬 브리지와 인덱서에서 현재 상태를 확인합니다.');try{for(const o of report.outcomes){const res=await fetch('/api/midnight-sdk?address='+report.contractAddress+'&request='+o.requestId,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error('로컬 로그인·SDK 브리지·동일 Devnet이 실행되어 있어야 합니다. 공개 사이트에서는 저장된 실행 증거를 확인하세요.');const current=sdkContractSchema.parse(await res.json());if(!current.found||current.contractAddress!==report.contractAddress||current.request?.id!==o.requestId||!current.request.submitted||current.request.eligible!==(o.scenario!=='negative'))throw Error('현재 체인 상태가 저장된 결과와 다릅니다.');}setLive('현재 인덱서의 BizProof 검증 키와 세 요청의 판정 결과가 일치합니다. 저장된 기록에는 별도의 취소 시연도 포함되어 있습니다.');}catch(e){setLive(e instanceof Error?e.message:'현재 체인을 확인할 수 없습니다.');}finally{setChecking(false);}}
 return <>
 <section className="evidence-intro"><span className="evidence-eyebrow">MIDNIGHT · VERIFIABLE BUSINESS ELIGIBILITY</span><h1>한 번의 기업 자격,<br/>서로 다른 두 기관의 검증.</h1><p>웹에 저장된 서명 자격과 원래 신청 요청을 Local Devnet에 연결한 실제 시연 기록입니다. 무엇이 실행됐고, 어떤 정보를 보호하는지 확인하세요.</p><div className="evidence-disclosure"><ShieldCheck size={20}/><span><strong>저장된 시연 증거</strong> · 아래 기록은 별도 합성 데이터 실행 사례입니다. 현재 방문자의 신청을 온체인 검증한 결과가 아니며, Local Devnet의 현재 가동 상태도 뜻하지 않습니다.</span></div></section>
 {loading&&<div className="evidence-loading" role="status"><RefreshCw/>검증 기록을 불러오고 있습니다.</div>}
 {error&&<div role="alert" className="evidence-error"><p>실행 증거를 표시할 수 없습니다. 완료로 추정하지 않습니다.</p><details><summary>오류 내용</summary>{error}</details><button onClick={()=>{setLoading(true);setRetry(r=>r+1);}}>다시 불러오기</button></div>}
 {report&&<>
 <div className="evidence-stats"><div><small>실행 환경</small><b>Local Devnet</b></div><div><small>재사용한 웹 자격</small><b>1개</b></div><div><small>연결한 원래 웹 요청</small><b>2개</b></div><div><small>확정된 거래</small><b>{report.receipts.length}건</b></div></div>
 <section className="evidence-section"><div className="evidence-heading"><div><span>01 / RESULTS</span><h2>성공과 거절을 함께 확인합니다</h2></div><a href={asset} download><Download size={16}/>실행 증거 JSON</a></div><p>검증 당시의 결과입니다. 마지막 단계에서 체인 자격을 취소하고 재사용 차단을 확인했습니다.</p><div className="evidence-results">{report.outcomes.map(o=><article key={o.scenario} className={o.scenario==='negative'?'negative':''}><span>{o.scenario==='buyer'?'구매사 등록':o.scenario==='grant'?'지원사업 신청':'미충족 비교'}</span><h3>{o.audience}</h3><strong>{o.scenario==='negative'?'조건 미충족':'검증 당시 조건 충족'}</strong><p>{o.scenario==='buyer'?'매출 2억 원 이상':o.scenario==='grant'?'매출 5억 원 이하 · 서울 · 업력 3년 이내':'매출 5억 원 이상 조건과 비교'}</p><details><summary>실제 거래와 요청 확인</summary><dl><dt>웹 자격</dt><dd>{o.credentialId}</dd>{o.webRequestId&&<><dt>원래 웹 요청</dt><dd>{o.webRequestId}</dd></>}<dt>체인 요청</dt><dd>{o.requestId}</dd><dt>거래 ID</dt><dd>{o.receipt.txId}</dd><dt>확정 블록</dt><dd>{o.receipt.blockHeight}</dd><dt>결과</dt><dd>{o.receipt.status}</dd></dl></details></article>)}</div><div className="evidence-revoked"><LockKeyhole size={20}/><div><strong>취소 후 재사용 차단 확인</strong><p>취소 거래가 확정된 뒤 SDK의 회로 검사에서 거절했습니다. 거절된 제출에 새 성공 거래가 생성된 것은 아닙니다. 웹 원본과 체인 자격의 취소 상태는 별도로 관리합니다.</p></div></div></section>
 <section className="evidence-section"><div className="evidence-heading"><div><span>02 / EXECUTION TRACE</span><h2>실제 실행 순서를 따라가 보세요</h2></div><button onClick={()=>{if(step===events.length-1)setStep(0);setPlaying(p=>!p);}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'재생 일시정지':'기록 재생'}</button></div><p>완료된 실행 기록을 읽기 쉬운 속도로 재생합니다. 새로운 거래를 만들거나 실제 처리 시간을 표현하지 않습니다.</p><div className="evidence-trace-current" aria-live="polite"><Activity/><div><small>{events[step]?.operation} · {events[step]?.at}</small><h3>{stages[events[step]?.stage]??events[step]?.stage}</h3><b>{statuses[events[step]?.status]??events[step]?.status}</b></div></div><label className="evidence-slider">실행 기록 {step+1} / {events.length}<input aria-label="실행 기록 위치" type="range" min={0} max={Math.max(0,events.length-1)} value={step} onChange={e=>{setPlaying(false);setStep(Number(e.target.value));}}/></label><details><summary>모든 실행 기록 보기</summary><ol className="evidence-event-list">{events.map((e,i)=><li key={i}><time>{new Date(e.at).toLocaleTimeString('ko-KR')}</time><span>{e.operation}</span><b>{stages[e.stage]??e.stage}</b><span>{statuses[e.status]??e.status}</span></li>)}</ol></details></section>
 <section className="evidence-section"><div className="evidence-heading"><div><span>03 / VERIFY</span><h2>직접 재현하고 대조할 수 있습니다</h2></div></div><dl className="evidence-identifiers"><dt>계약 주소</dt><dd>{report.contractAddress}</dd><dt>원본 자격 SHA-256</dt><dd>{report.source.digest}</dd><dt>실행 완료 시각</dt><dd>{new Date(report.completedAt).toLocaleString('ko-KR')}</dd></dl><p>공개 사이트의 파일은 기록 시점의 증거입니다. 소스 저장소의 Docker 실행기로 새 Devnet에서 다시 실행할 수 있습니다. 같은 Devnet을 유지한 로컬 환경에서는 현재 상태도 조회할 수 있습니다.</p><div className="evidence-actions"><a href="https://github.com/xaikorea/midnight-korea-hackathon-2026" target="_blank" rel="noreferrer">소스·실행 설명서 ↗</a><button disabled={checking} onClick={()=>void recheck()}><RefreshCw size={16}/>{checking?'조회 중':'로컬 체인 현재 상태 대조'}</button></div>{live&&<p role="status" className="evidence-local-status">{live}</p>}</section>
 </>}
 <section className="evidence-section"><div className="evidence-heading"><div><span>04 / PRIVACY & TRUST</span><h2>누가 어떤 정보를 확인하나요?</h2></div></div><div className="evidence-flow"><div><FileKey2/><b>기업·발급기관·웹 서버</b><p>원본 기업 속성과 Ed25519 자격을 처리합니다.</p></div><ArrowDown/><div><LockKeyhole/><b>로컬 발급·증명 실행기</b><p>원본 서명을 확인하고 Schnorr 자격을 만들어 Compact 증명을 생성합니다. 실행기와 증명 서버는 원본을 처리합니다.</p></div><ArrowDown/><div><ShieldCheck/><b>Midnight Local Devnet</b><p>검증 가능한 증명과 정책·요청·결과를 처리합니다. 원본 매출·설립일을 공개 결과에 넣지 않습니다.</p></div><ArrowDown/><div><CheckCircle2/><b>구매사·지원기관</b><p>자신의 조건 충족 여부와 검증 근거를 확인합니다. 조건 결과로 일부 범위를 추론할 수 있습니다.</p></div></div><p className="evidence-disclosure">가상 기업·테스트 발급기관을 사용합니다. 원본 자료의 진실성은 발급기관의 검토에 의존하며 공식 vLEI 인증이나 실제 기관의 선정·계약 승인이 아닙니다. 공개 식별값은 연결될 수 있어 기관 간 추적 불가능성을 보장하지 않습니다.</p></section>
 </>;
}
