"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import type {VerificationRequest} from '@/lib/domain';
import {z} from 'zod';
import {verifierStatus} from '@/lib/waltid-verifier';
const sessionSchema=z.object({id:z.string().uuid(),requestId:z.string(),status:verifierStatus,expiresAt:z.string(),authorizationUrl:z.string().nullable(),notice:z.string(),eligible:z.null()});
const labels={UNKNOWN:'상태 확인 필요',ACTIVE:'지갑 제출 대기',UNUSED:'아직 제출되지 않음',EXPIRED:'세션 만료',SUCCESSFUL:'외부 서버 검증 성공 · 업무 승인 별도',FAILED:'외부 서버 검증 실패'};
export default function WaltidVerifierPanel({requests}:{requests:VerificationRequest[]}){
 const [now]=useState(()=>Date.now());
 const [sessions,setSessions]=useState<z.infer<typeof sessionSchema>[]>([]),[configured,setConfigured]=useState(false),[requestId,setRequestId]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();void fetch('/api/verifier',{signal:abort.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('외부 검증 설정을 불러오지 못했습니다.');return z.object({configured:z.boolean(),sessions:z.array(sessionSchema)}).parse(await r.json());}).then(x=>{if(!abort.signal.aborted){setConfigured(x.configured);setSessions(x.sessions);}}).catch(()=>{if(!abort.signal.aborted)setError('외부 검증 설정을 불러오지 못했습니다.');});return()=>abort.abort();},[]);
 async function run(body:unknown){setBusy(true);setError('');try{const r=await fetch('/api/verifier',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(z.object({error:z.string()}).parse(data).error);const item=sessionSchema.parse(data);setSessions(previous=>[item,...previous.filter(s=>s.id!==item.id)]);}catch(e){setError(e instanceof Error?e.message:'외부 검증 요청 실패');}finally{setBusy(false);}}
 return <section className="panel bottom-panel"><div className="section-heading"><div><h2>외부 지갑 제출 검증</h2><p>walt.id Verifier API 2 · OpenID4VP · 기업 자격 요청</p></div><span className="status warn">{configured?'서버 설정됨 · 연결은 실행 시 확인':'검증 서버 미설정'}</span></div><p className="context-note">구매·지원 요청의 기업 식별자와 허용 발급기관으로 자격을 요청합니다. JWT VC의 원본 속성이 외부 검증 서버에 전달될 수 있으며, 결과는 업무 승인이나 Midnight 증명이 아닙니다.</p><label>연결할 업무 요청<select aria-label="외부 검증 업무 요청" value={requestId} onChange={e=>setRequestId(e.target.value)} disabled={busy}><option value="">요청 선택</option>{requests.filter(r=>r.status==='pending'&&Date.parse(r.expiresAt)>now).map(r=><option key={r.id} value={r.id}>{r.policy.name} · {r.companyId}</option>)}</select></label><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy}/>외부 서버의 원본 속성 처리 가능성을 확인했습니다.</label><div className="button-row"><Button disabled={!configured||!requestId||!consent||busy} onClick={()=>void run({action:'create',requestId,consent:true})}>지갑 제출 요청 만들기</Button></div>{error&&<p role="alert">{error}</p>}{sessions.map(s=><div className="compact-request" key={s.id}><b>{labels[s.status]}</b><p className="journey-id">업무 요청 {s.requestId}</p><p>유효기간 {new Date(s.expiresAt).toLocaleString('ko-KR')}</p>{s.authorizationUrl&&<><label>지갑 요청 링크<textarea aria-label="지갑 요청 링크" readOnly value={s.authorizationUrl}/></label><p>호환 지갑에서 링크를 열어 제출 내용을 확인하세요.</p></>}<Button variant="outline" disabled={busy} onClick={()=>void run({action:'refresh',id:s.id})}>검증 상태 확인</Button><p className="context-note">{s.notice}</p></div>)}</section>;
}
