/* eslint-disable @next/next/no-html-link-for-pages */
import BizProofLogo from './bizproof-logo';
import EntryForm from './welcome-start';
import WelcomeMotion from './welcome-motion';
import './welcome-motion.css';
import {publicDemo} from '@/lib/public-demo';
export default function Welcome(){return <main className="welcome">
 <header className="welcome-nav"><a href="/" aria-label="BizProof 홈"><BizProofLogo/></a><nav aria-label="접속 페이지 메뉴"><a href="/guide">이용자 가이드 ↗</a><a href="/admin/login">관리자 접속</a></nav></header>
 <WelcomeMotion><div className="welcome-hero"><div className="welcome-copy"><span className="welcome-kicker"><i/> BUSINESS TRUST, SIMPLIFIED</span><h1>한 번 증명하고,<br/><em>더 많은 기회</em>로.</h1><p className="welcome-lead">매번 같은 서류를 준비하는 대신,<br/>하나의 기업 자격으로 구매사 등록과<br className="welcome-mobile"/> 지원사업 조건을 확인하세요.</p><EntryForm demo={publicDemo()}/><a className="welcome-guide-link" href="/issuance">자격 발급부터 체험하기 →</a><a className="welcome-guide-link" href="/guide#guide-public-demo">처음이신가요? 5분 시연 따라 하기 →</a><div className="welcome-details"><span>회원가입 없이 체험</span><span>방문자별 독립 공간</span><span>가상 기업 데이터</span></div></div>
 <div className="welcome-visual" aria-label="하나의 기업 자격을 두 기관에 재사용하는 흐름"><div className="welcome-orbit" aria-hidden="true"><i/><i/><i/></div><span className="welcome-visual-tag" aria-hidden="true"><i/> ONE VERIFIED IDENTITY</span><div className="welcome-pass"><div className="welcome-pass-top"><BizProofLogo animated compact/><span>BUSINESS CREDENTIAL<br/><b>기업 자격 카드</b></span><small>DEMO</small></div><div className="welcome-company">주식회사 한빛테크<span>설명을 위한 가상 기업</span></div><div className="welcome-pass-rule"/><div className="welcome-pass-bottom"><span>원본 정보 대신<br/><b>필요한 조건만 확인</b></span><span className="welcome-verified">✓ 서명 기반 시연</span></div></div><svg className="welcome-connectors" viewBox="0 0 500 62" preserveAspectRatio="none" fill="none" aria-hidden="true"><path d="M250 0V15Q250 27 230 27H144Q125 27 125 42V62M250 0V15Q250 27 270 27H356Q375 27 375 42V62"/><path className="welcome-signal" d="M250 0V15Q250 27 230 27H144Q125 27 125 42V62"/><path className="welcome-signal welcome-signal-alt" d="M250 0V15Q250 27 270 27H356Q375 27 375 42V62"/></svg><div className="welcome-destinations"><div><span>01 / PROCUREMENT</span><b>구매사 등록</b><small>요청 조건 확인 ✓</small></div><div><span>02 / OPPORTUNITY</span><b>지원사업 신청</b><small>같은 자격 재사용 ✓</small></div></div><p className="welcome-caption">ONE CREDENTIAL. TWO OPPORTUNITIES.</p></div></div></WelcomeMotion>
 <section className="welcome-steps" aria-label="체험 순서">{[['01','신청 대상 선택','기업과 자격은 미리 준비되어 있습니다.'],['02','공유 확인·한 번 제출','선택한 기관에 보낼 내용을 읽고 동의하세요.'],['03','결과 자동 확인','기관별 검증 결과를 한눈에 확인하세요.']].map(([n,t,d])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></article>)}</section>
 <footer className="welcome-footer"><p>공개 체험은 합성 데이터와 서버 전자서명을 사용합니다. 실제 기관 인증·사업 선정·블록체인 거래 완료를 의미하지 않습니다.<br/>체험 세션은 2시간 유지됩니다. 실제 개인정보나 기업 기밀은 입력하지 마세요.</p><a href="/privacy/analytics">방문 정보 안내</a></footer>
 </main>}
