/* eslint-disable @next/next/no-html-link-for-pages */
import BizProofLogo from './bizproof-logo';
import EntryForm from './welcome-start';
import {publicDemo} from '@/lib/public-demo';
export default function Welcome(){return <main className="welcome">
 <header className="welcome-nav"><a href="/" aria-label="BizProof 홈"><BizProofLogo/></a><nav aria-label="접속 페이지 메뉴"><a href="/guide">이용자 가이드 ↗</a><a href="/admin/login">관리자 접속</a></nav></header>
 <section className="welcome-hero"><div className="welcome-copy"><span className="welcome-kicker"><i/> BUSINESS TRUST, SIMPLIFIED</span><h1>한 번 증명하고,<br/><em>더 많은 기회</em>로.</h1><p className="welcome-lead">매번 같은 서류를 준비하는 대신,<br/>하나의 기업 자격으로 구매사 등록과<br className="welcome-mobile"/> 지원사업 조건을 확인하세요.</p><EntryForm demo={publicDemo()}/><a className="welcome-guide-link" href="/guide#guide-public-demo">처음이신가요? 5분 시연 따라 하기 →</a><div className="welcome-details"><span>회원가입 없이 체험</span><span>방문자별 독립 공간</span><span>가상 기업 데이터</span></div></div>
 <div className="welcome-visual" aria-label="하나의 기업 자격을 두 기관에 재사용하는 흐름"><div className="welcome-orbit"/><div className="welcome-pass"><div className="welcome-pass-top"><BizProofLogo animated compact/><span>BUSINESS CREDENTIAL<br/><b>기업 자격 카드</b></span><small>DEMO</small></div><div className="welcome-company">한빛 테크놀로지<span>설명을 위한 가상 기업</span></div><div className="welcome-pass-rule"/><div className="welcome-pass-bottom"><span>원본 정보 대신<br/><b>필요한 조건만 확인</b></span><span className="welcome-verified">✓ 서명 기반 시연</span></div></div><div className="welcome-destinations"><div><span>01 / PROCUREMENT</span><b>구매사 등록</b><small>요청 조건 확인 ✓</small></div><div><span>02 / OPPORTUNITY</span><b>지원사업 신청</b><small>같은 자격 재사용 ✓</small></div></div><p className="welcome-caption">ONE CREDENTIAL. TWO OPPORTUNITIES.</p></div></section>
 <section className="welcome-steps" aria-label="체험 순서">{[['01','가상 자격 준비','준비된 시연 데이터로 바로 시작하세요.'],['02','공유 내용 확인','받는 기관과 전달할 내용을 읽고 동의하세요.'],['03','결과 비교','충족·미충족과 취소 후 차단을 확인하세요.']].map(([n,t,d])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></article>)}</section>
 <footer className="welcome-footer"><p>공개 체험은 합성 데이터와 서버 전자서명을 사용합니다. 실제 기관 인증·사업 선정·블록체인 거래 완료를 의미하지 않습니다.<br/>체험 세션은 2시간 유지됩니다. 실제 개인정보나 기업 기밀은 입력하지 마세요.</p><a href="/privacy/analytics">방문 정보 안내</a></footer>
 </main>}
