import {familyMatches} from './credential-family';
import {z} from 'zod';
import {type State,type Authority,credentialPayload,statusOf} from './domain';
import {sign,verify} from './signatures';
export const authorityInput=z.object({credentialId:z.string(),holderUserId:z.string().trim().min(1).max(200).optional(),holder:z.string().trim().min(2).max(80),title:z.string().trim().min(2).max(80),scope:z.enum(['buyer','grant']),days:z.number().int().min(1).max(180)});
export function authorityPayload(a:Authority){return {...(a.holderUserId?{holderUserId:a.holderUserId}:{}),id:a.id,companyId:a.companyId,credentialId:a.credentialId,issuerId:a.issuerId,keyId:a.keyId,holder:a.holder,title:a.title,scope:a.scope,issuedAt:a.issuedAt,expiresAt:a.expiresAt,mode:a.mode};}
export async function checkAuthority(s:State,a:Authority,companyId:string,scope:string){const c=s.credentials.find(x=>x.id===a.credentialId),i=s.issuers.find(x=>x.id===a.issuerId),company=s.companies.find(x=>x.id===a.companyId);const key=i&&(a.keyId===i.keyId?i.publicKey:i.previousKeys.find(k=>k.keyId===a.keyId)?.publicKey);const ck=c&&i&&(c.keyId===i.keyId?i.publicKey:i.previousKeys.find(k=>k.keyId===c.keyId)?.publicKey);const checks=[{label:'기업 자격 스키마 연결',pass:!!c&&s.schemas.some(schema=>schema.id===c.schemaId)&&await familyMatches(s,c)},{label:'발급기관 신뢰',pass:i?.status==='active'},{label:'기업 자격 연결',pass:!!c&&c.companyId===a.companyId&&c.issuerId===a.issuerId&&statusOf(c)==='active'&&Date.parse(c.issuedAt)<=Date.now()&&Date.parse(c.expiresAt)>Date.parse(c.issuedAt)},{label:'기업 거래 상태',pass:!!company&&company.accountStatus!=='suspended'},{label:'기업 자격 서명',pass:!!c&&!!ck&&await verify(ck,credentialPayload(c),c.signature)},{label:'담당자 권한 서명',pass:!!key&&await verify(key,authorityPayload(a),a.signature)},{label:'권한 유효기간·취소 상태',pass:a.mode==='signed-demo'&&a.status==='active'&&Date.parse(a.issuedAt)<=Date.now()&&Date.parse(a.expiresAt)>Date.now()&&Date.parse(a.expiresAt)>Date.parse(a.issuedAt)&&!!c&&Date.parse(a.issuedAt)>=Date.parse(c.issuedAt)&&Date.parse(a.expiresAt)<=Date.parse(c.expiresAt)},{label:'요청 기업 일치',pass:a.companyId===companyId},{label:'업무 범위 일치',pass:a.scope===scope}];return {valid:checks.every(c=>c.pass),checks,chain:[{kind:'issuer',id:a.issuerId,label:i?.name??'알 수 없는 발급기관',keyId:a.keyId,status:i?.status??'missing'},{kind:'credential',id:a.credentialId,label:company?.name??'알 수 없는 기업',keyId:c?.keyId,status:c?statusOf(c):'missing'},{kind:'authority',id:a.id,label:a.holder+' · '+a.title,status:statusOf(a)}],checkedAt:new Date().toISOString(),mode:'signed-demo' as const,notice:'샌드박스 서명 검증입니다. 실제 개인 신원·재직·대표권 또는 GLEIF vLEI를 인증하지 않습니다.'};}
export async function issueAuthority(s:State,input:z.infer<typeof authorityInput>){const c=s.credentials.find(x=>x.id===input.credentialId),i=c&&s.issuers.find(x=>x.id===c.issuerId);if(!c||!i||!s.schemas.some(schema=>schema.id===c.schemaId)||Date.parse(c.issuedAt)>Date.now()||!await familyMatches(s,c)||statusOf(c)!=='active'||i.status!=='active')throw Error('유효한 기업 자격과 신뢰 발급기관이 필요합니다.');if(s.companies.find(x=>x.id===c.companyId)?.accountStatus==='suspended')throw Error('거래 중지 기업에는 권한을 발급할 수 없습니다.');const key=c.keyId===i.keyId?i.publicKey:i.previousKeys.find(k=>k.keyId===c.keyId)?.publicKey;if(!key||!await verify(key,credentialPayload(c),c.signature))throw Error('기업 자격 서명이 유효하지 않습니다.');const a:Authority={...(input.holderUserId?{holderUserId:input.holderUserId}:{}),id:'authority-'+crypto.randomUUID(),companyId:c.companyId,credentialId:c.id,issuerId:i.id,keyId:i.keyId,holder:input.holder,title:input.title,scope:input.scope,issuedAt:new Date().toISOString(),expiresAt:new Date(Math.min(Date.now()+input.days*864e5,Date.parse(c.expiresAt))).toISOString(),status:'active',signature:'',mode:'signed-demo'};a.signature=await sign(i.privateKey,authorityPayload(a));(s.authorities??=[]).push(a);return a;}



