import {remoteCredentialStatus,verifyRemoteOriginal} from './remote-issuer';
import {defineCredentialFamily,assertCredentialFamilyDefinition} from '@midnight-ntwrk/credential-model';
import {type CredentialSchema,type Credential,type State,credentialPayload,statusOf} from './domain';
import {digest,verify} from './signatures';
// The published rc3 API differs from main; use only the installed public contract.
export function familyFor(schema:CredentialSchema){const codec={mediaType:'application/vnd.bizproof.envelope+json',encode:(value:unknown)=>JSON.stringify(value),decode:(value:string)=>JSON.parse(value) as unknown};const definition=defineCredentialFamily<unknown,unknown,string,string>({id:'bizproof.enterprise',version:'2.0.0',schema:{id:schema.id,version:`${schema.version}.0.0`,credentialTypes:['BizProofBusinessCredential'],claims:schema.fields.map(f=>({id:f.key,path:['claims',f.key] as [string,...string[]],disclosure:'predicate-only' as const,required:true,valueType:f.type}))},capabilities:[{id:'bizproof-ed25519-v2',kind:'proof',version:'2.0.0',required:true},{id:'bizproof-server-status',kind:'status',version:'1.0.0',required:true},{id:'bizproof-request-result',kind:'presentation',version:'2.0.0',required:true}],artifacts:[],composition:{formatVersion:1,packages:[{name:'@midnight-ntwrk/credential-model',version:'0.1.0-rc3'}]},credentialCodec:codec,presentationCodec:codec});assertCredentialFamilyDefinition(definition);const {credentialCodec,presentationCodec,...metadata}=definition;return {...metadata,codecs:{credential:credentialCodec.mediaType,presentation:presentationCodec.mediaType}};}export async function schemaBinding(schema:CredentialSchema){const family=familyFor(schema);return {familyId:family.id,familyVersion:family.version,schemaVersion:family.schema.version,descriptorHash:await digest(family)};}
export async function familyMatches(s:State,c:Credential){if(c.proofVersion===3)return c.schemaId==='business-v1'&&!!c.remoteBinding;if(c.proofVersion!==2)return true;const schema=s.schemas.find(x=>x.id===c.schemaId);return !!schema&&!!c.familyBinding&&await digest(c.familyBinding)===await digest(await schemaBinding(schema));}
export async function inspectCredential(s:State,c:Credential){let remoteValid=true,remoteActive=true;if(c.proofVersion===3){try{await verifyRemoteOriginal({...c,status:'active'},c.remoteBinding?.scope??'',c.remoteBinding?.requestId??'');const status=await remoteCredentialStatus(c,s.credentialReceipts?.find(r=>r.credentialId===c.id)?.statusRevision);remoteActive=status.body.status==='active';}catch{remoteValid=false;remoteActive=false;}}const i=s.issuers.find(x=>x.id===c.issuerId);const key=i&&(c.keyId===i.keyId?i.publicKey:i.previousKeys.find(k=>k.keyId===c.keyId)?.publicKey);const checks=[{id:'signature',label:'원본 전체에 대한 발급 서명',pass:remoteValid&&!!key&&await verify(key,credentialPayload(c),c.signature)},{id:'trust',label:'등록 발급기관의 현재 신뢰',pass:i?.status==='active'&&(c.proofVersion===3?i.kind==='remote':i.kind!=='remote')},{id:'status',label:'현재 취소·만료 상태',pass:remoteActive&&statusOf(c)==='active'},{id:'time',label:'발급·만료 시간 순서',pass:Date.parse(c.issuedAt)<=Date.now()&&Date.parse(c.expiresAt)>Date.parse(c.issuedAt)},{id:'schema',label:'스키마 존재 및 정확한 버전 연결',pass:!!s.schemas.find(x=>x.id===c.schemaId)&&await familyMatches(s,c)},{id:'subject',label:'보유 기업 연결',pass:!!s.companies.find(x=>x.id===c.companyId)}];return {credentialId:c.id,valid:checks.every(c=>c.pass),checks,checkedAt:new Date().toISOString(),proofFormat:c.proofVersion===3?'bizproof-remote-v3':c.proofVersion===2?'bizproof-context-v2':'bizproof-legacy-v1',domainSeparated:c.proofVersion===2||c.proofVersion===3,modelPackage:'@midnight-ntwrk/credential-model@0.1.0-rc3',notice:'공식 패키지는 스키마 메타데이터를 검증합니다. 서명은 BizProof 전용 Ed25519이며 Midnight 코어 VC/VP proof 또는 W3C 적합성 인증이 아닙니다.'};}


