import type {ScanRecord} from './malware-scan';
import type {VerifierSession} from './waltid-verifier';
import { z } from 'zod';
export type Role = 'admin'|'issuer'|'company'|'buyer'|'grant';
export const roleLabels: Record<Role,string> = {admin:'워크스페이스 관리자',issuer:'자격 발급기관',company:'신청 기업',buyer:'구매사 담당자',grant:'지원기관 담당자'};
export type Company = {id:string;name:string;registration:string;industry:string;region:string;contact:string;createdAt:string;updatedAt?:string;accountStatus?:"active"|"suspended";profile?:{description:string;website:string;products:string;serviceRegions:string;visibility:"private"|"requested"|"connected"|"all"};profileAvailable?:boolean;profileVisibility?:"private"|"requested"|"connected"|"all"};
export type Claims = {revenue:number;foundedOn:string;region:string;certified:boolean};
type IssuerBase = {id:string;name:string;did:string;status:'active'|'suspended';keyId:string;publicKey:JsonWebKey;previousKeys:{keyId:string;publicKey:JsonWebKey}[];createdAt:string};
export type Issuer = IssuerBase & ({kind?:'local';privateKey:JsonWebKey}|{kind:'remote';privateKey?:never});
export type CredentialSource = {kind:"synthetic"|"document-review";reference:string;period:string;method:string;reviewer:string;reviewedAt:string;documents:{id:string;name:string;sha256:string}[];notice:string};
export type DemoJourney = {id:string;companyId:string;credentialId:string;requestIds:Record<"buyer"|"grant"|"negative"|"revoked",string>;createdAt:string;revocationCheck?:{at:string;blocked:boolean}};
export type Credential = {source?:CredentialSource;proofVersion?:2|3;remoteBinding?:{requestId:string;scope:string;identitySessionId:string;identityMode:'simulated';documentHash:string};familyBinding?:{familyId:string;familyVersion:string;schemaVersion:string;descriptorHash:string};id:string;companyId:string;issuerId:string;schemaId:string;claims:Claims;issuedAt:string;expiresAt:string;keyId:string;signature:string;status:'active'|'revoked';revokedAt?:string;reason?:string;supersedes?:string};
export type Policy = {id:string;name:string;audience:string;kind:'buyer'|'grant';version:number;minRevenue:number|null;maxRevenue:number|null;maxAgeMonths:number|null;region:string|null;requireCertification:boolean;issuerIds:string[];createdAt:string;status:'active'|'archived'};
export type VerificationRequest = {id:string;companyId:string;policyId:string;policyHash:string;policy:Policy;nonce:string;status:'pending'|'submitted'|'verified'|'rejected'|'cancelled'|'expired';expiresAt:string;createdAt:string};
export type Presentation = {proofVersion?:2|3;signerKind?:'platform';schemaId?:string;credentialDigest?:string;id:string;requestId:string;credentialId:string;companyId:string;policyHash:string;nonce:string;audience:string;issuedAt:string;expiresAt:string;eligible:boolean;checks:{label:string;pass:boolean}[];signature:string;issuerId:string;keyId:string;mode:'signed-demo';submittedBy?:string;authorityId?:string;verifiedAt?:string};
export type Audit = {id:string;actor?:string;at:string;role:Role;action:string;target:string;detail:string};
export type CredentialSchema = {id:string;name:string;version:number;description:string;fields:{key:string;label:string;type:string;private:boolean}[];createdAt:string};
export type Connection = {id:string;companyId:string;organization:string;kind:'buyer'|'grant';status:'pending'|'accepted'|'declined';createdAt:string};
export type Evidence = {scan?:ScanRecord;sha256?:string;id:string;companyId:string;name:string;mime:string;size:number;key:string;createdAt:string};
export type Authority = {holderUserId?:string;id:string;companyId:string;credentialId:string;issuerId:string;keyId:string;holder:string;title:string;scope:"buyer"|"grant";issuedAt:string;expiresAt:string;status:"active"|"revoked";signature:string;mode:"signed-demo";revokedAt?:string;reason?:string};
export type CredentialDraft = {id:string;companyId:string;issuerId:string;schemaId:string;claims:Claims;days:number;labels:string[];note:string;evidenceIds:string[];status:"draft"|"issued"|"archived";revision:number;createdAt:string;updatedAt:string;credentialId?:string};
export type CompactRun = {id:string;requestId:string;credentialId:string;policyHash:string;eligible:boolean;at:string;mode:"compact-local";networkConnected:false;proofGenerated:false;replayBlocked:true;sourceSignatureVerified:boolean;policyParity:boolean;compiler:string;runtime:string;notice:string};
export type WalletEntry = {credentialId:string;favorite:boolean;archived:boolean;category:string;updatedAt:string};
export type IssuerSnapshot = {id:string;issuerId:string;sequence:number;previousHash:string|null;stateHash:string;keyId:string;capturedAt:string;credentialCount:number;revokedCount:number;mode:"local-signed-state";signature:string};
export type WorkflowEvent = {at:string;actor:string;status:string;reason:string;evidenceIds?:string[]};
export type AccessRequest = {approval?:{actor:string;owner:string;companyId:string;requester:string;newCompany:boolean;at:string};id:string;kind:'company'|'authority';actor:string;holder:string;title:string;reason:string;createdAt:string;status:'pending'|'provisioning'|'approved'|'rejected'|'cancelled';companyId?:string;policyId?:string;credentialId?:string;authorityId?:string;companyData?:Omit<Company,'id'|'createdAt'>;decision?:string;history:WorkflowEvent[]};
export type IssuanceRequest = {id:string;companyId:string;policyId:string;issuerId:string;evidenceIds:string[];actor:string;createdAt:string;status:"pending"|"issued"|"needs_changes"|"rejected"|"cancelled";revision?:number;reason?:string;history?:WorkflowEvent[];credentialId?:string};
export type PreparedDemo = {version:2;preparedAt:string;companyId:string;credentialId:string;policyIds:string[]};
export type State = {credentialReceipts?:{credentialId:string;requestId:string;digest:string;receivedAt:string;statusRevision:number}[];preparedDemo?:PreparedDemo;accessRequests?:AccessRequest[];policyAutomation?:{policyId:string;enabled:boolean;actor:string;at:string}[];applicationSubmissions?:{key:string;actor:string;companyId:string;policyId:string;previewHash:string;requestId:string;presentationId:string}[];issuanceRequests?:IssuanceRequest[];verifierSessions?:VerifierSession[];demoJourneys?:DemoJourney[];issuerSnapshots?:IssuerSnapshot[];walletEntries?:WalletEntry[];compactRuns?:CompactRun[];drafts?:CredentialDraft[];authorities?:Authority[];companies:Company[];issuers:Issuer[];credentials:Credential[];policies:Policy[];requests:VerificationRequest[];presentations:Presentation[];audit:Audit[];schemas:CredentialSchema[];connections:Connection[];evidence:Evidence[];settings:{name:string};};
export type ViewState = Omit<State,'issuers'|'credentials'|'verifierSessions'> & {issuers:Omit<Issuer,'privateKey'>[];credentials:(Omit<Credential,'claims'|'signature'> & {claims?:Claims;signature?:string})[];publicDemo?:boolean;role:Role;workspaceKind?:"personal"|"shared";organization?:string|null;allowedRoles:Role[];authMode:"demo"|"keycloak";actor?:string;user:string;version:number;engine:{mode:string;connected:boolean;message:string}};
const safeText=z.string().trim().min(1).max(160);
export const companyInput=z.object({name:safeText,registration:z.string().trim().min(3).max(40),industry:safeText,region:safeText,contact:z.string().email().max(180)});
export const claimsInput=z.object({revenue:z.number().int().min(0).max(1_000_000_000_000),foundedOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&Date.parse(v)<=Date.now(),'설립일을 확인하세요'),region:safeText,certified:z.boolean()});
export const policyInput=z.object({name:safeText,audience:safeText,kind:z.enum(['buyer','grant']),minRevenue:z.number().int().min(0).max(1e12).nullable(),maxRevenue:z.number().int().min(0).max(1e12).nullable(),maxAgeMonths:z.number().int().min(0).max(1200).nullable(),region:safeText.nullable(),requireCertification:z.boolean(),issuerIds:z.array(z.string().min(1)).min(1).max(20)}).refine(p=>p.minRevenue===null||p.maxRevenue===null||p.minRevenue<=p.maxRevenue,'최소 매출은 최대 매출보다 클 수 없습니다');
export function canonical(value:unknown):string {if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';const o=value as Record<string,unknown>;return '{'+Object.keys(o).sort().filter(k=>o[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonical(o[k])).join(',')+'}';}
export function credentialPayload(c:Credential){const body={...(c.source?{source:c.source}:{}),id:c.id,companyId:c.companyId,issuerId:c.issuerId,schemaId:c.schemaId,claims:c.claims,issuedAt:c.issuedAt,expiresAt:c.expiresAt,keyId:c.keyId};return c.proofVersion===3?{context:'bizproof:credential:issuance:v3',proofVersion:3,remoteBinding:c.remoteBinding,body}:c.proofVersion===2?{context:"bizproof:credential:issuance:v2",proofVersion:2,familyBinding:c.familyBinding,body}:body;}
export function presentationPayload(p:Presentation){const payload=Object.fromEntries(Object.entries(p).filter(([key])=>!['signature','verifiedAt'].includes(key)));return p.proofVersion===3?{context:'bizproof:platform:processing-receipt:v3',body:payload}:p.proofVersion===2?{context:"bizproof:credential:presentation:v2",body:payload}:payload;}
export function evaluate(claims:Claims,policy:Policy,at=new Date()){const checks:{label:string;pass:boolean}[]=[];if(policy.minRevenue!==null)checks.push({label:`매출 ${policy.minRevenue.toLocaleString('ko-KR')}원 이상`,pass:claims.revenue>=policy.minRevenue});if(policy.maxRevenue!==null)checks.push({label:`매출 ${policy.maxRevenue.toLocaleString('ko-KR')}원 이하`,pass:claims.revenue<=policy.maxRevenue});if(policy.maxAgeMonths!==null){const cutoff=new Date(claims.foundedOn);cutoff.setUTCMonth(cutoff.getUTCMonth()+policy.maxAgeMonths);checks.push({label:`업력 ${policy.maxAgeMonths}개월 이내`,pass:at.getTime()<=cutoff.getTime()});}if(policy.region)checks.push({label:`소재지 ${policy.region}`,pass:claims.region===policy.region});if(policy.requireCertification)checks.push({label:'인증 보유',pass:claims.certified});return {eligible:checks.every(x=>x.pass),checks};}
export function statusOf(c:{status:string;expiresAt:string}){return c.status==='revoked'?'revoked':Date.parse(c.expiresAt)<=Date.now()?'expired':c.status;}










