import {z} from 'zod';
import {binding} from './store';
import {digest} from './signatures';
import {PortOneIdentityProvider,portOneConfigSchema,IdentityProviderError,type IdentityIntent,type IdentityEvidence} from './identity-provider';
type Session={intent:IdentityIntent;status:'pending'|'verified'|'failed'|'cancelled'|'consumed';evidence?:IdentityEvidence};
const failure=(message:string,status=403):never=>{throw new IdentityProviderError(status,message);};
export function requireIdentityPilot(actor:string,authMode:string){if(process.env.BIZPROOF_PUBLIC_DEMO==='true'||process.env.BIZPROOF_IDENTITY_PILOT!=='true'||authMode!=='keycloak'||!(process.env.BIZPROOF_IDENTITY_PILOT_USERS??'').split(',').includes(actor))failure('본인확인은 별도 승인된 파일럿 계정에서만 제공됩니다.');}
function provider(){const config=process.env.BIZPROOF_PORTONE_CONFIG;if(!config)return failure('인증기관 테스트 계정과 채널 설정이 필요합니다.',503);return new PortOneIdentityProvider(portOneConfigSchema.parse(JSON.parse(config)));}
async function table(){await binding().prepare('CREATE TABLE IF NOT EXISTS identity_pilot_sessions(id TEXT PRIMARY KEY,actor TEXT NOT NULL,created INTEGER NOT NULL,expires INTEGER NOT NULL,payload TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0)').run();await binding().prepare('DELETE FROM identity_pilot_sessions WHERE expires<?').bind(Date.now()-86400000).run();}
function summary(s:Session){return {id:s.intent.id,status:s.intent.expiresAt<=Date.now()&&s.status!=='consumed'?'expired':s.status,expiresAt:s.intent.expiresAt,documentHash:s.intent.documentHash,provider:'portone-v2',mode:s.evidence?.mode,documentSigned:false};}
export async function startIdentitySession(actor:string,input:{companyId:string;documentHash:string}){provider();await table();const now=Date.now(),intent:IdentityIntent={id:crypto.randomUUID(),actor,...input,purpose:'business-issuance',createdAt:now,expiresAt:now+600000,nonce:crypto.randomUUID()},session:Session={intent,status:'pending'};
 const result=await binding().prepare('INSERT INTO identity_pilot_sessions(id,actor,created,expires,payload) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM identity_pilot_sessions WHERE actor=? AND created>?)<5').bind(intent.id,actor,now,intent.expiresAt,JSON.stringify(session),actor,now-3600000).run();if(result.meta.changes!==1)return failure('인증 요청이 많습니다. 잠시 후 다시 시도하세요.',429);return {...summary(session),launch:await provider().start(intent)};}
async function load(actor:string,id:string){await table();const row=await binding().prepare('SELECT payload,revision FROM identity_pilot_sessions WHERE actor=? AND id=?').bind(actor,id).first<{payload:string;revision:number}>();if(!row)return failure('인증 요청을 찾을 수 없습니다.',404);return {session:JSON.parse(row.payload) as Session,revision:row.revision};}
async function save(s:Session,revision:number){const r=await binding().prepare('UPDATE identity_pilot_sessions SET payload=?,revision=revision+1 WHERE id=? AND actor=? AND revision=?').bind(JSON.stringify(s),s.intent.id,s.intent.actor,revision).run();if(r.meta.changes!==1)failure('인증 상태가 변경되었습니다. 다시 확인하세요.',409);}
export async function checkIdentitySession(actor:string,id:string,cancel=false){const {session:s,revision}=await load(actor,id);if(s.status!=='pending'||s.intent.expiresAt<=Date.now())return summary(s);if(cancel){s.status='cancelled';await save(s,revision);return summary(s);}const result=await provider().verify(s.intent);if('status' in result){if(result.status==='failed'){s.status='failed';await save(s,revision);}}else{s.status='verified';s.evidence=result;await save(s,revision);}return summary(s);}
// Internal use only: company authority and provider mode must be decided separately by the pilot issuer.
export async function consumeIdentitySession(actor:string,id:string,expected:{companyId:string;documentHash:string;mode:'live'|'provider-test'}){const {session:s,revision}=await load(actor,id);if(s.status!=='verified'||s.intent.expiresAt<=Date.now()||s.intent.companyId!==expected.companyId||s.intent.documentHash!==expected.documentHash||s.evidence?.mode!==expected.mode||s.evidence.intentHash!==await digest(s.intent))return failure('해당 신청에 유효한 본인확인 증거가 없습니다.',422);s.status='consumed';await save(s,revision);return s.evidence;}
export const identitySessionCommand=z.discriminatedUnion('action',[z.object({action:z.literal('start'),companyId:z.string().min(1).max(150),documentHash:z.string().regex(/^[a-f0-9]{64}$/),consent:z.literal(true)}).strict(),z.object({action:z.enum(['check','cancel']),id:z.string().uuid()}).strict()]);
