import type {ProgramProfile,Rule,DocumentRequirement,DocumentType} from './program-types';
const checked='2026-09-25',limit=20*1024*1024;
const doc=(type:DocumentType,label:string,extra:Partial<DocumentRequirement>={}):DocumentRequirement=>({type,label,maxBytes:limit,...extra});
const manual=(id:string,label:string,reason:string):Rule=>({id,label,op:'manual',reason});
const common={version:'2026-09-25.1',sourceCheckedAt:checked,sourceDigest:null,sourceStatus:'public-reference',externalSubmission:'not-connected'} as const;
const registered:Rule={id:'registered',label:'사업자등록 확인',op:'compare',fact:'registered',comparison:'eq',value:true};
const history:Rule[]=[{id:'hub-history',label:'과거·현재 허브 입주 이력',op:'compare',fact:'noHubHistory',comparison:'eq',value:true},{id:'space-history',label:'중복 공간지원 여부',op:'compare',fact:'noDuplicateSpace',comparison:'eq',value:true}];
function agePaths(referenceDate:string,comparison:'lt'|'lte'):Rule{return {id:'age',label:'일반 또는 신산업 업력 조건',op:'any',rules:[{id:'general-age',label:`일반기업 7년 ${comparison==='lt'?'미만':'이내'}`,op:'age',referenceDate,months:84,comparison},{id:'new-industry-path',label:'신산업 인정 및 10년 이내',op:'all',rules:[{id:'new-industry',label:'신산업 인정 근거',op:'compare',fact:'newIndustry',comparison:'eq',value:true},{id:'extended-age',label:'10년 이내',op:'age',referenceDate,months:120,comparison:'lte'}]}]};}
export const programProfiles:ProgramProfile[]=[
 {...common,id:'seongsu-2026-h2',name:'서울창업허브 성수 · 2026 하반기',organization:'서울창업허브 성수',kind:'grant',category:'입주기업',sourceUrl:'https://www.startup-plus.kr/project/PRJ007420',window:{opens:'2026-09-03T09:00:00+09:00',closes:'2026-09-28T17:00:00+09:00'},contact:'공고 내 입주 모집 담당: 02-2115-0545',rules:[registered,agePaths('2026-09-03','lt'),...history,manual('move','선정 후 이전 의사 및 중복 수혜 예외','현재 소재지만으로 탈락시키지 않습니다. 선정 후 이전 및 공간지원 종료 조건은 담당자 확인이 필요합니다.'),manual('selection','입주 적합성·사업성 평가','기관의 최종 평가를 자동 판정하지 않습니다.'),{id:'women',label:'여성기업 가점 자료',op:'compare',fact:'womenBusiness',comparison:'eq',value:true,bonus:true}],documents:[doc('registration','사업자등록증'),doc('ir','IR 자료',{maxPages:10}),doc('women-business','여성기업확인서',{bonus:true})],notes:['일반 경로와 신산업 예외를 구분합니다. 신산업 인정과 수혜 이력은 근거가 없으면 미확인입니다.','공개 공고를 바탕으로 만든 참고 프로필이며 공식 접수·선정 결과가 아닙니다.']},
 {...common,id:'ai-hub-2026-leading',name:'서울 AI 허브 · 2026 1차 선도기업',organization:'서울 AI 허브',kind:'grant',category:'선도기업 · 과거 공고 재현',sourceUrl:'https://www.startup-plus.kr/project/PRJ006524',window:{opens:'2026-03-09T13:00:00+09:00',closes:'2026-03-31T23:59:00+09:00'},contact:'공고 내 입주 모집 담당: 02-2135-6814',rules:[registered,manual('age-reference','7년 이내 업력의 정확한 기준일 확인','기준일을 임의로 추정하지 않습니다. 원문 및 담당자 확인 후 별도 회차 버전을 발행해야 합니다.'),{id:'finance-or',label:'2025 매출 20억원 또는 누적 투자 30억원',op:'any',rules:[{id:'revenue',label:'2025년 매출 20억원 이상',op:'compare',fact:'revenueKrw',comparison:'gte',value:2_000_000_000,fiscalYear:2025},{id:'investment',label:'누적 투자 30억원 이상',op:'compare',fact:'investmentKrw',comparison:'gte',value:3_000_000_000}]},{id:'residents',label:'입주 예정 상주 인원 15명 이상',op:'compare',fact:'plannedResidents',comparison:'gte',value:15},manual('ai-fit','AI 기술 적합성·투자 인정 범위 검토','사업 유형, 투자 인정 시점과 상주 계획을 기관 담당자가 검토해야 합니다.')],documents:[doc('registration','사업자등록증'),doc('ir','사업·기술 소개'),doc('residents','상주 인원 계획 및 근거')],notes:['종료된 회차이며 현재 신청을 접수하지 않습니다.','이 프로필의 재무·인력 조건을 신규기업 유형에 적용하지 않습니다.','재무 조건은 회계연도가 일치하는 매출 자격 또는 투자 자격으로 각각 증명합니다.']},
 {...common,id:'gongdeok-2026-h1',name:'서울창업허브 공덕 · 2026 상반기',organization:'서울창업허브 공덕',kind:'grant',category:'입주기업 · 과거 공고 재현',sourceUrl:'https://hubgongdeok.startup-plus.kr/project/PRJ006640',window:{opens:'2026-04-01T12:00:00+09:00',closes:'2026-04-20T15:00:00+09:00'},contact:'공고 내 입주 모집 담당: 02-2115-2035',rules:[registered,agePaths('2026-06-10','lte'),...history,{id:'national-tax',label:'국세 납세 사실 확인',op:'compare',fact:'nationalTaxClear',comparison:'eq',value:true},{id:'local-tax',label:'지방세 납세 사실 확인',op:'compare',fact:'localTaxClear',comparison:'eq',value:true},manual('move','계약 후 30일 이내 본점·지점 이전','현재 지역 제한과 이전 약정을 구분하며 이행 여부는 담당자 확인 사항입니다.'),manual('selection','입주·서류 예외 심사','재무제표 미발급 시 사업자등록증, 법인 납세증명 미발급 시 대표자 증빙 등 공고상 대체서류를 별도로 검토합니다.')],documents:[doc('registration','사업자등록증'),doc('ir','IR 자료'),doc('finance','재무제표',{alternative:'registration',exception:'재무제표 미발급 사유와 대체서류 인정 여부 확인'}),doc('insurance','4대보험 가입 자료'),doc('national-tax','국세 납세증명'),doc('local-tax','지방세 납세증명'),doc('application','사업계획·신청서'),doc('consent','공고 지정 동의서')],notes:['업력은 입주 예정일 2026-06-10 기준이며 현재 자격의 만료 검사는 현재 시각으로 수행합니다.','대체서류가 있다고 자동으로 체납 없음 또는 재무 실적을 인정하지 않습니다.']},
 {...common,id:'hyundai-steel-technical',name:'현대제철 · 기술제안 준비',organization:'현대제철',kind:'buyer',category:'신규 기술제안 · 구매사 등록과 별개',sourceUrl:'https://poinfo.hyundai-steel.com/sub/suggest',contact:'공개 구매 기획 문의: 031-510-2870 (문의 전 원문 재확인)',rules:[registered,manual('category','제안 품목·구매 담당 기능 분류','기술·설비·자재 유형을 확인하고 공식 제안 경로로 전달할 준비를 합니다.'),manual('technical','공장 적용성·기술 검토','등록 여부와 별개인 기술제안입니다. 구매사 등록, 공장 시험, 계약 승인을 대신하지 않습니다.')],documents:[doc('registration','기업 식별 자료'),doc('technical-proposal','기술제안서')],notes:['모든 제안에 과거 특정 등록 공고의 점수 기준을 일괄 적용하지 않습니다.','실제 담당자 배정·공장 시험·거래 등록은 현대제철의 절차로 진행해야 합니다.']},
 {...common,id:'posco-sourcing',name:'POSCO · 소싱그룹 등록 준비',organization:'POSCO',kind:'buyer',category:'소싱그룹별 공급사 심사',sourceUrl:'https://sustainability.posco.com/S91/S91F10/kor/cmspage.do?mmcd=1750321915001548',contact:'공개 구매 문의: 054-220-5000 (품목별 경로 재확인)',rules:[registered,manual('category','소싱그룹·품목별 등록 기준','단일 공통 신용등급을 만들지 않습니다. 선택한 소싱그룹의 현행 기준이 필요합니다.'),manual('credit','신용·재무·공급 역량 검토','평가기관·등급 체계·평가일을 확인한 후 해당 품목의 기준으로 검토합니다.'),manual('esg','윤리·ESG·공급사 행동규범 확인','문서 확인과 실제 공급사 심사는 담당자가 수행합니다.')],documents:[doc('registration','기업 식별 자료'),doc('credit','신용평가 및 재무 자료'),doc('technical-proposal','공급 역량·품목 자료'),doc('esg','ESG·행동규범 자료')],notes:['공개 지속가능 공급망 안내를 참고한 준비 체크리스트입니다. 실제 소싱그룹 접수 규격은 미확정입니다.']},
 {...common,id:'sk-hynix-supplier',name:'SK하이닉스 · 신규 협력사 준비',organization:'SK하이닉스',kind:'buyer',category:'품목별 구매·TSC 검토',sourceUrl:'https://gpis.skhynix.com/ui/sp/eportal/pc/bp_regi_info.html',contact:'GPIS 공개 신규 협력사 안내의 품목별 문의 경로',rules:[registered,manual('category','품목 분류·담당 조직 확인','공개 품목 안내에서 해당 구매·TSC 경로를 확인합니다. 확인되지 않은 부서명이나 담당자를 생성하지 않습니다.'),manual('supplier-review','등록 정보·심사 요청·구매/TSC 심사','BizProof의 준비 완료를 공식 협력사 등록 완료로 표시하지 않습니다.')],documents:[doc('registration','기업 식별 자료'),doc('technical-proposal','품목·공급 역량 자료')],notes:['공식 GPIS 입력·심사와 내부 서류 준비는 별도 단계입니다.','공개 등록 안내를 참고하며 내부 평가 기준과 API는 확보되지 않았습니다.']}
];
export function findProgram(id:string){return programProfiles.find(p=>p.id===id);}
export function programWindow(p:ProgramProfile,now=new Date()):'open'|'closed'|'upcoming'|'reference'{return !p.window?'reference':now.getTime()<Date.parse(p.window.opens)?'upcoming':now.getTime()>Date.parse(p.window.closes)?'closed':'open';}
