import {programOriginalSchema} from '../contracts/sdk/program-source';
import {z} from 'zod';
import {binding,readState} from './store';
import {digest,sign,verify} from './signatures';
import {platformKey} from './processing-signature';
import {findProgram} from './program-catalog';
import {precheckProgram} from './program-rules';
import {applicationReceiptPayload,ProgramError} from './program-service';
import {readDocument} from './program-http';
import {jobEventSchema,jobReceiptSchema,type JobReceipt,type JobEvent} from '../contracts/sdk/proof-job-protocol';
import {deriveProgramBinding,executionSourceSchema,verifyProgramExecution,programTaskSchema,programVerificationSchema,type ProgramBinding} from '../contracts/sdk/program-execution';
import {publicSigningKey,verifySigned} from '../contracts/sdk/issued-source';
export type ProgramProofJob={id:string;owner:string;actor:string;applicationId:string;profileId:string;name:string;profileHash:string;fingerprint:string;sourceDigest:string;status:'awaiting_approval'|'queued'|'running'|'awaiting_verification'|'confirmed'|'needs_attention'|'blocked'|'cancelled';createdAt:string;issuedAt:number;deadline:number;revision:number;approvedBy?:string;worker?:string;lease?:string;leaseExpiresAt?:number;target?:{contractAddress:string;holder:string};chainBinding?:ProgramBinding;receipts:JobReceipt[];events:(JobEvent&{at:string})[];challenge?:string;verification?:z.infer<typeof programVerificationSchema>;reason?:string};
function fail(message:string,status=409):never{throw new ProgramError(message,status);}
async function table(){await binding().prepare('CREATE TABLE IF NOT EXISTS program_proof_jobs(id TEXT PRIMARY KEY,owner TEXT NOT NULL,application_id TEXT NOT NULL,created TEXT NOT NULL,payload TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0)').run();await binding().prepare('CREATE INDEX IF NOT EXISTS program_proof_owner ON program_proof_jobs(owner,created)').run();}
export async function getProgramJob(id:string){await table();const r=await binding().prepare('SELECT payload,revision FROM program_proof_jobs WHERE id=?').bind(id).first<{payload:string;revision:number}>();if(!r)fail('신규 사례 체인 작업을 찾을 수 없습니다.',404);return {...JSON.parse(r.payload),revision:r.revision} as ProgramProofJob;}
export async function listProgramJobs(owner?:string){await table();const query=owner?binding().prepare('SELECT payload,revision FROM program_proof_jobs WHERE owner=? ORDER BY created DESC LIMIT 12').bind(owner):binding().prepare('SELECT payload,revision FROM program_proof_jobs ORDER BY created DESC LIMIT 100');const rows=await query.all<{payload:string;revision:number}>();return rows.results.map(r=>({...JSON.parse(r.payload),revision:r.revision}) as ProgramProofJob);}
async function save(j:ProgramProofJob){const r=await binding().prepare('UPDATE program_proof_jobs SET payload=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(j),j.id,j.revision).run();if(r.meta.changes!==1)fail('상태가 변경되었습니다. 다시 조회하세요.');j.revision++;return j;}
async function original(owner:string,actor:string,applicationId:string){
 const {state}=await readState(owner),data=state.programData,a=data?.applications.find(v=>v.id===applicationId),company=state.companies.find(c=>c.id===a?.companyId),p=findProgram(a?.profile.id??'');
 if(!data||!a||!company||!p||a.actor!==actor||a.mode!=='synthetic'||!/^demo-[a-f0-9-]{36}$/.test(owner))fail('신청 당사자의 합성 시연만 실행할 수 있습니다.',403);
 if(await digest(p)!==a.precheck.profileHash||await digest(a.profile)!==a.precheck.profileHash||!await verify(data.receiptKey.publicKey,applicationReceiptPayload(a),a.receipt.signature))fail('신청·공고 서명이 변경되었습니다.');
 const verified=new Set<string>();for(const reference of a.precheck.documents){const d=data.documents.find(v=>v.id===reference.id&&v.companyId===company.id);if(!d||d.sha256!==reference.sha256)fail('증빙 원본이 변경되었습니다.');await readDocument(owner,d);verified.add(d.id);}
 const precheck=await precheckProgram({data,company,profile:p,verifiedDocuments:verified});if(precheck.fingerprint!==a.precheck.fingerprint)fail('원본 자격·접수 기간·서류 상태가 변경되었습니다. 새 준비 기록이 필요합니다.');
 const originals=data.credentials.filter(c=>precheck.credentialDigests.some(v=>v.id===c.id));if(!originals.length)fail('서명된 기업 자격이 필요합니다.');
 return {a,company,precheck,originals,data};
}
async function current(j:ProgramProofJob,allowExpired=false){if(!allowExpired&&j.deadline<=Math.floor(Date.now()/1000))fail('체인 실행 동의 90분이 만료되었습니다.');const o=await original(j.owner,j.actor,j.applicationId);if(await digest(o.originals)!==j.sourceDigest||o.precheck.fingerprint!==j.fingerprint||o.precheck.profileHash!==j.profileHash||o.originals.some(c=>Date.parse(c.expiresAt)<j.deadline*1000))fail('승인 당시의 자격·자료가 변경되거나 만료되었습니다.');return o;}
async function source(j:ProgramProofJob,target=j.target){if(!target)fail('계약 연결이 필요합니다.');const o=await current(j),key=platformKey(),issuedAt=Math.floor(Date.now()/1000);
 const chain=await deriveProgramBinding({jobId:j.id,applicationId:j.applicationId,companyId:o.company.id,registration:o.company.registration,actor:j.actor,profileId:o.a.profile.id as ProgramBinding['profileId'],profileHash:j.profileHash,sourceDigest:j.sourceDigest,requestId:await digest({context:'program-request:2',jobId:j.id}),nonce:await digest({context:'program-nonce:2',jobId:j.id}),audience:await digest({context:'program-audience:2',profileId:j.profileId}),...target,issuedAt:j.issuedAt,deadline:j.deadline},o.originals.map(c=>programOriginalSchema.parse(c)));
 if(j.chainBinding&&await digest(j.chainBinding)!==await digest(chain))fail('기존 체인 요청 연결이 변경되었습니다.');
 const body=executionSourceSchema.shape.body.parse({context:'bizproof:program-execution-source:2',network:'undeployed',issuedAt,expiresAt:Math.min(issuedAt+300,j.deadline),binding:chain,originals:o.originals,documents:o.precheck.documents,issuers:o.data.issuers.filter(i=>o.originals.some(c=>c.issuerId===i.id)).map(i=>({issuerId:i.id,keyId:i.keyId,publicKey:publicSigningKey.parse({kty:i.publicKey.kty,crv:i.publicKey.crv,x:i.publicKey.x}),facts:i.facts,active:i.status==='active'})),trust:'platform-delegated-synthetic-issuers'});
 const result={body,signature:await sign(key.privateKey,body)};await verifyProgramExecution(result,{kty:key.publicKey.kty,crv:key.publicKey.crv,x:key.publicKey.x},{jobId:j.id,sourceDigest:j.sourceDigest,...target});return result;
}
export async function requestProgramJob(owner:string,actor:string,applicationId:string){
 const o=await original(owner,actor,applicationId),issuedAt=Math.floor(Date.now()/1000),jobs=await listProgramJobs(owner),existing=jobs.find(j=>j.applicationId===applicationId&&!['blocked','cancelled'].includes(j.status));if(existing)return existing;
 const j:ProgramProofJob={id:crypto.randomUUID(),owner,actor,applicationId,profileId:o.a.profile.id,name:o.a.profile.name,profileHash:o.precheck.profileHash,fingerprint:o.precheck.fingerprint,sourceDigest:await digest(o.originals),issuedAt,deadline:issuedAt+5400,createdAt:new Date().toISOString(),status:'awaiting_approval',revision:0,receipts:[],events:[]};
 // Validate exact coverage before requesting approval, using an unbound temporary target only in memory.
 await source(j,{contractAddress:'0'.repeat(64),holder:'1'.repeat(64)});
 const result=await binding().prepare("INSERT INTO program_proof_jobs(id,owner,application_id,created,payload,revision) SELECT ?,?,?,?,?,0 WHERE (SELECT COUNT(*) FROM program_proof_jobs WHERE owner=?)<12 AND NOT EXISTS(SELECT 1 FROM program_proof_jobs WHERE owner=? AND application_id=? AND json_extract(payload,'$.status') NOT IN ('blocked','cancelled'))").bind(j.id,owner,applicationId,j.createdAt,JSON.stringify(j),owner,owner,applicationId).run();if(result.meta.changes!==1)fail('이미 작업이 있거나 체험 공간의 작업 한도에 도달했습니다.');return j;
}
export async function refreshProgramJob(j:ProgramProofJob){if(['awaiting_approval','queued'].includes(j.status)&&j.deadline<=Math.floor(Date.now()/1000)){j.status='blocked';j.reason='실행 동의가 만료되었습니다. 새 동의로 요청하세요.';return save(j);}if(j.status==='running'&&(j.leaseExpiresAt??0)<Date.now()){j.status='needs_attention';j.reason='실행기 연결이 끊겼습니다. 거래 대조 후 복구해야 합니다.';return save(j);}return j;}
export async function controlProgramJob(id:string,action:'approve'|'cancel'|'resume',actor:string,revision:number,owner?:string){const j=await getProgramJob(id);if(owner&&j.owner!==owner)fail('작업을 찾을 수 없습니다.',404);if(j.revision!==revision)fail('최신 상태에서 다시 요청하세요.');if(action==='cancel'){if(!['awaiting_approval','queued'].includes(j.status))fail('실행 중인 거래는 취소할 수 없습니다.');j.status='cancelled';}else {if(owner)fail('서비스 관리자 승인이 필요합니다.',403);if(action==='approve'&&j.status!=='awaiting_approval'||action==='resume'&&(j.status!=='needs_attention'||!j.approvedBy))fail('승인·복구 가능한 상태가 아닙니다.');await current(j);j.status='queued';j.approvedBy=actor;j.leaseExpiresAt=0;delete j.reason;}return save(j);}
export function publicProgramJob(j:ProgramProofJob){return {id:j.id,applicationId:j.applicationId,name:j.name,profileId:j.profileId,status:j.status,revision:j.revision,createdAt:j.createdAt,deadline:j.deadline,network:'undeployed',coverage:j.chainBinding?.coverage,contractAddress:j.target?.contractAddress,receipts:j.receipts,events:j.events,verification:j.verification,reason:j.reason,officialReceipt:null,fullEligibility:false};}
export async function programWork(role:'executor'|'verifier'){const jobs=[];for(const raw of await listProgramJobs()){const j=await refreshProgramJob(raw);if(role==='executor'&&j.status==='queued'||role==='verifier'&&j.status==='awaiting_verification')jobs.push({id:j.id,kind:'proof' as const,family:'program' as const});if(jobs.length===10)break;}return jobs;}
export async function programWorkerCommand(worker:string,raw:unknown){
 const b=z.object({action:z.enum(['claim','heartbeat','bind','source','event','receipt','submitted','failed']),id:z.string().uuid(),lease:z.string().uuid().optional(),target:z.object({contractAddress:z.string().regex(/^[a-f0-9]{64}$/),holder:z.string().regex(/^[a-f0-9]{64}$/)}).strict().optional(),event:jobEventSchema.optional(),receipt:jobReceiptSchema.optional()}).strict().parse(raw),j=await refreshProgramJob(await getProgramJob(b.id));
 if(b.action==='claim'){if(j.status!=='queued'||!j.approvedBy)return null;await current(j);j.worker=worker;j.lease=crypto.randomUUID();j.leaseExpiresAt=Date.now()+180000;j.status='running';await save(j);return {id:j.id,lease:j.lease,sourceDigest:j.sourceDigest,target:j.target};}
 if(j.status!=='running'||j.worker!==worker||j.lease!==b.lease||(j.leaseExpiresAt??0)<=Date.now())fail('실행 권한이 만료되었습니다.',403);
 if(b.action==='heartbeat'){await current(j);j.leaseExpiresAt=Date.now()+180000;await save(j);return {active:true};}
 if(b.action==='bind'){if(!b.target||j.target&&await digest(j.target)!==await digest(b.target))fail('계약 연결을 변경할 수 없습니다.');j.target=b.target;}
 if(b.action==='source'){const result=await source(j);if(!j.chainBinding){j.chainBinding=result.body.binding;await save(j);}return result;}
 if(b.action==='event'){if(!b.event)fail('단계가 필요합니다.');if(j.events.length<150)j.events.push({...b.event,at:new Date().toISOString()});}
 if(b.action==='receipt'){const r=b.receipt;if(!r||j.target&&j.target.contractAddress!==r.contractAddress)fail('계약 영수증 불일치');const old=j.receipts.find(v=>v.txId===r.txId);if(old&&await digest(old)!==await digest(r))fail('영수증이 변경되었습니다.');if(!old){if(j.receipts.length>=12)fail('영수증 한도');j.receipts.push(r);}}
 if(b.action==='submitted'){await current(j);if(!j.chainBinding||j.receipts.filter(r=>r.operation==='submit').length!==1||!j.receipts.some(r=>r.operation==='createRequest'))fail('새 거래 영수증이 필요합니다.');j.status='awaiting_verification';j.challenge=crypto.randomUUID();j.leaseExpiresAt=0;}
 if(b.action==='failed'){j.status='needs_attention';j.reason='중단된 거래는 자동 재전송하지 않습니다. 관리자의 거래 대조가 필요합니다.';j.leaseExpiresAt=0;}
 return publicProgramJob(await save(j));
}
export async function programTask(id:string){const j=await getProgramJob(id);if(j.status!=='awaiting_verification'||!j.chainBinding||!j.challenge)fail('독립 검증 대기 상태가 아닙니다.');return programTaskSchema.parse({jobId:id,binding:j.chainBinding,receipts:j.receipts,challenge:j.challenge});}
export async function completeProgramVerification(raw:unknown){const e=z.object({body:programVerificationSchema,signature:z.string().min(80).max(100)}).strict().parse(raw),config=process.env.BIZPROOF_PROOF_VERIFIER_TRUST;if(!config)fail('검증기 신뢰 키가 필요합니다.',503);await verifySigned(publicSigningKey.parse(JSON.parse(config)),e.body,e.signature);const b=e.body,j=await getProgramJob(b.jobId),task=await programTask(j.id);if(b.challenge!==task.challenge||b.taskDigest!==await digest(task)||b.sourceDigest!==j.sourceDigest||b.contractAddress!==task.binding.contractAddress||b.requestId!==task.binding.requestId||b.eligible!==task.binding.eligible||b.receiptsVerified!==j.receipts.length||Math.abs(Date.now()-Date.parse(b.checkedAt))>60000)fail('독립 검증 결과 연결이 다릅니다.');await current(j,true);j.status='confirmed';j.verification=b;delete j.challenge;j.events.push({stage:'indexer',status:'complete',at:new Date().toISOString()});return publicProgramJob(await save(j));}
