import {z} from 'zod';
import {automaticDemoOwner} from './demo-automation';
import {env} from 'cloudflare:workers';
import {getChatGPTUser,getActiveRole} from '@/app/chatgpt-auth';
import {readState,saveState,ConflictError} from './store';
import {businessAllowed,requireBusinessAccess,type BusinessActor} from './business-access';
import {requireEvidenceAccess} from './openfga-runtime';
import {FgaError} from './openfga';
import {publicDemo,requestOrigin} from './public-demo';
import {demoWriteAllowed} from './public-demo-guard';
import {readEvidence,protectEvidence,evidenceHash} from './evidence-protection';
import {malwareConfig} from './malware-runtime';
import {scanBytes,ScanError} from './malware-scan';
import {findProgram,programProfiles,programWindow} from './program-catalog';
import {precheckProgram} from './program-rules';
import {consentChallenge,prepareProgramScenario,programScenarios,saveProgramApplication,reviewProgramApplication,ProgramError,initializeProgramData} from './program-service';
import {inspectProgramPdf,readBoundedBody,programFileLimit,ProgramDocumentError} from './program-documents';
import type {ConsentChallenge,ProgramProfile,ProgramApplication,ProgramDocument} from './program-types';
import type {State} from './domain';
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export function programFailure(error:unknown){if(error instanceof SyntaxError)return json({error:'JSON 형식의 요청이 필요합니다.'},400);if(error instanceof z.ZodError)return json({error:'입력 항목을 확인해 주세요.',issues:error.issues.map(i=>({path:i.path,message:i.message}))},400);return json({error:error instanceof ProgramError||error instanceof ConflictError||error instanceof ScanError||error instanceof ProgramDocumentError?error.message:'요청을 처리하지 못했습니다. 연결과 문서를 확인하고 다시 시도하세요.'},error instanceof ProgramError||error instanceof ScanError||error instanceof FgaError||error instanceof ProgramDocumentError?error.status:error instanceof ConflictError?409:500);}
export async function context(req:Request,write=false){const user=await getChatGPTUser(),role=await getActiveRole();if(!user||!role)throw new ProgramError('로그인 후 이용하세요.',401);if(write){if(req.headers.get('origin')!==requestOrigin(req))throw new ProgramError('같은 사이트에서 요청해 주세요.',403);if(!await demoWriteAllowed(user.userId))throw new ProgramError('잠시 후 다시 시도하세요.',429);}return {user,actor:{actor:user.userId,owner:user.storageOwner,role,authMode:user.authMode} satisfies BusinessActor};}
async function body(req:Request){return JSON.parse(new TextDecoder().decode(await readBoundedBody(req,20000)));}
function profile(id:string){const p=findProgram(id);if(!p)throw new ProgramError('프로필을 찾을 수 없습니다.',404);return p;}
async function companyAccess(state:State,id:string,actor:BusinessActor,write=false){const c=state.companies.find(c=>c.id===id);if(!c)throw new ProgramError('기업을 찾을 수 없습니다.',404);await requireBusinessAccess(actor,id,write);return c;}
function applicant(actor:BusinessActor){if(!['company','admin','issuer'].includes(actor.role))throw new ProgramError('신청 기업 역할에서 진행하세요.',403);}
function dataRequired(state:State){if(!state.programData)throw new ProgramError('먼저 시연 자료를 준비해 주세요.',409);return state.programData;}
export async function readDocument(owner:string,d:ProgramDocument){const obj=await env.BUCKET?.get(d.key);if(!obj)throw new ProgramError('증빙 파일을 찾을 수 없습니다.',404);const bytes=await readEvidence(owner,d.key,obj,d.sha256,programFileLimit);const pdf=await inspectProgramPdf(bytes);if(bytes.byteLength!==d.size||pdf.pages!==d.pages)throw new ProgramError('파일 정보가 변경되었습니다.');return bytes;}
export async function check(state:State,p:ProgramProfile,id:string,actor:BusinessActor){const company=await companyAccess(state,id,actor),data=dataRequired(state),verified=new Set<string>();for(const d of data.documents.filter(d=>d.companyId===id)){try{const bytes=await readDocument(actor.owner,d);if(d.source==='pilot'){const config=malwareConfig();if(!config)continue;await scanBytes(bytes,config,fetch,programFileLimit);}verified.add(d.id);}catch{/* A missing, changed or unsafe file remains unknown, never a successful check. */}}return precheckProgram({data,company,profile:p,verifiedDocuments:verified});}
function assignedReviewer(actor:BusinessActor,organization:string|null|undefined,profileId:string){
 if(actor.authMode!=='keycloak')return true;
 const assignments=z.array(z.object({actor:z.string(),organization:z.string(),profileId:z.string()})).parse(JSON.parse(process.env.BIZPROOF_PROGRAM_REVIEWERS??'[]'));
 return !!organization&&assignments.some(a=>a.actor===actor.actor&&a.organization===organization&&a.profileId===profileId);
}
export function applicationSummary(a:ProgramApplication){return {id:a.id,companyId:a.companyId,profileId:a.profile.id,name:a.profile.name,createdAt:a.createdAt,revision:a.revision,status:a.status,precheck:a.precheck,history:a.history,externalReceipt:a.externalReceipt,mode:a.mode};}
export async function getPrograms(req:Request){const {actor,user}=await context(req),{state}=await readState(actor.owner);const companies=[];for(const c of state.companies)if(await businessAllowed(actor,c.id))companies.push({id:c.id,name:c.name,synthetic:!!state.programData?.scenarios.some(s=>s.companyId===c.id)});const allowed=new Set(companies.map(c=>c.id));return json({profiles:programProfiles.map(p=>({...p,windowStatus:programWindow(p)})),companies,scenarios:programScenarios,applications:(state.programData?.applications??[]).filter(a=>allowed.has(a.companyId)&&(['admin','issuer','company'].includes(actor.role)?a.actor===actor.actor||actor.role==='admin':a.profile.kind===actor.role&&assignedReviewer(actor,user.organization,a.profile.id))).map(applicationSummary),autoRun:actor.authMode==='demo'&&actor.owner===actor.actor&&automaticDemoOwner(actor.owner),canPrepareDemo:actor.authMode==='demo',canUpload:actor.authMode==='keycloak'&&!publicDemo()&&process.env.BIZPROOF_PROGRAM_PILOT==='true',notice:'공개 조건에 따른 내부 준비 도구입니다. 공식 접수·선정·거래 등록과 별개이며, 공개 자동 시연은 최초 동의 후 Midnight 실행까지 이어지며 기관의 실제 심사는 포함하지 않습니다.'});}
export async function preparePrograms(req:Request){const {actor}=await context(req,true);applicant(actor);if(actor.authMode!=='demo')throw new ProgramError('합성 시연 자료는 개인 체험 공간에서만 만들 수 있습니다.',403);const {scenario}=z.object({scenario:z.enum(programScenarios)}).strict().parse(await body(req));return json({companyId:await prepareScenarioForActor(actor,scenario)});}
export async function prepareScenarioForActor(actor:BusinessActor,scenario:typeof programScenarios[number]){const {state,version}=await readState(actor.owner);if(!env.BUCKET)throw new ProgramError('증빙 저장소가 필요합니다.',503);const created:string[]=[];try{const companyId=await prepareProgramScenario(state,scenario,async(d,bytes)=>{const file=await protectEvidence(actor.owner,d.key,bytes);await env.BUCKET!.put(d.key,file.body,{httpMetadata:{contentType:file.encrypted?'application/json':'application/pdf'},customMetadata:file.encrypted?{protection:'openbao-v1'}:{}});created.push(d.key);},actor.owner);await saveState(actor.owner,state,version);return companyId;}catch(e){await Promise.all(created.map(key=>env.BUCKET!.delete(key)));throw e;}}
export async function precheckPrograms(req:Request,id:string){const {actor}=await context(req,true);applicant(actor);const {companyId}=z.object({companyId:z.string().min(1).max(100)}).strict().parse(await body(req));const {state}=await readState(actor.owner),result=await check(state,profile(id),companyId,actor);return json({precheck:result,consent:await consentChallenge(dataRequired(state),result,actor.actor,actor.owner)});}
const consentSchema=z.object({body:z.object({context:z.literal('bizproof:program-consent:1'),actor:z.string().max(200),owner:z.string().max(200),companyId:z.string().max(100),profileId:z.string().max(100),profileHash:z.string().length(64),fingerprint:z.string().length(64),nonce:z.string().uuid(),expiresAt:z.string().datetime(),scope:z.literal('company-and-checks-and-document-manifest')}).strict(),signature:z.string().max(200)}).strict();
export async function createProgramApplication(req:Request){const {actor}=await context(req,true);applicant(actor);const input=z.object({consent:consentSchema,confirmed:z.literal(true)}).strict().parse(await body(req));const {state,version}=await readState(actor.owner),data=dataRequired(state),p=profile(input.consent.body.profileId);await companyAccess(state,input.consent.body.companyId,actor,true);if(actor.authMode!=='demo')throw new ProgramError('확장 자격의 실기관 발급·대표권 검증 연결 전에는 합성 시연만 저장할 수 있습니다.',409);const precheck=await check(state,p,input.consent.body.companyId,actor),application=await saveProgramApplication(data,{actor:actor.actor,owner:actor.owner,profile:p,precheck,consent:input.consent as ConsentChallenge,confirmed:input.confirmed});await saveState(actor.owner,state,version);return json(applicationSummary(application));}
export async function getApplication(req:Request,id:string,write=false){const ctx=await context(req,write),stored=await readState(ctx.actor.owner),application=dataRequired(stored.state).applications.find(a=>a.id===id);if(!application)throw new ProgramError('준비 기록을 찾을 수 없습니다.',404);await companyAccess(stored.state,application.companyId,ctx.actor,write);return {...ctx,...stored,application};}
export async function reviewPrograms(req:Request,id:string){const ctx=await getApplication(req,id,true),{actor,user,application,state,version}=ctx;if(actor.role!=='admin'&&actor.role!==application.profile.kind)throw new ProgramError('해당 기관 담당자 역할이 필요합니다.',403);if(!assignedReviewer(actor,user.organization,application.profile.id))throw new ProgramError('이 기관의 심사 권한이 배정되지 않았습니다.',403);
 const input=z.object({revision:z.number().int().min(0),ruleId:z.string().max(100),decision:z.enum(['confirmed','needs_changes']),reason:z.string().trim().min(10).max(1000),evidenceIds:z.array(z.string().uuid()).min(1).max(30)}).strict().parse(await body(req));
 const fresh=await check(state,application.profile,application.companyId,actor);if(fresh.fingerprint!==application.precheck.fingerprint)throw new ProgramError('원본 자격·서류·접수 기간이 변경되었습니다. 새 사전검사와 동의가 필요합니다.',409);
 reviewProgramApplication(application,input,actor.actor);state.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),actor:actor.actor,role:actor.role,action:'program.review',target:application.companyId,detail:`${application.profile.id} · ${input.ruleId} · ${input.decision}`});await saveState(actor.owner,state,version);return json(applicationSummary(application));}
export async function packageProgram(req:Request,id:string){const {actor,state,application}=await getApplication(req,id);applicant(actor);if(actor.role!=='admin'&&application.actor!==actor.actor)throw new ProgramError('신청 준비 당사자만 내려받을 수 있습니다.',403);const fresh=await check(state,application.profile,application.companyId,actor),data=dataRequired(state);const manifest={format:'bizproof-submission-manifest-v1',notice:'공식 접수증이 아닙니다. 선택한 기관의 공식 사이트에서 원본 제출 절차를 완료해야 합니다. 이 파일에는 원본 매출·투자 값과 PDF 본문을 포함하지 않습니다.',application:{id:application.id,companyId:application.companyId,organization:application.profile.organization,createdAt:application.createdAt,profile:application.profile,precheck:application.precheck,history:application.history,status:application.status},current:{checkedAt:fresh.evaluatedAt,unchanged:fresh.fingerprint===application.precheck.fingerprint,outcome:fresh.outcome,warnings:fresh.warnings},externalReceipt:null,documents:application.precheck.documents.map(e=>{const d=data.documents.find(d=>d.id===e.id);return {...e,name:d?.name,type:d?.type,source:d?.source,downloadUrl:`/api/program-documents/${e.id}`};}),verification:{context:'bizproof:program-package:1',keyId:data.receiptKey.keyId,publicKey:data.receiptKey.publicKey,signature:''}};const payload=Object.fromEntries(Object.entries(manifest).filter(([key])=>key!=='verification'));manifest.verification.signature=await import('./signatures').then(m=>m.sign(data.receiptKey.privateKey,{context:manifest.verification.context,payload}));return new Response(JSON.stringify(manifest,null,2),{headers:{'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="bizproof-${id}.json"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export async function downloadProgramDocument(req:Request,id:string){const {actor,user}=await context(req),{state}=await readState(actor.owner),d=dataRequired(state).documents.find(d=>d.id===id);if(!d)throw new ProgramError('서류를 찾을 수 없습니다.',404);applicant(actor);await companyAccess(state,d.companyId,actor);await requireEvidenceAccess(user,d.companyId,'read');const bytes=await readDocument(actor.owner,d);if(d.source==='pilot'){const config=malwareConfig();if(!config)throw new ScanError();await scanBytes(bytes,config,fetch,programFileLimit);}return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="${id}.pdf"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export async function uploadProgramDocument(req:Request){const {actor,user}=await context(req,true);applicant(actor);if(publicDemo()||actor.authMode!=='keycloak'||process.env.BIZPROOF_PROGRAM_PILOT!=='true')throw new ProgramError('실제 PDF 업로드는 승인된 실증 계정에서만 사용할 수 있습니다.',403);const url=new URL(req.url),p=profile(url.searchParams.get('profileId')??''),companyId=url.searchParams.get('companyId')??'',type=url.searchParams.get('type')??'',requirement=p.documents.find(d=>d.type===type);if(!requirement||req.headers.get('content-type')!=='application/pdf')throw new ProgramError('대상 서류 유형과 PDF 형식을 확인하세요.');const {state,version}=await readState(actor.owner);await companyAccess(state,companyId,actor,true);await requireEvidenceAccess(user,companyId,'write');const data=state.programData??=await initializeProgramData();if(data.documents.filter(d=>d.companyId===companyId).length>=30)throw new ProgramError('기업별 문서는 30개까지 보관할 수 있습니다.',429);const bytes=await readBoundedBody(req,requirement.maxBytes),config=malwareConfig();if(!config)throw new ScanError();await scanBytes(bytes,config,fetch,programFileLimit);const {pages}=await inspectProgramPdf(bytes);if(requirement.maxPages&&pages>requirement.maxPages)throw new ProgramError(`${requirement.label}는 ${requirement.maxPages}쪽 이하여야 합니다.`);if(!env.BUCKET)throw new ProgramError('증빙 저장소 연결이 필요합니다.',503);const id=crypto.randomUUID(),d:ProgramDocument={id,companyId,type:requirement.type,name:requirement.label+'.pdf',key:`evidence/${actor.owner}/${id}`,sha256:await evidenceHash(bytes),size:bytes.byteLength,pages,createdAt:new Date().toISOString(),source:'pilot',scan:'clean'};const file=await protectEvidence(actor.owner,d.key,bytes,programFileLimit);await env.BUCKET.put(d.key,file.body,{customMetadata:file.encrypted?{protection:'openbao-v1'}:{}});try{data.documents.push(d);await saveState(actor.owner,state,version);}catch(e){await env.BUCKET.delete(d.key);throw e;}return json({id,pages,size:d.size,sha256:d.sha256});}
