import type { State,Credential,Issuer } from './domain';
import {credentialPayload} from './domain';
import {makeKeys,sign} from './signatures';
export async function seedState():Promise<State>{
 const now=new Date().toISOString(), expiry=new Date(Date.now()+180*864e5).toISOString();
 const keys=await makeKeys();
 const issuer:Issuer={id:'issuer-bizproof',name:'BizProof 테스트 인증원',did:'did:web:demo.bizproof.local:issuers:bizproof',status:'active',keyId:'key-1',...keys,previousKeys:[],createdAt:now};
 const s:State={companies:[{id:'hanbit',name:'주식회사 한빛테크',registration:'DEMO-110-01',industry:'소프트웨어',region:'서울',contact:'hello@hanbit.example',createdAt:now},{id:'nova',name:'노바머티리얼즈',registration:'DEMO-220-02',industry:'첨단 소재',region:'경기',contact:'office@nova.example',createdAt:now},{id:'orbit',name:'오르빗랩스',registration:'DEMO-330-03',industry:'데이터 분석',region:'서울',contact:'team@orbit.example',createdAt:now}],issuers:[issuer],credentials:[],policies:[{id:'vendor-standard',name:'2026 협력사 사전 등록',audience:'미래산업 구매팀',kind:'buyer',version:1,minRevenue:200000000,maxRevenue:null,maxAgeMonths:null,region:null,requireCertification:false,issuerIds:[issuer.id],createdAt:now,status:'active'},{id:'grant-startup',name:'서울 스타트업 성장 지원',audience:'서울창업지원센터 (가상)',kind:'grant',version:1,minRevenue:null,maxRevenue:500000000,maxAgeMonths:36,region:'서울',requireCertification:false,issuerIds:[issuer.id],createdAt:now,status:'active'},{id:'vendor-premium',name:'프리미엄 공급망 파트너',audience:'미래산업 구매팀',kind:'buyer',version:1,minRevenue:500000000,maxRevenue:null,maxAgeMonths:null,region:null,requireCertification:true,issuerIds:[issuer.id],createdAt:now,status:'active'}],requests:[],presentations:[],audit:[],schemas:[{id:'business-v1',name:'기업 기본 · 재무 자격',version:1,description:'서명된 기업 속성을 검증 정책에 재사용합니다.',fields:[{key:'revenue',label:'연 매출액',type:'integer',private:true},{key:'foundedOn',label:'설립일',type:'date',private:true},{key:'region',label:'소재지',type:'string',private:true},{key:'certified',label:'인증 보유',type:'boolean',private:true}],createdAt:now}],connections:[{id:'connection-1',companyId:'hanbit',organization:'미래산업 구매팀',kind:'buyer',status:'accepted',createdAt:now},{id:'connection-2',companyId:'hanbit',organization:'서울창업지원센터 (가상)',kind:'grant',status:'pending',createdAt:now}],evidence:[],settings:{name:'기업 신뢰 네트워크'}};
 const founded=new Date();founded.setUTCMonth(founded.getUTCMonth()-24);
 for(const [i,company] of s.companies.entries()){const c:Credential={id:`credential-${company.id}`,companyId:company.id,issuerId:issuer.id,schemaId:'business-v1',claims:{revenue:[300000000,800000000,70000000][i],foundedOn:founded.toISOString().slice(0,10),region:company.region,certified:i!==2},issuedAt:now,expiresAt:expiry,keyId:issuer.keyId,status:'active',signature:''};c.signature=await sign(issuer.privateKey,credentialPayload(c));s.credentials.push(c);}
 s.audit.push({id:crypto.randomUUID(),at:now,role:'admin',action:'workspace.created',target:'BizProof',detail:'가상 기업 3개와 테스트 자격으로 데모 시작'});return s;
}
