import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const workspaces=sqliteTable('workspaces',{owner:text('owner').primaryKey(),payload:text('payload').notNull(),version:integer('version').notNull().default(0)});

export const visitorEvents=sqliteTable('visitor_events',{id:text('id').primaryKey(),occurred_at:text('occurred_at').notNull(),month:text('month').notNull(),day:text('day').notNull(),visitor_id:text('visitor_id').notNull(),user_id:text('user_id'),name:text('name'),ip:text('ip'),country:text('country'),region:text('region'),city:text('city'),geo_source:text('geo_source').notNull(),user_agent:text('user_agent').notNull(),browser:text('browser').notNull(),os:text('os').notNull(),device:text('device').notNull(),path:text('path').notNull()},t=>[index('visitor_events_month_time').on(t.month,t.occurred_at),index('visitor_events_user').on(t.user_id,t.occurred_at),index('visitor_events_visitor').on(t.visitor_id,t.occurred_at)]);
export const analyticsAdminAudit=sqliteTable('analytics_admin_audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),occurred_at:text('occurred_at').notNull(),action:text('action').notNull(),month:text('month').notNull()});
export const visitorProfiles=sqliteTable('visitor_profiles',{visitor_id:text('visitor_id').primaryKey(),name:text('name').notNull(),company:text('company').notNull(),created_at:text('created_at').notNull(),updated_at:text('updated_at').notNull()});
export const adminCredentials=sqliteTable('admin_credentials',{username:text('username').primaryKey(),password_hash:text('password_hash').notNull(),revision:integer('revision').notNull().default(0),changed_at:text('changed_at')});
export const adminSecurityAudit=sqliteTable('admin_security_audit',{revision:integer('revision').primaryKey(),occurred_at:text('occurred_at').notNull(),action:text('action').notNull()});
export const adminPasswordRate=sqliteTable('admin_password_rate',{username:text('username').primaryKey(),window:integer('window').notNull(),n:integer('n').notNull()});
