import {getChatGPTUser,getActiveRole} from '@/app/chatgpt-auth';
import {binding,readState,saveState,ConflictError} from '@/lib/store';
import {protectionMode,storageClient,storageEnvelope} from '@/lib/storage-protection';
import {z} from 'zod';
export const dynamic='force-dynamic';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
async function access(){const user=await getChatGPTUser();if(!user)return null;return (await getActiveRole())==='admin'?user:null;}
export async function GET(){const user=await access();if(!user)return json({error:'관리자 로그인이 필요합니다.'},403);try{const mode=protectionMode(),row=await binding().prepare('SELECT payload,version FROM workspaces WHERE owner=?').bind(user.storageOwner).first<{payload:string;version:number}>(),envelope=row?storageEnvelope(row.payload):null;let latestVersion:number|null=null,available=false;if(mode==='openbao'){try{latestVersion=(await storageClient().metadata()).latestVersion;available=true;}catch{/* Expose no upstream response or credentials. */}}
 return json({mode,available,stored:row?'existing':'empty',encrypted:!!envelope,keyVersion:envelope?Number(envelope.ciphertext.split(':')[1].slice(1)):null,latestVersion,needsMigration:!!row&&!envelope&&mode==='openbao'});
 }catch{return json({error:'저장소 보호 설정 또는 데이터 형식을 확인하세요.'},503);}}
export async function POST(req:Request){const user=await access();if(!user)return json({error:'관리자 로그인이 필요합니다.'},403);if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'허용되지 않는 출처입니다.'},403);try{const raw=await req.text();if(raw.length>200)return json({error:'요청이 너무 큽니다.'},413);const {action}=z.object({action:z.enum(['protect','rewrap'])}).strict().parse(JSON.parse(raw));if(protectionMode()!=='openbao')return json({error:'서버에서 OpenBao 모드를 먼저 설정하세요.'},409);
 if(action==='protect'){const {state,version}=await readState(user.storageOwner);state.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),actor:user.userId,role:'admin',action:'storage.protect',target:'workspace',detail:'워크스페이스 Transit 암호화 저장'});await saveState(user.storageOwner,state,version);}else{const row=await binding().prepare('SELECT payload,version FROM workspaces WHERE owner=?').bind(user.storageOwner).first<{payload:string;version:number}>();if(!row)return json({error:'암호화할 워크스페이스가 없습니다.'},409);const envelope=storageEnvelope(row.payload);if(!envelope)return json({error:'먼저 기존 데이터를 암호화하세요.'},409);const updated=await storageClient().rewrap(user.storageOwner,envelope);const result=await binding().prepare('UPDATE workspaces SET payload=?,version=version+1 WHERE owner=? AND version=?').bind(JSON.stringify(updated),user.storageOwner,row.version).run();if(result.meta.changes!==1)throw new ConflictError();}
 return json({ok:true});
 }catch(e){if(e instanceof ConflictError)return json({error:e.message},409);if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:'올바른 작업을 지정하세요.'},400);return json({error:'암호화 작업을 완료하지 못했습니다. 설정·서버 상태·토큰 권한을 확인하세요. 평문 대체 저장은 하지 않았습니다.'},503);}}
