import {z} from 'zod';
import {sourceCanonical} from './web-source.ts';
import {verifySigned,sourceHash} from './issued-source.ts';
const text=z.string().min(1).max(200),hex=z.string().regex(/^[a-f0-9]{64}$/),uint=z.number().int().min(0).max(1e15);
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v>='1970-01-01');
const facts=z.object({foundedOn:date.optional(),registered:z.boolean().optional(),newIndustry:z.boolean().optional(),revenueKrw:uint.optional(),fiscalYear:uint.max(65535).optional(),investmentKrw:uint.optional(),plannedResidents:uint.max(1000000).optional(),nationalTaxClear:z.boolean().optional(),localTaxClear:z.boolean().optional(),noHubHistory:z.boolean().optional(),noDuplicateSpace:z.boolean().optional(),womenBusiness:z.boolean().optional()}).strict();
export const programOriginalSchema=z.object({id:text,schemaVersion:z.literal('bizproof:program-facts:1'),companyId:text,registration:text,issuerId:text,keyId:text,facts,evidence:z.array(z.object({id:text,sha256:hex}).strict()).min(1).max(30),issuedAt:z.string().datetime(),expiresAt:z.string().datetime(),status:z.literal('active'),signature:z.string().min(80).max(100),source:z.literal('synthetic')}).strict();
export const numericPolicySchema=z.object({minRevenue:uint,minInvestment:uint,fiscalYear:uint.max(65535),requireFinance:z.boolean(),minResidents:uint.max(1000000),minFoundedDay:uint.max(4294967295),maxFoundedDay:uint.max(4294967295),issuerId:uint.min(1).max(65535)}).strict().refine(p=>p.minFoundedDay<=p.maxFoundedDay);
export const programSourceSchema=z.object({body:z.object({context:z.literal('bizproof:program-numeric-source:1'),network:z.literal('undeployed'),applicationId:text,companyId:text,registration:text,actor:text,profileId:z.literal('ai-hub-2026-leading'),profileHash:hex,nonce:hex,holder:hex,contractAddress:hex,issuedAt:uint,expiresAt:uint,policy:numericPolicySchema,originals:z.array(programOriginalSchema).min(1).max(10),documents:z.array(z.object({id:text,sha256:hex}).strict()).min(1).max(30),coverage:z.tuple([z.literal('finance-or'),z.literal('residents')]),fullEligibility:z.literal(false)}).strict(),signature:z.string().min(80).max(100)}).strict();
export type ProgramNumericSource=z.infer<typeof programSourceSchema>;
export type ProgramIssuerPin={issuerId:string;keyId:string;publicKey:JsonWebKey;facts:string[];active:boolean};
export async function verifyProgramNumericSource(raw:unknown,pins:{platform:JsonWebKey;issuers:ProgramIssuerPin[]},expected:{applicationId:string;companyId:string;registration:string;actor:string;profileHash:string;nonce:string;holder:string;contractAddress:string;policy:z.infer<typeof numericPolicySchema>},currentStatus:(id:string)=>Promise<'active'|'revoked'|'unknown'>,now=Math.floor(Date.now()/1000)){
 const source=programSourceSchema.parse(raw),b=source.body;
 const verifyPublic=(key:JsonWebKey,payload:unknown,signature:string)=>{if(key.d)throw Error('Use a pinned public key, not a private key');return verifySigned({kty:key.kty,crv:key.crv,x:key.x},payload,signature);};
 await verifyPublic(pins.platform,b,source.signature);
 if(b.applicationId!==expected.applicationId||b.companyId!==expected.companyId||b.registration!==expected.registration||b.actor!==expected.actor||b.profileHash!==expected.profileHash||b.nonce!==expected.nonce||b.holder!==expected.holder||b.contractAddress!==expected.contractAddress||sourceCanonical(b.policy)!==sourceCanonical(expected.policy)||b.issuedAt>now||b.expiresAt<=now||b.expiresAt-b.issuedAt>300||new Set(b.originals.map(c=>c.id)).size!==b.originals.length||new Set(b.documents.map(d=>d.id)).size!==b.documents.length)throw Error('Program source target, policy or lifetime mismatch');
 for(const c of b.originals){const pin=pins.issuers.find(i=>i.issuerId===c.issuerId&&i.keyId===c.keyId);if(!pin?.active||Object.keys(c.facts).some(k=>!pin.facts.includes(k))||c.companyId!==b.companyId||c.registration!==b.registration||Date.parse(c.issuedAt)>now*1000||Date.parse(c.expiresAt)<=now*1000||Date.parse(c.expiresAt)<b.expiresAt*1000||c.evidence.some(e=>!b.documents.some(d=>d.id===e.id&&d.sha256===e.sha256))||await currentStatus(c.id)!=='active')throw Error('Program issuer, company, evidence or current credential status mismatch');
  const body=Object.fromEntries(Object.entries(c).filter(([key])=>!['status','signature'].includes(key)));await verifyPublic(pin.publicKey,{context:'bizproof:program-credential:1',body},c.signature);
 }
 const fact=(name:keyof z.infer<typeof facts>)=>{const values=b.originals.filter(c=>c.facts[name]!==undefined).map(c=>c.facts[name]);if(!values.length||new Set(values.map(sourceCanonical)).size!==1)throw Error('Missing or conflicting numeric source: '+name);return values[0];};
 const revenue=fact('revenueKrw'),fiscalYear=fact('fiscalYear'),investment=fact('investmentKrw'),residents=fact('plannedResidents'),foundedOn=fact('foundedOn');
 if(typeof revenue!=='number'||typeof fiscalYear!=='number'||typeof investment!=='number'||typeof residents!=='number'||typeof foundedOn!=='string'||Date.parse(foundedOn)>now*1000)throw Error('Invalid numeric source type or date');
 // Revenue and its accounting period must come from the same signed credential.
 if(!b.originals.some(c=>c.facts.revenueKrw===revenue&&c.facts.fiscalYear===fiscalYear))throw Error('Revenue period is not bound to the same credential');
 const bytes=(s:string)=>Uint8Array.from(s.match(/../g)!,x=>parseInt(x,16));
 const bundleDigest=await sourceHash(b.originals),companyCommitment=await sourceHash({companyId:b.companyId,registration:b.registration});
 return {source:b,networkConnected:false as const,proofGenerated:false as const,fullEligibility:false as const,claims:{revenue:BigInt(revenue),fiscalYear:BigInt(fiscalYear),investment:BigInt(investment),plannedResidents:BigInt(residents),foundedDay:BigInt(Math.floor(Date.parse(foundedOn)/864e5)),companyCommitment:bytes(companyCommitment),bundleDigest:bytes(bundleDigest),credentialId:bytes(await sourceHash({context:b.context,applicationId:b.applicationId,bundleDigest})),issuedAt:BigInt(b.issuedAt),expiresAt:BigInt(b.expiresAt)}};
}
