import type {TransactionState} from './transaction-state.ts';
import {randomBytes} from 'node:crypto';
import {BizProofClient,type WalletBinding} from './client.ts';
import {IssuerVault} from './issuer.ts';
import {bytes32,type Network} from './config.ts';
// Invokes real SDK transactions when funded wallet bindings and network services are supplied.
// Uses fictional company attributes. It neither imports nor re-signs an existing BizProof web credential.
export async function runNetworkReuse(options:{onTransaction?:(role:'administrator'|'holder',state:TransactionState)=>void;network:Network;administratorWallet:WalletBinding;holderWallet:WalletBinding;storageDirectory:string;passwordProvider:()=>Promise<string>|string;onReceipt:(receipt:Awaited<ReturnType<BizProofClient['deploy']>>)=>Promise<void>}){
 const admin=new BizProofClient({...options,wallet:options.administratorWallet,role:'administrator'}),holder=new BizProofClient({...options,wallet:options.holderWallet,role:'holder'});
 if(options.onTransaction){admin.watchTransactions(state=>options.onTransaction!('administrator',state));holder.watchTransactions(state=>options.onTransaction!('holder',state));}
 let issuer:IssuerVault|undefined;
 try{const deployment=await admin.deploy();await options.onReceipt(deployment);const contractAddress=deployment.contractAddress;
  issuer=new IssuerVault({...options,accountId:options.administratorWallet.accountId},contractAddress);const issuerKey=await issuer.create(1n);await options.onReceipt(await admin.registerIssuer(1n,issuerKey.publicKey));
  const enrollment=await holder.enrollHolder(contractAddress);const now=BigInt(Math.floor(Date.now()/1000)),credentialId=new Uint8Array(randomBytes(32));const attestation=await issuer.issue(1n,{credentialId,revenue:300000000n,foundedDay:BigInt(Math.floor(Date.now()/864e5)-730),region:1n,certified:true,expiresAt:now+86400n},bytes32(enrollment.holder));await holder.storeAttestation(attestation.claims,attestation.signature);
  const outcomes=[];for(const scenario of [{name:'buyer',minRevenue:200000000n,maxRevenue:1000000000000n},{name:'grant',minRevenue:0n,maxRevenue:500000000n},{name:'negative',minRevenue:500000000n,maxRevenue:1000000000000n}]){await options.onReceipt(await admin.advanceTime());const id=new Uint8Array(randomBytes(32));await options.onReceipt(await admin.createRequest(id,{holder:attestation.holder,audience:new Uint8Array(randomBytes(32)),nonce:new Uint8Array(randomBytes(32)),deadline:BigInt(Math.floor(Date.now()/1000)+3600),policy:{issuerId:1n,minRevenue:scenario.minRevenue,maxRevenue:scenario.maxRevenue,minFoundedDay:scenario.name==='grant'?BigInt(Math.floor(Date.now()/864e5)-1095):0n,region:scenario.name==='grant'?1n:0n,requireCertification:false}}));await options.onReceipt(await holder.submit(id));outcomes.push({scenario:scenario.name,credentialHandle:Buffer.from(credentialId).toString('hex'),state:await holder.inspect(Buffer.from(id).toString('hex'))});}
  const revokedRequest=new Uint8Array(randomBytes(32));await options.onReceipt(await admin.createRequest(revokedRequest,{holder:attestation.holder,audience:new Uint8Array(randomBytes(32)),nonce:new Uint8Array(randomBytes(32)),deadline:BigInt(Math.floor(Date.now()/1000)+3600),policy:{issuerId:1n,minRevenue:0n,maxRevenue:1000000000000n,minFoundedDay:0n,region:0n,requireCertification:false}}));
  await options.onReceipt(await admin.revokeCredential(credentialId));let revokedSubmissionBlocked=false;try{await holder.submit(revokedRequest);}catch(e){let current:unknown=e;for(let depth=0;depth<5&&current instanceof Error;depth++){if(current.message.includes('Credential revoked'))revokedSubmissionBlocked=true;current=current.cause;}if(!revokedSubmissionBlocked)throw e;}if(!revokedSubmissionBlocked)throw Error('취소된 자격의 제출이 차단되지 않았습니다.');return {mode:'midnight-finalized' as const,contractAddress,outcomes,credentialRevoked:true,revokedSubmissionBlocked,blockStage:'SDK circuit assertion',notice:'취소 거래 확정 후 SDK의 회로 실행에서 재사용을 거절했습니다. 실패한 제출의 거래 영수증이 생성된 것은 아닙니다.'};
 }finally{await issuer?.close();await holder.close();await admin.close();}
}
